INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_1763731497291', 'Engineer', '400977', 'SACODECO', '400977', 'Saudi', '2059537924');
INSERT OR REPLACE INTO workers (id, name, company, employee_id, nationaliy, id_number, role, transfer_destination, status) VALUES ('w_1763817984229', 'تهامي سباك', 'Sacodeco', '39469', 'Saudi', '101010101010', 'Engineer', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_1764141465208', 'Worker', 'محمد سبيل محمد اسلم', 'FAST', '59250', 'Pakistan', '101010101011');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, transfer_destination, status) VALUES ('w_1765185345153', 'Supervisor', 'Sadru Din', 'SACODECO', '28590', 'India', '2174608311', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_001_فاست_RENT_ROOM', 'Engineer', 'store fast', 'فاست RENT ROOM', '001', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_16924_الالمنيوم', 'Worker', 'احمد عبدالرزاق احمد منصور', 'الالمنيوم', '16924', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_16969_الالمنيوم', 'Worker', 'محمد الضيفى محمد احمد', 'الالمنيوم', '16969', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_17610_الالمنيوم', 'Worker', 'محمد سرفراز محمد', 'الالمنيوم', '17610', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_18014_الالمنيوم', 'Worker', 'فرج شنواز', 'الالمنيوم', '18014', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_18217929_فاست', 'Worker', 'سوبون مولا', 'فاست', '18217929', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_19953_الالمنيوم', 'Worker', 'فرغلي عطار رضوان', 'الالمنيوم', '19953', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20181_فاست', 'Worker', 'محمد نديم', 'فاست', '20181', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20196_فاست', 'Worker', 'رجوان خان اشتياق احمد خان', 'فاست', '20196', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20198_فاست', 'Worker', 'غلام مصطفى شمشاد', 'فاست', '20198', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20201_فاست', 'Worker', 'محمد كمالو', 'فاست', '20201', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20204_فاست', 'Worker', 'محمد نعيم', 'فاست', '20204', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20206_فاست', 'Worker', 'كليم احمد شكيل احمد', 'فاست', '20206', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20209_فاست', 'Worker', 'اسد انصارى سلطان احمد انصارى', 'فاست', '20209', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20213_فاست', 'Worker', 'محمد كاف شاهد على', 'فاست', '20213', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20216_فاست', 'Worker', 'عبدالله', 'فاست', '20216', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20217_فاست', 'Worker', 'محمد نواز حسن', 'فاست', '20217', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20221_فاست', 'Worker', 'اركان احمد', 'فاست', '20221', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20226_فاست', 'Worker', 'ترفيز خان موناو خان', 'فاست', '20226', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20231_فاست', 'Worker', 'سافيق رفيق', 'فاست', '20231', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20248_فاست', 'Worker', 'محمد طارق', 'فاست', '20248', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20273_فاست', 'Worker', 'قل شير شمش دين', 'فاست', '20273', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20274_فاست', 'Worker', 'اكرام محمد نافي', 'فاست', '20274', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20287_فاست', 'Worker', 'محمد جلفان', 'فاست', '20287', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20289_فاست', 'Worker', 'محمد عنبر بان', 'فاست', '20289', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20293_فاست', 'Worker', 'اويس على', 'فاست', '20293', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20307_فاست', 'Worker', 'محمد اشرف شوبدار', 'فاست', '20307', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20312_فاست', 'Worker', 'وقار احمد', 'فاست', '20312', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20316_فاست', 'Worker', 'جمال دين', 'فاست', '20316', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20327_فاست', 'Worker', 'نعيم شهزادة', 'فاست', '20327', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20332_فاست', 'Worker', 'رجوان دين صغير على', 'فاست', '20332', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20333_فاست', 'Worker', 'سيف الله سعيد الإسلام', 'فاست', '20333', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20335_فاست', 'Worker', 'نديم إقبال محمد قاسم', 'فاست', '20335', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20336_فاست', 'Worker', 'مو أرشد مو أنيش', 'فاست', '20336', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20345_فاست', 'Worker', 'مجاهد رجا', 'فاست', '20345', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20347_فاست', 'Worker', 'الشيخ اسماعيل الشيخ شميم', 'فاست', '20347', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20348_فاست', 'Worker', 'شهباج خان حسامت خان', 'فاست', '20348', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20350_فاست', 'Worker', 'رفيق فضل  ربيع', 'فاست', '20350', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status, transfer_destination) VALUES ('w_emp_20361_فاست', 'Worker', 'شاروخ', 'فاست', '20361', 'Indian', '', 'Active', NULL);
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20363_فاست', 'Worker', 'عمران', 'فاست', '20363', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20365_فاست', 'Worker', 'علي أكبر', 'فاست', '20365', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20367_فاست', 'Worker', 'عبد الله', 'فاست', '20367', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20373_فاست', 'Worker', 'علي داود', 'فاست', '20373', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20374_فاست', 'Worker', 'آصف محمود', 'فاست', '20374', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20380_فاست', 'Worker', 'اكرم علي', 'فاست', '20380', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20384_فاست', 'Worker', 'محمد صدام', 'فاست', '20384', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20386_فاست', 'Worker', 'محمد اسعد رشيد', 'فاست', '20386', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20387_فاست', 'Worker', 'فياض الرحمن', 'فاست', '20387', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20390_فاست', 'Worker', 'سجاد خان', 'فاست', '20390', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20403_فاست', 'Worker', 'محمد أبوبكر', 'فاست', '20403', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20407_فاست', 'Worker', 'شاه زيب خان', 'فاست', '20407', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20408_فاست', 'Worker', 'عبد السلام', 'فاست', '20408', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20427_فاست', 'Worker', 'محمد عاصف', 'فاست', '20427', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20435_فاست', 'Worker', 'ساحل', 'فاست', '20435', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20453_فاست', 'Worker', 'احشان الله', 'فاست', '20453', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20454_فاست', 'Worker', 'نور علام خان', 'فاست', '20454', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20459_فاست', 'Worker', 'شهيد علي', 'فاست', '20459', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20470_فاست', 'Worker', 'شهد احمد', 'فاست', '20470', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20473_فاست', 'Worker', 'راجان أحمد', 'فاست', '20473', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20474_فاست', 'Worker', 'الرحمن', 'فاست', '20474', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20476_فاست', 'Worker', 'محمد شاروخ خان', 'فاست', '20476', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20477_فاست', 'Worker', 'محمد عشمان', 'فاست', '20477', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20485_فاست', 'Worker', 'محمد افجال', 'فاست', '20485', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20489_فاست', 'Worker', 'محمد جولزار', 'فاست', '20489', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20492_فاست', 'Worker', 'فرمان', 'فاست', '20492', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20493_فاست', 'Worker', 'مو يوسف', 'فاست', '20493', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20494_فاست', 'Worker', 'محفوظ خان', 'فاست', '20494', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20495_فاست', 'Worker', 'خان يمين', 'فاست', '20495', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20500_فاست', 'Worker', 'سفيان خان', 'فاست', '20500', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20501_فاست', 'Worker', 'نصر الدين', 'فاست', '20501', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20519_الالمنيوم', 'Worker', 'منجور علي', 'الالمنيوم', '20519', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20521_فاست', 'Worker', 'دروغا عالم بهولا', 'فاست', '20521', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20523_فاست', 'Worker', 'فرخ شهزاد', 'فاست', '20523', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20526_فاست', 'Worker', 'بريم لال   كومل', 'فاست', '20526', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20537_فاست', 'Worker', 'شوكت حسين فضل داد', 'فاست', '20537', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20547_فاست', 'Worker', 'اسد الله سامي الله', 'فاست', '20547', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20558_فاست', 'Worker', 'شميل محمد وهاب دين', 'فاست', '20558', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20571_فاست', 'Worker', 'سيد جمال حسن', 'فاست', '20571', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20572_فاست', 'Worker', 'مالك شاه', 'فاست', '20572', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20573_فاست', 'Worker', 'زرد علي', 'فاست', '20573', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20576_فاست', 'Worker', 'سيد علي محب عاشر', 'فاست', '20576', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20579_فاست', 'Worker', 'رضا أحمد', 'فاست', '20579', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20580_فاست', 'Worker', 'زيغام سهيل', 'فاست', '20580', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20581_فاست', 'Worker', 'محمد آفاق مظهر', 'فاست', '20581', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20582_فاست', 'Worker', 'محمد أمير', 'فاست', '20582', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20583_فاست', 'Worker', 'ياسر خان', 'فاست', '20583', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20586_فاست', 'Worker', 'عثمان ياسين', 'فاست', '20586', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20587_فاست', 'Worker', 'امير حمزة', 'فاست', '20587', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20589_فاست', 'Worker', 'عبدالرحمن', 'فاست', '20589', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20590_فاست', 'Worker', 'عماد حسين', 'فاست', '20590', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20591_فاست', 'Worker', 'شير علي', 'فاست', '20591', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20592_فاست', 'Worker', 'شيراز خان', 'فاست', '20592', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20593_فاست', 'Worker', 'محمد شفيق', 'فاست', '20593', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20594_فاست', 'Worker', 'عبد الله', 'فاست', '20594', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20599_فاست', 'Worker', 'محمد شهباز', 'فاست', '20599', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20601_فاست', 'Worker', 'طلحة يونس', 'فاست', '20601', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20603_فاست', 'Worker', 'محمد ساجد', 'فاست', '20603', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20604_فاست', 'Worker', 'محمد كاشان', 'فاست', '20604', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20605_فاست', 'Worker', 'أسد خان', 'فاست', '20605', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20615_فاست', 'Worker', 'عزالدين عبدالجواد جابر عبدالجواد', 'فاست', '20615', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20619_فاست', 'Worker', 'بلال خات', 'فاست', '20619', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20633_فاست', 'Worker', 'عرفان حسين نور زمان', 'فاست', '20633', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20634_فاست', 'Worker', 'محمد برفيز', 'فاست', '20634', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20641_فاست', 'Worker', 'اسرار حسين', 'فاست', '20641', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20648_فاست', 'Worker', 'عمران اسلام  الدين', 'فاست', '20648', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20667_فاست', 'Worker', 'ايمن عبد العظيم حسين  سعد', 'فاست', '20667', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20669_فاست', 'Worker', 'عمر نجار بكري', 'فاست', '20669', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20686_فاست', 'Worker', 'شهزاد خان شير زمان', 'فاست', '20686', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20692_فاست', 'Worker', 'صفات الله مجيب  الله', 'فاست', '20692', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20693_فاست', 'Worker', 'راميش راديشبام', 'فاست', '20693', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20695_فاست', 'Worker', 'شاه نور خان نفيس', 'فاست', '20695', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20704_فاست', 'Worker', 'سوشيل كمار', 'فاست', '20704', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20705_فاست', 'Worker', 'انكيت كومر رام كريبال', 'فاست', '20705', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20706_فاست', 'Worker', 'محمد فضيل محمد زكري', 'فاست', '20706', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20712_فاست', 'Worker', 'صاحب علام توفيق احمد', 'فاست', '20712', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20730_فاست', 'Worker', 'فيصل غفار عبد الغفار', 'فاست', '20730', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20731_فاست', 'Worker', 'عبدالواحد زاهد  برفيز', 'فاست', '20731', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20741_فاست', 'Worker', 'واجد علي', 'فاست', '20741', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20746_فاست', 'Worker', 'نصر علي', 'فاست', '20746', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20750_فاست', 'Worker', 'محمد مصطفى اسماعيل احمد', 'فاست', '20750', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20761_فاست', 'Worker', 'محمد اصف امتياز', 'فاست', '20761', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20820_فاست', 'Worker', 'خالد محمود اشفاق محمود', 'فاست', '20820', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20825_فاست', 'Worker', 'عبد الرحمن', 'فاست', '20825', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20827_فاست', 'Worker', 'عاكف عزيز', 'فاست', '20827', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20830_فاست', 'Worker', 'ألطاف خان', 'فاست', '20830', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20836_فاست', 'Worker', 'خيبر خان', 'فاست', '20836', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20842_فاست', 'Worker', 'بنيامين', 'فاست', '20842', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20852_فاست', 'Worker', 'محمد بشارات', 'فاست', '20852', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20858_فاست', 'Worker', 'محمد شيراز', 'فاست', '20858', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20863_فاست', 'Worker', 'محمد إدريس', 'فاست', '20863', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20865_فاست', 'Worker', 'مزمل حسين', 'فاست', '20865', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20866_فاست', 'Worker', 'محمد حارس', 'فاست', '20866', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20867_فاست', 'Worker', 'عابد حسين', 'فاست', '20867', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20878_فاست', 'Worker', 'عادل احمد', 'فاست', '20878', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20885_فاست', 'Worker', 'أنيب محمود', 'فاست', '20885', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20886_فاست', 'Worker', 'احسان الله', 'فاست', '20886', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20888_فاست', 'Worker', 'محمد بلال', 'فاست', '20888', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20891_فاست', 'Worker', 'نافيد أحمد', 'فاست', '20891', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20892_فاست', 'Worker', 'ساجد علي', 'فاست', '20892', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20899_فاست', 'Worker', 'آصف علي', 'فاست', '20899', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20921_فاست', 'Worker', 'ملاك تاج', 'فاست', '20921', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20923_فاست', 'Worker', 'حماد علي', 'فاست', '20923', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20926_فاست', 'Worker', 'خان أفضل', 'فاست', '20926', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20927_فاست', 'Worker', 'أسد محمود', 'فاست', '20927', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20931_فاست', 'Worker', 'مو أرمان مينودين', 'فاست', '20931', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20944_فاست', 'Worker', 'أنيس أمين', 'فاست', '20944', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20946_فاست', 'Worker', 'سيد نواز', 'فاست', '20946', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20948_فاست', 'Worker', 'هاشم خان', 'فاست', '20948', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20958_فاست', 'Worker', 'حسن رضا', 'فاست', '20958', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20959_فاست', 'Worker', 'زين العابدين', 'فاست', '20959', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20967_فاست', 'Worker', 'محمد انس', 'فاست', '20967', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20969_فاست', 'Worker', 'سلمان خان', 'فاست', '20969', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20982_فاست', 'Worker', 'مالك تنوير', 'فاست', '20982', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20987_فاست', 'Worker', 'محمد عارف', 'فاست', '20987', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20988_فاست', 'Worker', 'باجال خان', 'فاست', '20988', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_20997_فاست', 'Worker', 'أبو سفيان', 'فاست', '20997', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21000_فاست', 'Worker', 'شابير احمد', 'فاست', '21000', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21009_فاست', 'Worker', 'عمران خادم خادم حسين', 'فاست', '21009', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21016_فاست', 'Worker', 'شعبان السيد محمد السيد', 'فاست', '21016', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21019_فاست', 'Worker', 'فايز الرحمن', 'فاست', '21019', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21020_فاست', 'Worker', 'فرحان أكبر', 'فاست', '21020', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21026_فاست', 'Worker', 'سياب خان', 'فاست', '21026', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21031_فاست', 'Worker', 'محمد رجا', 'فاست', '21031', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21034_فاست', 'Worker', 'سناء الله', 'فاست', '21034', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21036_فاست', 'Worker', 'كامران خان', 'فاست', '21036', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21046_فاست', 'Worker', 'نور حان ماهروف خان', 'فاست', '21046', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21106_فاست', 'Worker', 'محمد ارشد جمعه خان', 'فاست', '21106', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21119_فاست', 'Worker', 'محمد عادل محمد يوسف', 'فاست', '21119', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21145_فاست', 'Worker', 'محمد حمدى فياض عبدالبر', 'فاست', '21145', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21146_فاست', 'Worker', 'منير  احمد بشير', 'فاست', '21146', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21169_فاست', 'Worker', 'فضل سبحان  محمد الله', 'فاست', '21169', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21175_فاست', 'Worker', 'حيات محمد محمد شير', 'فاست', '21175', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21178_فاست', 'Worker', 'وحيد الله عامر بادشاه', 'فاست', '21178', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21191_فاست', 'Worker', 'محمد اشفاق عبد الله', 'فاست', '21191', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21196_فاست', 'Worker', 'نعيم شهزاد', 'فاست', '21196', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21208_فاست', 'Worker', 'انور دركت  خان', 'فاست', '21208', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21221_فاست', 'Worker', 'محمد بلال', 'فاست', '21221', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21229_فاست', 'Worker', 'شهزاد على محمد سالم', 'فاست', '21229', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21230_فاست', 'Worker', 'نفيد خان عبيد خان', 'فاست', '21230', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21235_فاست', 'Worker', 'اجهار الدين خان فهيم الدين خان', 'فاست', '21235', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21243_فاست', 'Worker', 'تاج محمد قيمت قل', 'فاست', '21243', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21244_فاست', 'Worker', 'احسان الهى غلام رسول', 'فاست', '21244', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21248_فاست', 'Worker', 'محمد علي محمدمراد', 'فاست', '21248', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21256_فاست', 'Worker', 'غلام مصطفى والى الرحمن', 'فاست', '21256', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21260_فاست', 'Worker', 'انيس جاويد', 'فاست', '21260', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21261_فاست', 'Worker', 'رانا عرفان محمود بشير احمد رانا', 'فاست', '21261', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21269_فاست', 'Worker', 'محمد حسيب صديقي محمد صديقي', 'فاست', '21269', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21275_فاست', 'Worker', 'عابد اد   محمد', 'فاست', '21275', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21281_فاست', 'Worker', 'زبران علاء مكتور', 'فاست', '21281', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21287_الالمنيوم', 'Worker', 'رحيم الدين نظام', 'الالمنيوم', '21287', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21301_فاست', 'Worker', 'وليد محمد عز الدين عبد النعيم', 'فاست', '21301', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21308_فاست', 'Worker', 'محمد جمال الدين السعيد', 'فاست', '21308', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21322_فاست', 'Worker', 'محمد عدنان أحمد خان', 'فاست', '21322', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21345_فاست', 'Worker', 'وقار أحمد نور محمد', 'فاست', '21345', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status, transfer_destination) VALUES ('w_emp_21387_فاست', 'Worker', 'ابراهيم نوبي احمد محمد', 'فاست', '21387', 'Egypt', '', 'Active', NULL);
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21404_فاست', 'Worker', 'مشتاق على حاجي ارشد على', 'فاست', '21404', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21408_فاست', 'Worker', 'عمار سينغ  بيروا', 'فاست', '21408', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21411_فاست', 'Worker', 'على رضا محمد سرور', 'فاست', '21411', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21412_فاست', 'Worker', 'شاداب خان منير احمد', 'فاست', '21412', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21449_فاست', 'Worker', 'عتيق الرحمن محمد لطيف', 'فاست', '21449', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21451_فاست', 'Worker', 'شير على شير محمد', 'فاست', '21451', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21459_فاست', 'Worker', 'شريف احمد عبد الخالق محمد', 'فاست', '21459', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21466_فاست', 'Worker', 'محمود مسعود محمود نصر', 'فاست', '21466', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21467_فاست', 'Worker', 'إبراهيم خليفة عبد المعتمد خليل', 'فاست', '21467', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21481_فاست', 'Worker', 'محمد لطفي عبدالرازق محمد', 'فاست', '21481', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21485_فاست', 'Worker', 'مصطفي شحاته حسين يوسف', 'فاست', '21485', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21492_فاست', 'Worker', 'محمود كارم بركات ابراهيم ركه', 'فاست', '21492', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21499_فاست', 'Worker', 'محمد فاروق راب نواز', 'فاست', '21499', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21500_فاست', 'Worker', 'عمران محمد إسماعيل', 'فاست', '21500', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21519_فاست', 'Worker', 'محمد إسماعيل جوهر علي', 'فاست', '21519', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21526_فاست', 'Worker', 'عمر محمود', 'فاست', '21526', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21557_فاست', 'Worker', 'جواد حسين', 'فاست', '21557', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21566_فاست', 'Worker', 'طالب حسين', 'فاست', '21566', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21568_فاست', 'Worker', 'ارمان خان', 'فاست', '21568', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21570_فاست', 'Worker', 'محمد سمير', 'فاست', '21570', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21571_فاست', 'Worker', 'سلمان علي', 'فاست', '21571', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21576_فاست', 'Worker', 'محمد محتسيم', 'فاست', '21576', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21587_فاست', 'Worker', 'محمد غفران', 'فاست', '21587', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21588_فاست', 'Worker', 'علاء الدين', 'فاست', '21588', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21595_فاست', 'Worker', 'توقير اختر اختر حسين', 'فاست', '21595', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21599_فاست', 'Worker', 'صبولر احمد محمد رصاف', 'فاست', '21599', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21602_فاست', 'Worker', 'ديل تاج بب', 'فاست', '21602', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21603_فاست', 'Worker', 'مينا سفير سفير حسين', 'فاست', '21603', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21607_فاست', 'Worker', 'محمد عاقب', 'فاست', '21607', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21610_فاست', 'Worker', 'سوجات حسين', 'فاست', '21610', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21611_فاست', 'Worker', 'محمد ساجد', 'فاست', '21611', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21616_فاست', 'Worker', 'طارق خان محمد الياس', 'فاست', '21616', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21628_فاست', 'Worker', 'زار والي معلم', 'فاست', '21628', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21630_فاست', 'Worker', 'رحيل عباس محمد عباس', 'فاست', '21630', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21638_فاست', 'Worker', 'عنصر نثار نثار احمد', 'فاست', '21638', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21671_فاست', 'Worker', 'محمد جهانجير محمد يوسف', 'فاست', '21671', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21740_فاست', 'Worker', 'اشرف محمد عبدالحميد محمد', 'فاست', '21740', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21741_فاست', 'Worker', 'اشرف محمد عبدالحميد محمد', 'فاست', '21741', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21748_فاست', 'Worker', 'محمد حمدي شحاته', 'فاست', '21748', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21753_فاست', 'Worker', 'عمر عبدالعزيز محمد', 'فاست', '21753', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21812_فاست', 'Worker', 'سمير عبدالله احمد محمد الوصابى', 'فاست', '21812', 'Yemen', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21824_فاست', 'Worker', 'ابوبكر صلاح حلمى محمد', 'فاست', '21824', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_21870_فاست', 'Worker', 'احمد ابراهيم عفيفى احمد', 'فاست', '21870', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_22092_الالمنيوم', 'Worker', 'احمد اوزير', 'الالمنيوم', '22092', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_22206_الالمنيوم', 'Worker', 'احمد صلاح  حسن', 'الالمنيوم', '22206', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_22402_الالمنيوم', 'Worker', 'محمد صابر خان', 'الالمنيوم', '22402', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_22443_الالمنيوم', 'Worker', 'سهيل محمد', 'الالمنيوم', '22443', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2341468144_عمالة_يومية_(ساكوديكو)', 'Worker', 'علي محمد محمد', 'عمالة يومية (ساكوديكو)', '2341468144', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2413179322_فاست', 'Worker', 'عبدالرؤوف محمد عبدالرؤوف', 'فاست', '2413179322', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2414324448_عمالة_يومية_(ساكوديكو)', 'Worker', 'محمد عبد الرحمن عباس', 'عمالة يومية (ساكوديكو)', '2414324448', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2428244020_فاست', 'Worker', 'محمد سول', 'فاست', '2428244020', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2463458683_فاست', 'Worker', 'محمد شاهين مياه', 'فاست', '2463458683', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2468770678_عمالة_يومية_(ساكوديكو)', 'Worker', 'إبراهيم عبد الصمد', 'عمالة يومية (ساكوديكو)', '2468770678', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2482569395_عمالة_يومية_(ساكوديكو)', 'Worker', 'فتحي المرسي عبد الخالق المرسي', 'عمالة يومية (ساكوديكو)', '2482569395', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2493312504_شركة_البدر', 'Worker', 'عارف  ميا', 'شركة البدر', '2493312504', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2502405141_فاست', 'Worker', 'سيبان ايجو مياه', 'فاست', '2502405141', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2502752930_فاست', 'Worker', 'مقصود احمد محرام على', 'فاست', '2502752930', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2506800602_شركة_البدر', 'Worker', 'محمد منير ال اسلام', 'شركة البدر', '2506800602', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2509632531_فاست', 'Worker', 'بلال احمد بهويان', 'فاست', '2509632531', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2511930410_شركة_البدر', 'Worker', 'مد أكرم علي', 'شركة البدر', '2511930410', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2513183810_عمالة_يومية_(ساكوديكو)', 'Worker', 'احمد ابراهيم الشحات محمد', 'عمالة يومية (ساكوديكو)', '2513183810', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2513449138_فاست', 'Worker', 'بيرناس داس', 'فاست', '2513449138', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2515911598_شركة_البدر', 'Worker', 'شير علم خان خريمي', 'شركة البدر', '2515911598', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2516080336_فاست', 'Worker', 'محمد كريم وزير خان', 'فاست', '2516080336', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2519420398_عمالة_يومية_(ساكوديكو)', 'Worker', 'اسلام السيد محمد قهوه', 'عمالة يومية (ساكوديكو)', '2519420398', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2520571809_شركة_البدر', 'Worker', 'محمد أنيس لبرحمن', 'شركة البدر', '2520571809', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2520583143_عمالة_يومية_(ساكوديكو)', 'Worker', 'امين علي احمد الجبالي', 'عمالة يومية (ساكوديكو)', '2520583143', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2521004891_فاست', 'Worker', 'برهان خان قيصر', 'فاست', '2521004891', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2522711627_عمالة_يومية_(ساكوديكو)', 'Worker', 'محمد مضحك مصطفي أبو شريف', 'عمالة يومية (ساكوديكو)', '2522711627', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2522809199_عمالة_يومية_(ساكوديكو)', 'Worker', 'وجيه محب عبد العظيم حبيب', 'عمالة يومية (ساكوديكو)', '2522809199', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2523173744_شركة_البدر', 'Worker', 'شفيق ال اسلام هيمال', 'شركة البدر', '2523173744', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2524731565_فاست', 'Worker', 'طاهر علام', 'فاست', '2524731565', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2530911789_عمالة_يومية_(ساكوديكو)', 'Worker', 'عمر عبد الله صالح محمد', 'عمالة يومية (ساكوديكو)', '2530911789', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2532841018_عمالة_يومية_(ساكوديكو)', 'Worker', 'إبراهيم عاطف', 'عمالة يومية (ساكوديكو)', '2532841018', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2534648544_فاست', 'Worker', 'محمد امتياز محمد نواز', 'فاست', '2534648544', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2536423300_عمالة_يومية_(ساكوديكو)', 'Worker', 'علي فوزي السيد سلامة', 'عمالة يومية (ساكوديكو)', '2536423300', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_25401_الالمنيوم', 'Worker', 'وقاص خان علي رياض', 'الالمنيوم', '25401', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2546562857_عمالة_يومية_(ساكوديكو)', 'Worker', 'محمود عاطف محمد فرح', 'عمالة يومية (ساكوديكو)', '2546562857', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2552477123_فاست', 'Worker', 'مد عبد ال الغفار مافاج', 'فاست', '2552477123', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2555944418_فاست', 'Worker', 'رحمن الله اصغر خان', 'فاست', '2555944418', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2556029532_فاست', 'Worker', 'محمد سعيد مظهر اقبال', 'فاست', '2556029532', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2562435335_شركة_البدر', 'Worker', 'مد ظهير  إسلام', 'شركة البدر', '2562435335', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2570137931_فاست', 'Worker', 'محمد ياكوب محرام على', 'فاست', '2570137931', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2597325378_فاست', 'Worker', 'عثمان قادر غلام قادر', 'فاست', '2597325378', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2597836853_شركة_البدر', 'Worker', 'مد سانو ججمان', 'شركة البدر', '2597836853', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2598751176_فاست', 'Worker', 'منير ارسين', 'فاست', '2598751176', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2600333419_عمالة_يومية_(ساكوديكو)', 'Worker', 'حسن علي احمد الجبالى', 'عمالة يومية (ساكوديكو)', '2600333419', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2602624377_فاست', 'Worker', 'محمد سراج بويان', 'فاست', '2602624377', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2605784822_فاست', 'Worker', 'اسد الرحمن حاجى محمد', 'فاست', '2605784822', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2606340509_شركة_البدر', 'Worker', 'مد شكيل اوسين', 'شركة البدر', '2606340509', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2610931558_فاست', 'Worker', 'منير احمد كالا خان', 'فاست', '2610931558', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616850307_شركة_البدر', 'Worker', 'مد شوجن علي', 'شركة البدر', '2616850307', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616850331_شركة_البدر', 'Worker', 'محمد رونجان ميا', 'شركة البدر', '2616850331', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616853129_شركة_البدر', 'Worker', 'مد خير', 'شركة البدر', '2616853129', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616863854_شركة_البدر', 'Worker', 'محمد سون شكيدر', 'شركة البدر', '2616863854', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616867186_شركة_البدر', 'Worker', 'محمدروبين ميا', 'شركة البدر', '2616867186', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616867889_شركة_البدر', 'Worker', 'اكلاس اوسين', 'شركة البدر', '2616867889', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_2616867970_شركة_البدر', 'Worker', 'محمد  افير رحمن', 'شركة البدر', '2616867970', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_3030085_ABCD-انشاء_المباني', 'Worker', 'محمد الياس متولي', 'ABCD-انشاء المباني', '3030085', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_3036609_ABCD-جامعه_و_حرس', 'Worker', 'متعب جراد الغامدي', 'ABCD-جامعه و حرس', '3036609', 'Saudi', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_3040447_ABCD-انشاء_المباني', 'Worker', 'عبدالمجيد عبدالعزيز', 'ABCD-انشاء المباني', '3040447', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_3043722_ABCD-جامعه_و_حرس', 'Worker', 'نسيم احمد محي الدين', 'ABCD-جامعه و حرس', '3043722', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_315411_فاست', 'Worker', 'فيصل مقصود', 'فاست', '315411', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_36270_فاست', 'Worker', 'محمد رياض محمد صادق', 'فاست', '36270', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_36895_فاست', 'Worker', 'رمضان فوزى', 'فاست', '36895', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_37986_فاست', 'Worker', 'احمد عيد إبراهيم شحاته', 'فاست', '37986', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_4035495_ABCD-جامعه_و_حرس', 'Worker', 'ساجد ناصر ب بيساياتي', 'ABCD-جامعه و حرس', '4035495', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_4039536_ABCD-جامعه_و_حرس', 'Worker', 'بيرت مندل  مراري', 'ABCD-جامعه و حرس', '4039536', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_4039833_ABCD-جامعه_و_حرس', 'Worker', 'راجيش شرما بثبات ذاكر', 'ABCD-جامعه و حرس', '4039833', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_45905_SACODECO', 'Supervisor', 'Qamrulhasan Khan', 'SACODECO', '45905', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_48828_SACODECO', 'Supervisor', 'NAZIR HUSSAIN MUHAMMAD IRSHAD', 'SACODECO', '48828', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_48838_SACODECO', 'Worker', 'VASIM AHMAD', 'SACODECO', '48838', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49116_SACODECO', 'Worker', 'JUNAID PAPPU KHAN', 'SACODECO', '49116', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49120_SACODECO', 'Worker', 'MOHAMMAD TALIIB', 'SACODECO', '49120', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49137_SACODECO', 'Worker', 'MOHAMMAD MOHSIN', 'SACODECO', '49137', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49144_SACODECO', 'Worker', 'FAISAL SHAKEEL', 'SACODECO', '49144', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49172_SACODECO', 'Worker', 'MOHAMMAD ARBAZ', 'SACODECO', '49172', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49187_SACODECO', 'Worker', 'SHAHRUKH KHAN', 'SACODECO', '49187', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49191_SACODECO', 'Worker', 'SALMAN KHAN', 'SACODECO', '49191', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49192_SACODECO', 'Worker', 'MOHD ANAS', 'SACODECO', '49192', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49193_SACODECO', 'Worker', 'ABDULLA MUSLIM PATHAN', 'SACODECO', '49193', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49194_SACODECO', 'Worker', 'MOHD UMER', 'SACODECO', '49194', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49195_SACODECO', 'Worker', 'MOHD WAZID SHAIKH', 'SACODECO', '49195', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49202_SACODECO', 'Worker', 'ABUZAR JAHIR ALAM', 'SACODECO', '49202', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49214_SACODECO', 'Worker', 'HAMZA SHAHID SHAHID HUSSAIN', 'SACODECO', '49214', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49215_SACODECO', 'Worker', 'ALI RAZA NASIR ALI', 'SACODECO', '49215', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49217_SACODECO', 'Worker', 'AHSAN SHAHID SHAHID HUSSAIN', 'SACODECO', '49217', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49225_SACODECO', 'Worker', 'MD NAUSHAD', 'SACODECO', '49225', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49233_SACODECO', 'Worker', 'MOHD AYAN', 'SACODECO', '49233', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49238_SACODECO', 'Worker', 'NADEEM AHMAD', 'SACODECO', '49238', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49244_SACODECO', 'Worker', 'AKRAM ANSARI', 'SACODECO', '49244', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49245_SACODECO', 'Worker', 'MOHD IMTIYAJ', 'SACODECO', '49245', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49247_SACODECO', 'Supervisor', 'FAISAL ALI', 'SACODECO', '49247', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49256_SACODECO', 'Worker', 'MEER HAMZA MUHAMMAD TAYYAB', 'SACODECO', '49256', 'Palestine', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49270_SACODECO', 'Worker', 'MOHSIN AHMAD MEWA TAB', 'SACODECO', '49270', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49302_SACODECO', 'Worker', 'MUHAMMAD ASIF ALI TAHIR REHMAT ALI', 'SACODECO', '49302', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49306_SACODECO', 'Worker', 'NAUMAN KHAN TAIMOOR KHAN', 'SACODECO', '49306', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49307_SACODECO', 'Worker', 'WASIM SAJJAD RAHIM', 'SACODECO', '49307', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49314_SACODECO', 'Worker', 'WAQAR YOUNAS TAJ MUHAMMAD', 'SACODECO', '49314', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49338_SACODECO', 'Worker', 'MUHAMMAD AQIB MUHAMMAD RASHEED', 'SACODECO', '49338', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49341_SACODECO', 'Worker', 'MUHAMMAD ANEES KALA KHAN', 'SACODECO', '49341', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49347_SACODECO', 'Worker', 'MUHAMMAD IRFAN ROOHUL ZAMIR', 'SACODECO', '49347', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_49381_SACODECO', 'Worker', 'MUHAMMAD SHAHID MUHAMMAD JAVED', 'SACODECO', '49381', 'Pakistan', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49382_SACODECO', 'Worker', 'RIZWAN AKHTAR AKHTAR ZAMAN', 'SACODECO', '49382', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49389_SACODECO', 'Worker', 'ABDUL RABI GUL ZAMEER', 'SACODECO', '49389', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49394_SACODECO', 'Worker', 'ABDULLAH SIRAJ UL HAQ', 'SACODECO', '49394', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49399_SACODECO', 'Worker', 'MUHAMMAD FAIZAN MIAN RAMZAN', 'SACODECO', '49399', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49400_SACODECO', 'Worker', 'FAHEEM ULLAH SAFI ULLAH', 'SACODECO', '49400', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49409_SACODECO', 'Worker', 'MUHAMMAD JAN SAIDA JAN', 'SACODECO', '49409', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49438_SACODECO', 'Worker', 'SHAMASHAD MAKASOOD', 'SACODECO', '49438', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49440_SACODECO', 'Worker', 'MUHMMAD VAHID', 'SACODECO', '49440', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49443_SACODECO', 'Worker', 'MERAJ MUNSAD', 'SACODECO', '49443', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49452_SACODECO', 'Worker', 'INAM UL HAQ MUHAMMAD HANIF', 'SACODECO', '49452', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49454_SACODECO', 'Worker', 'HUZZAIFA SAJID SAJID HUSSAIN', 'SACODECO', '49454', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49461_SACODECO', 'Worker', 'NIZAMUDDIN CHIDDA HUSSAIN', 'SACODECO', '49461', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49462_SACODECO', 'Worker', 'MURSALEEN INSAF ALI', 'SACODECO', '49462', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, transfer_destination, status) VALUES ('w_emp_49463_SACODECO', 'Worker', 'MOHAMMAD SAMIULLAH', 'SACODECO', '49463', 'Indian', '', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49468_SACODECO', 'Worker', 'MO KAIF', 'SACODECO', '49468', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49490_SACODECO', 'Worker', 'RABBANEE MO JAMIL', 'SACODECO', '49490', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49491_SACODECO', 'Worker', 'SALMAN KHAN', 'SACODECO', '49491', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49498_SACODECO', 'Worker', 'MOHAMMED MUBARIK', 'SACODECO', '49498', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49499_SACODECO', 'Worker', 'MOHD ASHWAD', 'SACODECO', '49499', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49501_SACODECO', 'Worker', 'RAHMAN MAHBUB KHAN', 'SACODECO', '49501', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49502_SACODECO', 'Worker', 'MOHAMMED IMRAN', 'SACODECO', '49502', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49504_SACODECO', 'Worker', 'AMEER ALI', 'SACODECO', '49504', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49509_SACODECO', 'Supervisor', 'SAHIL HUSAIN', 'SACODECO', '49509', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49515_SACODECO', 'Worker', 'MOHD ALTAF', 'SACODECO', '49515', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49519_SACODECO', 'Worker', 'IJAZ AHMAD MUHAMMAD SULEMAN', 'SACODECO', '49519', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49522_SACODECO', 'Worker', 'UMAR QAYYUM ABDUL QAYYUM', 'SACODECO', '49522', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49536_SACODECO', 'Worker', 'SHAHZAD NAZIR NAZIR AHMAD', 'SACODECO', '49536', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49546_SACODECO', 'Worker', 'REHAN KHAN', 'SACODECO', '49546', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49547_SACODECO', 'Worker', 'IMRAN ISLAMUDDIN', 'SACODECO', '49547', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49674_SACODECO', 'Worker', 'FURKAN AJAMAT ALI', 'SACODECO', '49674', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49676_SACODECO', 'Worker', 'MUHAMMAD HILAL NAWAZ KHAN', 'SACODECO', '49676', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49678_SACODECO', 'Worker', 'MUHAMMAD WASEEM KHAN MUHAMMAD NAVEED KHAN', 'SACODECO', '49678', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49682_SACODECO', 'Worker', 'AHMAD BILAL GUL DAD KHAN', 'SACODECO', '49682', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49683_SACODECO', 'Worker', 'BILAL IBRAHIM MUHAMMAD IBRAHIM', 'SACODECO', '49683', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49684_SACODECO', 'Worker', 'MUHAMMAD ZUBAIR SABEEL KHAN', 'SACODECO', '49684', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49694_SACODECO', 'Worker', 'MUHAMMAD RASHID KHUDA BUKHSH', 'SACODECO', '49694', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49697_SACODECO', 'Worker', 'ABID SALEEM KHAN', 'SACODECO', '49697', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49698_SACODECO', 'Worker', 'KAMRAN HUSSAIN SAJID KHAN', 'SACODECO', '49698', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49701_SACODECO', 'Worker', 'MUHAMMAD ALI MUHAMMAD RIAZ', 'SACODECO', '49701', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49702_SACODECO', 'Worker', 'CHANGAIZ KHAN ALLAH DAD', 'SACODECO', '49702', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49711_SACODECO', 'Worker', 'MO MOHD FARUKH DANISH', 'SACODECO', '49711', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49713_SACODECO', 'Worker', 'SARFRAZ UDDIN', 'SACODECO', '49713', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49715_SACODECO', 'Worker', 'NOMAN ZULFIQAR ZULFIQAR ALI', 'SACODECO', '49715', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49717_SACODECO', 'Worker', 'MUHAMMAD NAVEED MUHAMMAD BASHIR', 'SACODECO', '49717', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49719_SACODECO', 'Worker', 'MEHRAN KHAN GUL DARAZ KHAN', 'SACODECO', '49719', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49721_SACODECO', 'Worker', 'MUHAMMAD SHAHID MUHAMMAD AKRAM', 'SACODECO', '49721', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49722_SACODECO', 'Worker', 'SHAH SAUD WAKEEL KHAN', 'SACODECO', '49722', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49727_SACODECO', 'Worker', 'MANZOOR KHAN AZAM KHAN', 'SACODECO', '49727', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49829_SACODECO', 'Worker', 'KASHIF ARSALAN FAQIR HUSSAIN', 'SACODECO', '49829', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49832_SACODECO', 'Worker', 'MUHAMMAD DANISH MAHRAB KHAN', 'SACODECO', '49832', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_49856_SACODECO', 'Worker', 'MOHAMMAD FAIZAN', 'SACODECO', '49856', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50193_SACODECO', 'Worker', 'HAMMAD ALI ABDUL WAJIB', 'SACODECO', '50193', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50194_SACODECO', 'Worker', 'ILTAF HUSSAIN SADIQ MUHAMMAD', 'SACODECO', '50194', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50195_SACODECO', 'Worker', 'NAEEM ASHRAF MUHAMMAD ASHRAF', 'SACODECO', '50195', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50200_SACODECO', 'Worker', 'GHULAM MUSTAFA MUHAMMAD ASLAM', 'SACODECO', '50200', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50201_SACODECO', 'Worker', 'BAHAR ALI ROGHAN GUL', 'SACODECO', '50201', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50202_SACODECO', 'Worker', 'ZOHAIB ALI MANZOOR HUSSAIN', 'SACODECO', '50202', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50206_SACODECO', 'Worker', 'RIAZ HUSSAIN GUL HUSSAIN', 'SACODECO', '50206', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50209_SACODECO', 'Worker', 'MUBARIK MOHAMMAD ILIYAS BISAYATI', 'SACODECO', '50209', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50215_SACODECO', 'Worker', 'AJMAL BISAYTI MOHAMMED TAZMAL', 'SACODECO', '50215', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50217_SACODECO', 'Worker', 'SOHAIL QURESHI ARFAN QURESHI', 'SACODECO', '50217', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50218_SACODECO', 'Worker', 'MO HASAN ABDUL HANAN', 'SACODECO', '50218', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50220_SACODECO', 'Worker', 'ASIF BISAYATI MOHAMMED ZAKIR', 'SACODECO', '50220', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50221_SACODECO', 'Worker', 'MOHAMMED JAKIR ABDUL BAHID', 'SACODECO', '50221', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50223_SACODECO', 'Worker', 'ADIL MO MUSTAK', 'SACODECO', '50223', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50224_SACODECO', 'Worker', 'MOHAMMED SOHIL MUSTAAK AHAMED', 'SACODECO', '50224', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50226_SACODECO', 'Worker', 'AADIL BHATI HARUN BHATI', 'SACODECO', '50226', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50227_SACODECO', 'Worker', 'AKHTAR RJA MOHAMMED ALI', 'SACODECO', '50227', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50228_SACODECO', 'Worker', 'MOHAMMAD AFRIDI MOHAMMAD CHAND', 'SACODECO', '50228', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50229_SACODECO', 'Worker', 'MOHAMMED ASLAM MUNEER DEEN KHAN', 'SACODECO', '50229', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50231_SACODECO', 'Worker', 'MOHAMMAD SHAKIL SABIR', 'SACODECO', '50231', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_50238_SACODECO', 'Worker', 'WAHID MUHAMMAD HANIF', 'SACODECO', '50238', 'Pakistan', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50344_SACODECO', 'Worker', 'AHMED MOHAMED ABDELAATI AHMED', 'SACODECO', '50344', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50350_SACODECO', 'Worker', 'AHMED IBRAHIM MOHAMED HASSAN', 'SACODECO', '50350', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50363_SACODECO', 'Worker', 'MOHAMED ELSAYED ELARABI MOHAMED ELMORSI', 'SACODECO', '50363', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50465_SACODECO', 'Worker', 'ABDALLA IBRAHIM REZK REZK HELWA', 'SACODECO', '50465', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50470_SACODECO', 'Worker', 'ABDELSHAFI MOHAMED KHALAF MOURSI', 'SACODECO', '50470', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50564_SACODECO', 'Worker', 'MOSIM SABUDEEN', 'SACODECO', '50564', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50567_SACODECO', 'Worker', 'QUTUBUDDIN MAHABUB', 'SACODECO', '50567', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50568_SACODECO', 'Worker', 'NIJAMUDDEEN MAGAN', 'SACODECO', '50568', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50569_SACODECO', 'Worker', 'PARVEZ AALAM MOHAMMED IDREES KHILJI', 'SACODECO', '50569', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50578_SACODECO', 'Worker', 'MAHFUJ AHMAD KAYUM AHMAD', 'SACODECO', '50578', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50580_SACODECO', 'Worker', 'MOHAMMED SHARIF HAKAM ALI KHAN', 'SACODECO', '50580', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50582_SACODECO', 'Worker', 'SARFRAJ KHAN HASMAT KHAN', 'SACODECO', '50582', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50588_SACODECO', 'Worker', 'FAISAL RAIS AHMED', 'SACODECO', '50588', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50604_SACODECO', 'Worker', 'MD HASIM MD NAIM', 'SACODECO', '50604', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50609_SACODECO', 'Worker', 'MOHD RAYYAN AHMAD ALI', 'SACODECO', '50609', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50612_SACODECO', 'Worker', 'MUHAMMAD RAMZAN RAB NAWAZ', 'SACODECO', '50612', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50613_SACODECO', 'Worker', 'SAMI ULLAH MUHAMMAD TARIQ', 'SACODECO', '50613', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50617_SACODECO', 'Worker', 'ZABIT JALAL GUL JALAL', 'SACODECO', '50617', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50630_SACODECO', 'Worker', 'ALI RAHMAT KHAN HAJI AKBAR KHAN', 'SACODECO', '50630', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50634_SACODECO', 'Worker', 'MUHAMMAD JABAR ABDUL RAHEEM', 'SACODECO', '50634', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50636_SACODECO', 'Worker', 'HAMID SHAHZAD MUSHTAQ AHMED', 'SACODECO', '50636', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50639_SACODECO', 'Worker', 'HAMZA JAVED MOHAMMAD JAVED', 'SACODECO', '50639', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50642_SACODECO', 'Worker', 'MUHAMMAD AHSAN QURBAN ALI', 'SACODECO', '50642', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50643_SACODECO', 'Worker', 'ABDUL GHAFOOR MALIK GHULAM MURTAZA', 'SACODECO', '50643', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50644_SACODECO', 'Worker', 'MUHAMMAD NOMAN MUHAMMAD BASHIR', 'SACODECO', '50644', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50645_SACODECO', 'Worker', 'ALI RAZA MUHAMMAD HANIF', 'SACODECO', '50645', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50646_SACODECO', 'Worker', 'MUHAMMAD KASHIF SHOUKAT ALI', 'SACODECO', '50646', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50647_SACODECO', 'Worker', 'MUHAMMAD FAISAL BASHARAT ALI', 'SACODECO', '50647', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50648_SACODECO', 'Worker', 'MUBASHAR HASSAN MUHAMMAD SAEED KHAN', 'SACODECO', '50648', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50649_SACODECO', 'Worker', 'MUHAMMAD NAEEM FALAK SHER', 'SACODECO', '50649', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50651_SACODECO', 'Worker', 'MUHAMMAD FAHEEM QASIM ALI', 'SACODECO', '50651', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50652_SACODECO', 'Worker', 'IMRAN ALI FALAK SHER', 'SACODECO', '50652', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50653_SACODECO', 'Worker', 'MUHAMMAD ASHRAF GHULAM NABI', 'SACODECO', '50653', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50655_SACODECO', 'Worker', 'SHAZAD HUSSAIN MAHABUB ALI', 'SACODECO', '50655', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50656_SACODECO', 'Worker', 'MAAZ KHAN JUBAIR KHAN', 'SACODECO', '50656', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50657_SACODECO', 'Worker', 'MOH KALAAM SAMSUDDIN', 'SACODECO', '50657', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50658_SACODECO', 'Worker', 'MOHAMMAD HASAN KHAN', 'SACODECO', '50658', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50659_SACODECO', 'Worker', 'TAUFEEK JUNED', 'SACODECO', '50659', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50661_SACODECO', 'Worker', 'IMRAN HARUN SHEKH', 'SACODECO', '50661', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50664_SACODECO', 'Worker', 'ELSAYED AYMAN HIJAB MAHMOUD HIJAB', 'SACODECO', '50664', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50665_SACODECO', 'Worker', 'SOBHY KHALAF SHAWKY MABAD', 'SACODECO', '50665', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50666_SACODECO', 'Worker', 'MOHAMED ABDALLA ELHUSSEINI IBRAHIM', 'SACODECO', '50666', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50667_SACODECO', 'Worker', 'KHALED ASHRAF ABOUELMAGD ABOUELHAMD', 'SACODECO', '50667', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50668_SACODECO', 'Worker', 'SALAH ALI SALAH ABDELGALIL', 'SACODECO', '50668', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50716_SACODECO', 'Worker', 'TAUSEEF HAIDER ANWAR PERVAIZ', 'SACODECO', '50716', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50726_SACODECO', 'Worker', 'SHAHRYAR ABDUL SATTAR', 'SACODECO', '50726', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50732_SACODECO', 'Worker', 'USAMA KHAN RABNAWAZ', 'SACODECO', '50732', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50737_SACODECO', 'Worker', 'SULAIMAN KHAN MUHAMMAD FARAZ', 'SACODECO', '50737', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50738_SACODECO', 'Worker', 'ADIL SHAH GUL WALI SHAH', 'SACODECO', '50738', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50739_SACODECO', 'Worker', 'TALHA NADEEM MUHAMMAD ISHAQ', 'SACODECO', '50739', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50749_SACODECO', 'Worker', 'MUHAMMAD IMRAN BASHIR AHMAD', 'SACODECO', '50749', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50750_SACODECO', 'Worker', 'KHURSHED ALAM FAZAL HABIB', 'SACODECO', '50750', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50789_SACODECO', 'Worker', 'ANEES HAMEED', 'SACODECO', '50789', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50809_SACODECO', 'Worker', 'MUHAMMAD UMAIR FIDA MUHAMMAD', 'SACODECO', '50809', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50810_SACODECO', 'Worker', 'ARMAN HAYAT UMAR HAYAT KHAN', 'SACODECO', '50810', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50876_SACODECO', 'Worker', 'EZZAT ABDELNAGAH MAHMOUD RABIA', 'SACODECO', '50876', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50877_SACODECO', 'Supervisor', 'AHMED ABDELHADI MOHAMED SOLIMAN', 'SACODECO', '50877', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50886_SACODECO', 'Worker', 'ASEM ISMAEIL MOHAMED ELKHALIFA', 'SACODECO', '50886', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50888_SACODECO', 'Worker', 'MOHAMMAD AMIR MOHAMMAD IDREESH', 'SACODECO', '50888', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50890_SACODECO', 'Worker', 'GUL HASSAN KHAN', 'SACODECO', '50890', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50892_SACODECO', 'Worker', 'JAVED AKHTAR MOHAMMAD HAMID', 'SACODECO', '50892', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50893_SACODECO', 'Worker', 'MOHD IRFAN MOHD JAAN', 'SACODECO', '50893', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50895_SACODECO', 'Worker', 'SHAVEZ MATLOOB AHMAD', 'SACODECO', '50895', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50896_SACODECO', 'Worker', 'DANISH MUNASIB', 'SACODECO', '50896', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50897_SACODECO', 'Worker', 'MEHRAN IMRAN AHMAD', 'SACODECO', '50897', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50898_SACODECO', 'Worker', 'ASHU AKHTAR', 'SACODECO', '50898', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50899_SACODECO', 'Worker', 'MOHAMMAD ARHAM NISAR AHMAD', 'SACODECO', '50899', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50901_SACODECO', 'Worker', 'MOHD YUNUS MAKSUD', 'SACODECO', '50901', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50903_SACODECO', 'Worker', 'MOHAMMAD RIZWAN MOHAMMAD NASEEM', 'SACODECO', '50903', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50904_SACODECO', 'Worker', 'MOHAMMAD ASID MOHAMMAD ASIF', 'SACODECO', '50904', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50905_SACODECO', 'Worker', 'MOHD ANAS MOHD YAMEEN', 'SACODECO', '50905', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50907_SACODECO', 'Worker', 'MO ARMAN MO RASHID', 'SACODECO', '50907', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50908_SACODECO', 'Worker', 'MOHD ARWAZ RAIS MIYAN', 'SACODECO', '50908', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50909_SACODECO', 'Worker', 'MOHD TAHIR GULAM MOHAMMAD', 'SACODECO', '50909', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50910_SACODECO', 'Worker', 'SAMEER AHMAD AQEEL AHMAD', 'SACODECO', '50910', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50938_SACODECO', 'Worker', 'MOHAMMAD ALIM KALIMUDDIN', 'SACODECO', '50938', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50942_SACODECO', 'Worker', 'TOUSEEF AHMED MUHAMMAD TANVEER AHMED', 'SACODECO', '50942', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50943_SACODECO', 'Worker', 'NABEEL MUHAMMAD AMJAD', 'SACODECO', '50943', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50944_SACODECO', 'Worker', 'RAHMAN ULLAH BAHADAR SHER', 'SACODECO', '50944', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50945_SACODECO', 'Worker', 'SANA ULLAH HASHAM KHAN', 'SACODECO', '50945', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50946_SACODECO', 'Worker', 'WAJID KHAN AMEER KHAN', 'SACODECO', '50946', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50957_SACODECO', 'Worker', 'MUHAMMAD AWAIS NOOR HUSSAIN', 'SACODECO', '50957', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50958_SACODECO', 'Worker', 'MUHAMMAD ABBAS GUL ZAMIN', 'SACODECO', '50958', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50996_SACODECO', 'Worker', 'MOHD KAIF ISTIYAQ', 'SACODECO', '50996', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50998_SACODECO', 'Worker', 'MOHD KHAWAJA BABAU', 'SACODECO', '50998', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_50999_SACODECO', 'Worker', 'ABDUL KADIR MOHD AFJAL', 'SACODECO', '50999', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51000_SACODECO', 'Worker', 'KUTBUDDIN BUDH KHAN', 'SACODECO', '51000', 'Indian', '');
