INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('3ZWapiGXdib9BkBNWYIeI6pbU012', '2025-08-23T12:55:27.000Z', 'Khaled Harharah', '{"mode":"system","colorTheme":"blue"}', 'bahra-housing@sacodeco.net', 'Supervisor', '["4znleAk6l3E1eb1kAEXK","SMTiuEOKEPoBpAzxEikd"]');
INSERT OR REPLACE INTO users (id, created_at, role, name, assigned_residences, theme_settings, email) VALUES ('8yyq6oLzTQYPlOpTV7wN2pg2ZjS2', '2025-12-05T21:25:41.000Z', 'Technician', 'Hassan', '[]', '{"mode":"system","colorTheme":"blue"}', 'abdali_m2@hotmail.com');
INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('AdrLC5D071NNxictgJIiuNJkdcj2', '2025-11-13T07:58:12.000Z', 'Mohammed Mahmoud', '{"mode":"system","colorTheme":"blue"}', 'redsea-housing@sacodeco.net', 'Supervisor', '["3C1ZgRS2sr2VFMYGdzIN"]');
INSERT OR REPLACE INTO users (id, created_at, name, email, role, assigned_residences, theme_settings) VALUES ('TZn8ztXP0OdZajNILsFYEbdog8x1', '2025-08-23T12:59:20.000Z', 'test', 'test@test.com', 'Supervisor', '["DkivDvDBirmX4HIHU3cW"]', '{"colorTheme":"blue","mode":"dark"}');
INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('YcgFNB8NHZg8qo82VAfhhSIMv1h1', '2025-11-12T08:26:20.000Z', 'Haitham Zen', '{"mode":"system","colorTheme":"blue"}', 'umluj-housing@sacodeco.net', 'Supervisor', '["3C1ZgRS2sr2VFMYGdzIN"]');
INSERT OR REPLACE INTO users (id, created_at, role, name, email, assigned_residences, theme_settings) VALUES ('bRpKwXMuelYjNgGOqpEm55PvPTP2', '2025-08-11T06:19:55.000Z', 'Admin', 'Mohammed Alabdali', 'm.alabdali@sacodeco.net', '["6w8r1vh1h8xjpOsVULV5","KA43UwlETuLC7bWffony","L3wLRKW34H2dM2tQaBfI","gpKfg1LK8UBxPIhHiuPa","rMRf9xOfBZqUw8GKPMMM","C8LpwaPOdkBDpzYvxDmA","4znleAk6l3E1eb1kAEXK","SMTiuEOKEPoBpAzxEikd","L4oapIYo87lkQANWsgiD","DkivDvDBirmX4HIHU3cW","Axbap5tRt6FJZjVpTjCJ","zeej1z22AFNszRlMGmkq","GR3i7DOtAFLazN46D7cB","3C1ZgRS2sr2VFMYGdzIN"]', '{"colorTheme":"blue","mode":"dark"}');
INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('rH17ByrpARc0SBoAhIcAFj9bP9h2', '2025-08-23T12:58:54.000Z', 'Mohammed Bilal', '{"mode":"system","colorTheme":"blue"}', 'riyadh-housing@sacodeco.net', 'Supervisor', '["gpKfg1LK8UBxPIhHiuPa","L4oapIYo87lkQANWsgiD","rMRf9xOfBZqUw8GKPMMM","3C1ZgRS2sr2VFMYGdzIN"]');
INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('teeJesoz2pYTZvHNmC7a7tLiwPO2', '2025-08-23T12:58:17.000Z', 'Sadru Aldin', '{"mode":"system","colorTheme":"blue"}', 'hamdaniya-housing@sacodeco.net', 'Supervisor', '["6w8r1vh1h8xjpOsVULV5","KA43UwlETuLC7bWffony","Axbap5tRt6FJZjVpTjCJ"]');
INSERT OR REPLACE INTO users (id, created_at, name, theme_settings, email, role, assigned_residences) VALUES ('wdtDvJV1skMRa2mEX3SvOcwAj9G2', '2025-08-23T12:57:31.000Z', 'Ahmed Alzahrani', '{"mode":"system","colorTheme":"blue"}', 'makkah-housing@sacodeco.net', 'Supervisor', '["L3wLRKW34H2dM2tQaBfI","C8LpwaPOdkBDpzYvxDmA"]');
