INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51001_SACODECO', 'Worker', 'MONIS SHAMSHAD', 'SACODECO', '51001', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51002_SACODECO', 'Worker', 'MOHAMMAD ANWAR MOHAMMAD KHALID', 'SACODECO', '51002', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51003_SACODECO', 'Worker', 'MOHAMMAD ANAS MOHAMMAD KHALIL', 'SACODECO', '51003', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51004_SACODECO', 'Worker', 'MOHAMMAD TASLEEM MOHAMMAD IBRAHEEM', 'SACODECO', '51004', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51006_SACODECO', 'Worker', 'MOHAMMAD NADEEM MOHAMMAD USMAN', 'SACODECO', '51006', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51007_SACODECO', 'Worker', 'IRFAN KHAN SAFI MOHAMMAD', 'SACODECO', '51007', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51008_SACODECO', 'Worker', 'JISHAN YASHIN', 'SACODECO', '51008', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51009_SACODECO', 'Worker', 'MUHAMAMD FAIZAN NAFIS AHMAD', 'SACODECO', '51009', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51010_SACODECO', 'Worker', 'MOHD SUHAIL MOHD FURKAN', 'SACODECO', '51010', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51011_SACODECO', 'Worker', 'ISRUDDIN HASMUDDIN', 'SACODECO', '51011', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51012_SACODECO', 'Worker', 'MUHAMMAD DANISH SHAHID HUSAIN', 'SACODECO', '51012', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51013_SACODECO', 'Worker', 'MO SHARIK SHAHMAT', 'SACODECO', '51013', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51015_SACODECO', 'Worker', 'RIYAJUL HUSAIN NISHAR AHAMAD', 'SACODECO', '51015', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51017_SACODECO', 'Worker', 'SHARIK HABIB', 'SACODECO', '51017', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51018_SACODECO', 'Worker', 'MOHD FAISAL SHARAFAT', 'SACODECO', '51018', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51019_SACODECO', 'Worker', 'MOHD AYAAN SARAFAT ALI', 'SACODECO', '51019', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51020_SACODECO', 'Worker', 'MOHAMMAD FAISAL SHAKEEL AHMAD', 'SACODECO', '51020', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51021_SACODECO', 'Worker', 'MOHASEEN ASAGAR', 'SACODECO', '51021', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51022_SACODECO', 'Worker', 'AASIF MOHAMMAD SHAFEEQ', 'SACODECO', '51022', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51023_SACODECO', 'Worker', 'MOH NADEEM NASEEM AHMAD', 'SACODECO', '51023', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51025_SACODECO', 'Worker', 'NAVED ALI NAFEES', 'SACODECO', '51025', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51026_SACODECO', 'Worker', 'MOHD RIHAN SHAHZAD ALI', 'SACODECO', '51026', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51029_SACODECO', 'Worker', 'MOHD SHABAN MOHD ASHFAQ', 'SACODECO', '51029', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51030_SACODECO', 'Worker', 'SALMAN MASROOR', 'SACODECO', '51030', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51031_SACODECO', 'Worker', 'DANISH AYYUB', 'SACODECO', '51031', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_51032_SACODECO', 'Worker', 'RIHAN ALI AHMAD', 'SACODECO', '51032', 'Indian', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51033_SACODECO', 'Worker', 'MOHD GULFAM MOHD UMAR', 'SACODECO', '51033', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51034_SACODECO', 'Worker', 'MOHAMMAD ANAS MOHAMMAD KAISAR', 'SACODECO', '51034', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51035_SACODECO', 'Worker', 'NAVED ALAM RAEES AHAMAD', 'SACODECO', '51035', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51037_SACODECO', 'Worker', 'NAJIR KHA SHAKIL KHAN', 'SACODECO', '51037', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51040_SACODECO', 'Worker', 'MOHAMMAD AASIF SALEEM', 'SACODECO', '51040', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51041_SACODECO', 'Worker', 'AKRAM MUNNA', 'SACODECO', '51041', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51043_SACODECO', 'Worker', 'GULJAR NAJIR AHMAD', 'SACODECO', '51043', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51044_SACODECO', 'Worker', 'ERIS ISTEKAR', 'SACODECO', '51044', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51045_SACODECO', 'Worker', 'MOHD SAJID MOHD JILANI', 'SACODECO', '51045', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51046_SACODECO', 'Worker', 'MOHD AMAN NAIM AHAMAD', 'SACODECO', '51046', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51047_SACODECO', 'Worker', 'MOHAMMED SAMIR MOHD MUSTAK GORI', 'SACODECO', '51047', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51048_SACODECO', 'Worker', 'MONISH ISRAR HUSAIN', 'SACODECO', '51048', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51050_SACODECO', 'Worker', 'MOHAMMAD AZAD MOHD NIJAMUDDIN', 'SACODECO', '51050', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51051_SACODECO', 'Worker', 'NAJIR NAZIM AHMAD', 'SACODECO', '51051', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51052_SACODECO', 'Worker', 'JAID MOHD AKRAM', 'SACODECO', '51052', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51054_SACODECO', 'Worker', 'SHAMI SHAUKEEN', 'SACODECO', '51054', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51056_SACODECO', 'Worker', 'ADIL NASEEM KHAN', 'SACODECO', '51056', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51057_SACODECO', 'Worker', 'KASHIM RAIS AHMAD', 'SACODECO', '51057', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51059_SACODECO', 'Worker', 'NAAVED ALAM YAASHEEN', 'SACODECO', '51059', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51060_SACODECO', 'Worker', 'MOHD FARHAN SHARIF AHAMAD', 'SACODECO', '51060', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51061_SACODECO', 'Worker', 'GUFRAN SHAHZAD ALI', 'SACODECO', '51061', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51062_SACODECO', 'Worker', 'MOHAMMAD NAJIM ABDUL RASEED', 'SACODECO', '51062', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51063_SACODECO', 'Worker', 'MOHD SHAHBAZ KHAN', 'SACODECO', '51063', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51064_SACODECO', 'Worker', 'MOHAMMAD NAZIM MOHAMMAD IRFAN', 'SACODECO', '51064', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51065_SACODECO', 'Worker', 'TAHSEEN AHMAD MOHAMAD RAIS', 'SACODECO', '51065', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51066_SACODECO', 'Worker', 'MOHAMMAD ARIF INTEJAR AHMAD', 'SACODECO', '51066', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51068_SACODECO', 'Worker', 'UMAID MOHAMMAD AKRAM', 'SACODECO', '51068', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51070_SACODECO', 'Worker', 'FARMAN KHAN RAZI ULLAH', 'SACODECO', '51070', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51071_SACODECO', 'Worker', 'MD MANAUWR ALAM', 'SACODECO', '51071', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51072_SACODECO', 'Worker', 'SHANIB MATLOOB', 'SACODECO', '51072', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51073_SACODECO', 'Worker', 'MOHD AKIB GUL HASAN', 'SACODECO', '51073', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51075_SACODECO', 'Worker', 'Afzal ahmed muhammad sarab', 'SACODECO', '51075', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51080_SACODECO', 'Worker', 'EJAZ KHAN BASIR KHAN', 'SACODECO', '51080', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51081_SACODECO', 'Worker', 'SUHEL NASEER AHMAD', 'SACODECO', '51081', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51082_SACODECO', 'Worker', 'MOHAMMAD IBRAHEEM RAHMAT ALI', 'SACODECO', '51082', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51083_SACODECO', 'Worker', 'JAFEER AHMAD AISH MOHD', 'SACODECO', '51083', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51084_SACODECO', 'Worker', 'MO ARIF MU HANIF', 'SACODECO', '51084', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51085_SACODECO', 'Worker', 'MAHFOOJ ALAM IKBAL KURAISHI', 'SACODECO', '51085', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51086_SACODECO', 'Worker', 'MOHD IMARAN MOHD ARIF', 'SACODECO', '51086', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51087_SACODECO', 'Worker', 'SAHWAN SAFIULLA', 'SACODECO', '51087', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51088_SACODECO', 'Worker', 'MOHAMAMD AASIF MOHAMMAD SHABAN', 'SACODECO', '51088', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51089_SACODECO', 'Worker', 'AZEEM ALI HASAN', 'SACODECO', '51089', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51090_SACODECO', 'Worker', 'MO AASIF MO SAFEEK', 'SACODECO', '51090', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51091_SACODECO', 'Worker', 'MOHD KAIF KHAN', 'SACODECO', '51091', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51092_SACODECO', 'Worker', 'ALI SAHAB ABDUL MATEEN', 'SACODECO', '51092', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51093_SACODECO', 'Worker', 'MOHAMMAD ANAS WAKIL AHMAD', 'SACODECO', '51093', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51094_SACODECO', 'Worker', 'MUSIR MURTAJ', 'SACODECO', '51094', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51095_SACODECO', 'Worker', 'MOHD IRSHAD MOHD JAKIR', 'SACODECO', '51095', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51097_SACODECO', 'Worker', 'FAEEM AHMAD ATEEK AHMAD', 'SACODECO', '51097', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51099_SACODECO', 'Worker', 'MOSEEM NABAB JAAN', 'SACODECO', '51099', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51100_SACODECO', 'Worker', 'MURSALIM MUSTAKIM', 'SACODECO', '51100', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51102_SACODECO', 'Worker', 'AMAN MOHD IQBAL', 'SACODECO', '51102', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51103_SACODECO', 'Worker', 'SALMAN SHAH ALAM', 'SACODECO', '51103', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51104_SACODECO', 'Worker', 'MO ADIL MO ANEES', 'SACODECO', '51104', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51105_SACODECO', 'Worker', 'HASMUDDIN MIYAN AHMAD MIYAN', 'SACODECO', '51105', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51106_SACODECO', 'Worker', 'RAFIQ USMAN GANI', 'SACODECO', '51106', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51107_SACODECO', 'Worker', 'SADDAM KHAN SAWAI KHAN', 'SACODECO', '51107', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51108_SACODECO', 'Worker', 'GULFAN INTAZAR', 'SACODECO', '51108', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51109_SACODECO', 'Worker', 'SHAMSHER ALAM BISMIL MIYAN', 'SACODECO', '51109', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51111_SACODECO', 'Worker', 'ZEESHAN ABDUL VARIS', 'SACODECO', '51111', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51112_SACODECO', 'Worker', 'MURSALEEM MOHD FAEEM', 'SACODECO', '51112', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51113_SACODECO', 'Worker', 'MUHAMMAD SAMEER SHAMEEM AHMAD', 'SACODECO', '51113', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51114_SACODECO', 'Worker', 'MOHD SARIK RAFEEK', 'SACODECO', '51114', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51115_SACODECO', 'Worker', 'MOHAMMAD SABIR AYYUB ANSARI', 'SACODECO', '51115', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51117_SACODECO', 'Worker', 'MOHD SOBI NASEEM AHMAD', 'SACODECO', '51117', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51121_SACODECO', 'Worker', 'NIZAMUDIN SALEEM AHMAD', 'SACODECO', '51121', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51122_SACODECO', 'Worker', 'ARSLAN DILVER', 'SACODECO', '51122', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51123_SACODECO', 'Worker', 'MOHD FARMAN MOHD NAFEES', 'SACODECO', '51123', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51124_SACODECO', 'Worker', 'JASHIM MUKEEM', 'SACODECO', '51124', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51125_SACODECO', 'Worker', 'EJAZ KHAN ABDUL MANNAN', 'SACODECO', '51125', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51126_SACODECO', 'Worker', 'MOHAMMAD AFZAL MOHAMMAD SAJJAN', 'SACODECO', '51126', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51127_SACODECO', 'Worker', 'ABDUL REHMAN MO ANWAR', 'SACODECO', '51127', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51128_SACODECO', 'Worker', 'MOHD SHAKIB ISTIKHAR ALI', 'SACODECO', '51128', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51129_SACODECO', 'Worker', 'FAISU KHAN FIDA HUSAIN', 'SACODECO', '51129', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51138_SACODECO', 'Worker', 'NAFEES WAREES', 'SACODECO', '51138', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51140_SACODECO', 'Worker', 'FARMAN KAMRUDDIN', 'SACODECO', '51140', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51146_SACODECO', 'Worker', 'AKRAM AHMAD ISLAMUDDIN', 'SACODECO', '51146', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51148_SACODECO', 'Worker', 'NADIM SABIR', 'SACODECO', '51148', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51149_SACODECO', 'Worker', 'SHANU KHAN MAHBOOB KHAN', 'SACODECO', '51149', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51151_SACODECO', 'Worker', 'MATLUB KHAN HASAN ALI', 'SACODECO', '51151', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51152_SACODECO', 'Worker', 'NAVED ALAM MOHD IKRAM', 'SACODECO', '51152', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51153_SACODECO', 'Worker', 'ADIL RAIS AHMAD', 'SACODECO', '51153', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51154_SACODECO', 'Worker', 'MOHAMMAD FAISAL FURKAN ALI', 'SACODECO', '51154', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51155_SACODECO', 'Worker', 'SHAKIB SHAKIR', 'SACODECO', '51155', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51157_SACODECO', 'Worker', 'FARID HUSAIN TAHIR HUSAIN', 'SACODECO', '51157', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51161_SACODECO', 'Worker', 'AHMED SAMIR ELSAYED ABDELGALIL', 'SACODECO', '51161', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51163_SACODECO', 'Worker', 'HAJARAT ALI ABBAS ALI', 'SACODECO', '51163', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51164_SACODECO', 'Worker', 'ABDUL HASAN HAKIKULLA', 'SACODECO', '51164', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51165_SACODECO', 'Worker', 'HASIM KHAN HIDAYAT KHAN', 'SACODECO', '51165', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51166_SACODECO', 'Worker', 'DILBAR KHAN HAIDAR HUSAIN', 'SACODECO', '51166', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51167_SACODECO', 'Worker', 'SHAHID HUSEN KAMRUDDEEN KURAISHI', 'SACODECO', '51167', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51168_SACODECO', 'Worker', 'MOHD RASID MOHD RAFIK', 'SACODECO', '51168', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51169_SACODECO', 'Worker', 'CHAND ALI ABBAS ALI', 'SACODECO', '51169', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51170_SACODECO', 'Worker', 'MOHD REHAN FAROOK', 'SACODECO', '51170', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51171_SACODECO', 'Worker', 'AQEEL AHMAD SAGEER AHMAD', 'SACODECO', '51171', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51172_SACODECO', 'Worker', 'MOHD LARAIB ANWARUL HAQUE', 'SACODECO', '51172', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51173_SACODECO', 'Worker', 'MOHD SHAMSHER KHAN', 'SACODECO', '51173', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51174_SACODECO', 'Worker', 'NASEEM KHAN AMEEN KHAN', 'SACODECO', '51174', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51175_SACODECO', 'Worker', 'MUKIM AMIN', 'SACODECO', '51175', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51176_SACODECO', 'Worker', 'NANBABU TUFAIL AHMAD', 'SACODECO', '51176', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51177_SACODECO', 'Worker', 'FARDEEN HUSAIN KHAN', 'SACODECO', '51177', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51178_SACODECO', 'Worker', 'SAJRE ALAM ACHHAN KHAN', 'SACODECO', '51178', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51179_SACODECO', 'Worker', 'CHANDBABOO MUMTAJ ALI', 'SACODECO', '51179', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51182_SACODECO', 'Worker', 'FIROJ HAKAM ALI', 'SACODECO', '51182', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51184_SACODECO', 'Worker', 'MOHD MAROOF RAZA', 'SACODECO', '51184', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51187_SACODECO', 'Worker', 'MOHD KAIF MOHD UMAR', 'SACODECO', '51187', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51188_SACODECO', 'Worker', 'MOHD ARMAN MOHD AKBAR', 'SACODECO', '51188', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51189_SACODECO', 'Worker', 'SAJID ALI ABDUL GAFAR BHUTTA', 'SACODECO', '51189', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51191_SACODECO', 'Worker', 'MOHAMMAD AAMIR MAKSOOD', 'SACODECO', '51191', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51193_SACODECO', 'Worker', 'MOHD SUHAIL IKBAL', 'SACODECO', '51193', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51194_SACODECO', 'Worker', 'MOHD FAIZAN ABDUL MAJEED', 'SACODECO', '51194', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51195_SACODECO', 'Worker', 'MOHAMMAD FAIJAN ALIHSAN', 'SACODECO', '51195', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51196_SACODECO', 'Worker', 'IMRAN KHILJI MO AKRAM KHILJI', 'SACODECO', '51196', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51197_SACODECO', 'Worker', 'MOH SHAHID TAHIR HUSAIN', 'SACODECO', '51197', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51198_SACODECO', 'Worker', 'MOHD AYAAN DILSHAD ALI', 'SACODECO', '51198', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51199_SACODECO', 'Worker', 'MOHD JUBAIR SHAMIM AHAMAD', 'SACODECO', '51199', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51200_SACODECO', 'Worker', 'MOHAMMAD FAHAD MOHAMMAD HASIM', 'SACODECO', '51200', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51201_SACODECO', 'Worker', 'MOHD SHADAB MO IRSHAD', 'SACODECO', '51201', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51202_SACODECO', 'Worker', 'SHAHJAD WASHEER AHMAD', 'SACODECO', '51202', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51203_SACODECO', 'Worker', 'RABBUL RAEES', 'SACODECO', '51203', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51204_SACODECO', 'Worker', 'SHAHNAWAZ ABRAR', 'SACODECO', '51204', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51205_SACODECO', 'Worker', 'MUDDSHIR MOHAMMAD AFSHAN', 'SACODECO', '51205', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51206_SACODECO', 'Worker', 'MOHAMMAD IRFAN MOHAMMAD ABUNASAR', 'SACODECO', '51206', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51207_SACODECO', 'Worker', 'MOHAMMAD SHAHNVAJ MOHAMMAD HANIF', 'SACODECO', '51207', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51208_SACODECO', 'Worker', 'WASIM HUSSAIN MATLUB HUSSAIN', 'SACODECO', '51208', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51209_SACODECO', 'Worker', 'MOHAMMAD DANISH RIYAZUL HAQ', 'SACODECO', '51209', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51210_SACODECO', 'Worker', 'SHARIQ MOHD AKHTAR', 'SACODECO', '51210', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51211_SACODECO', 'Worker', 'IMRAN AHMAD MOHD IRSHAD', 'SACODECO', '51211', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51212_SACODECO', 'Worker', 'ISHTIYAK ALI MOHD YUNUS', 'SACODECO', '51212', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51213_SACODECO', 'Worker', 'MOHD ARBAZ NOOR HASAN', 'SACODECO', '51213', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51214_SACODECO', 'Worker', 'AJAD SAJID', 'SACODECO', '51214', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51215_SACODECO', 'Worker', 'SAYAN SABIR', 'SACODECO', '51215', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51216_SACODECO', 'Worker', 'MOHAMMAD ARMAN RAHEES AHMAD', 'SACODECO', '51216', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51217_SACODECO', 'Worker', 'MOHAMMAD SALMAN NISAR', 'SACODECO', '51217', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51218_SACODECO', 'Worker', 'SALEEM MOHD NAIM', 'SACODECO', '51218', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51219_SACODECO', 'Worker', 'MOHD NOUMAN MOHD AKRAM', 'SACODECO', '51219', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51220_SACODECO', 'Worker', 'ARBAJ MOHD SAEED', 'SACODECO', '51220', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51222_SACODECO', 'Worker', 'MOHD IMRAN NASEEM AHMAD', 'SACODECO', '51222', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51223_SACODECO', 'Worker', 'MOHD TARIK AARIF', 'SACODECO', '51223', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51224_SACODECO', 'Worker', 'MOHD SUHAIL NAEEM', 'SACODECO', '51224', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51225_SACODECO', 'Worker', 'MOHAMMAD FURQAN MOHAMMAD SHAHID', 'SACODECO', '51225', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51227_SACODECO', 'Worker', 'MOHD RAJA MOHD RAJU', 'SACODECO', '51227', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51228_SACODECO', 'Worker', 'SHAHJAN AHMAD MOHAMMAD BABU', 'SACODECO', '51228', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51229_SACODECO', 'Worker', 'MOHAMMED DAUD MOHAMMED CHAND BISAYATI', 'SACODECO', '51229', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51230_SACODECO', 'Worker', 'SAMEER AHMAD ISRAR AHAMAD', 'SACODECO', '51230', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51231_SACODECO', 'Worker', 'ANAS MOHD AFJAAL', 'SACODECO', '51231', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51232_SACODECO', 'Worker', 'MEHARDIN MOHD NASIM', 'SACODECO', '51232', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51233_SACODECO', 'Worker', 'SHANE ALAM NASEEM AHMAD', 'SACODECO', '51233', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51234_SACODECO', 'Worker', 'ASIF BHUTTA MAHABOOB BHUTTA', 'SACODECO', '51234', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51235_SACODECO', 'Worker', 'SAQIB ABDUL SAMI', 'SACODECO', '51235', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51236_SACODECO', 'Worker', 'EKLAKH ALAM SALAUDDIN SAFI', 'SACODECO', '51236', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51241_SACODECO', 'Worker', 'MO IRAFAN MO AKBAR', 'SACODECO', '51241', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51242_SACODECO', 'Worker', 'MOHAMMAD ANAS ZAREEF AHMAD', 'SACODECO', '51242', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51243_SACODECO', 'Worker', 'MOHAMMAD KAIF RAIS AHMAD', 'SACODECO', '51243', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51244_SACODECO', 'Worker', 'SOYAB ABDUL HAKIM', 'SACODECO', '51244', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51245_SACODECO', 'Worker', 'MO BARIK MO ARIF BISAYATI', 'SACODECO', '51245', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51246_SACODECO', 'Worker', 'MOHD RAGIB MOHD ATIK', 'SACODECO', '51246', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51247_SACODECO', 'Worker', 'AYAN IFTEKAR AHMAD', 'SACODECO', '51247', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51248_SACODECO', 'Worker', 'FAISAL SAID', 'SACODECO', '51248', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51249_SACODECO', 'Worker', 'MOHD HASAN MOHD ASLAM', 'SACODECO', '51249', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51250_SACODECO', 'Worker', 'MOHAMMAD FAIJUL HASEENUDDIN', 'SACODECO', '51250', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51251_SACODECO', 'Worker', 'SAMIR MO SALIM', 'SACODECO', '51251', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51252_SACODECO', 'Worker', 'MOHD SAAD SHAHZAD ALAM', 'SACODECO', '51252', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51259_SACODECO', 'Worker', 'MOHAMMAD BAKHTIYAR MD TALIM', 'SACODECO', '51259', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51260_SACODECO', 'Supervisor', 'HANAFY MAHMOUD NADY ALY', 'SACODECO', '51260', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51261_SACODECO', 'Supervisor', 'MAHMOUD AHMED ABDELHAMED SHEHATA', 'SACODECO', '51261', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51262_SACODECO', 'Worker', 'ASGAR ALI RAJJAB', 'SACODECO', '51262', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51263_SACODECO', 'Worker', 'NABI HASAN MO HANIF', 'SACODECO', '51263', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51264_SACODECO', 'Worker', 'MOHAMMAD FARHAN ABDUL KHALIQ ANSARI', 'SACODECO', '51264', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51265_SACODECO', 'Worker', 'RIZWAN AHAMD RAMJAN ALI', 'SACODECO', '51265', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51266_SACODECO', 'Worker', 'ARKAN HUSAIN MUNAVWAR ALI', 'SACODECO', '51266', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51267_SACODECO', 'Worker', 'MAKSUD MO AYOOB', 'SACODECO', '51267', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51268_SACODECO', 'Worker', 'ARSHAAD RAZA MOHD KALAM', 'SACODECO', '51268', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51269_SACODECO', 'Worker', 'MO ADIL NANKE', 'SACODECO', '51269', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51270_SACODECO', 'Worker', 'RAJA BABU KHAN KAJJAN KHAN', 'SACODECO', '51270', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51271_SACODECO', 'Worker', 'ALI ASAD BABAR ALI', 'SACODECO', '51271', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51272_SACODECO', 'Worker', 'DILDAR KHAN MUNNA KHAN', 'SACODECO', '51272', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51273_SACODECO', 'Worker', 'MOHD LAREB MOHD HALIM', 'SACODECO', '51273', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51274_SACODECO', 'Worker', 'MOHD FAHEEM KHAN MOHD TARIK KHAN', 'SACODECO', '51274', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51275_SACODECO', 'Worker', 'MOHD SAHIL MOHD AKHRUJJAMA', 'SACODECO', '51275', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51276_SACODECO', 'Worker', 'SAHIL KHAN KALAMUDDIN', 'SACODECO', '51276', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51277_SACODECO', 'Worker', 'MAAZ AHMAD NABI AHMAD', 'SACODECO', '51277', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51278_SACODECO', 'Worker', 'MOHAMMAD SAHIL MOHAMMAD ASIN', 'SACODECO', '51278', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51279_SACODECO', 'Worker', 'SADDAM HUSAIN AHMAD ALI', 'SACODECO', '51279', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51280_SACODECO', 'Worker', 'MOHD JAVED BAFATI', 'SACODECO', '51280', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51281_SACODECO', 'Worker', 'PARVEZ KHAN MUJAMMIL KHAN', 'SACODECO', '51281', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51282_SACODECO', 'Worker', 'ASIF KHAN JULFIKAR KHAN', 'SACODECO', '51282', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51283_SACODECO', 'Worker', 'KAIF KHAN MASHUD ALI KHAN', 'SACODECO', '51283', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51284_SACODECO', 'Worker', 'SAMSHAD ALI JALIL AHMAD', 'SACODECO', '51284', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51285_SACODECO', 'Worker', 'FAKHRE ALAM ANSARI IMDAD ALI', 'SACODECO', '51285', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51286_SACODECO', 'Worker', 'MO AJAD PHOOL MOHAMMED', 'SACODECO', '51286', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51287_SACODECO', 'Worker', 'KHUSNED KHAN KADIR KHAN', 'SACODECO', '51287', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51294_SACODECO', 'Worker', 'MOHAMMAD TAUFIK HASAN', 'SACODECO', '51294', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51295_SACODECO', 'Worker', 'IMRAN JAMSHED', 'SACODECO', '51295', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51296_SACODECO', 'Worker', 'VAJEER AHAMAD MOHRRAM ALI', 'SACODECO', '51296', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51297_SACODECO', 'Worker', 'SAKLEN KHAN DIL NEVAJ AHMAD KHAN', 'SACODECO', '51297', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51298_SACODECO', 'Worker', 'MOHD SHAHJAD SHAREEF', 'SACODECO', '51298', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51299_SACODECO', 'Worker', 'ABDUL RAHMAN AKHTAR', 'SACODECO', '51299', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51300_SACODECO', 'Worker', 'AJLAAN HASAN ALI', 'SACODECO', '51300', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51301_SACODECO', 'Worker', 'SAHID RHIS', 'SACODECO', '51301', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51305_SACODECO', 'Supervisor', 'ABDUL RAHMAN ABDUL KHADEER', 'SACODECO', '51305', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51306_SACODECO', 'Supervisor', 'KAZI MOHD ARFAT MOHD AKRAM', 'SACODECO', '51306', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51307_SACODECO', 'Worker', 'SAHNAWAJ KHAN DASTGEER KHAN', 'SACODECO', '51307', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51308_SACODECO', 'Worker', 'MOHAMMAD ARSHAD KHAN', 'SACODECO', '51308', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51309_SACODECO', 'Worker', 'MOHAMMAD ASHIF MOHAMMAD ISLAM', 'SACODECO', '51309', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51310_SACODECO', 'Worker', 'AKRAMUDDIN AKBUDDIN', 'SACODECO', '51310', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51311_SACODECO', 'Worker', 'ALI KAIF KHAN', 'SACODECO', '51311', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51312_SACODECO', 'Worker', 'SAHIL KHAN MAHTAB ALAM', 'SACODECO', '51312', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51313_SACODECO', 'Worker', 'ABDUL KAREEM KUTUBUDDIN', 'SACODECO', '51313', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51315_SACODECO', 'Worker', 'MO ASHIF HABIBURRAHMAN', 'SACODECO', '51315', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51316_SACODECO', 'Worker', 'MO DANISH MOHD KALEEM', 'SACODECO', '51316', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51317_SACODECO', 'Worker', 'MOHD FIROJ JAHOOR', 'SACODECO', '51317', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51318_SACODECO', 'Worker', 'MOHAMMAD TOWAB HAMID KHA', 'SACODECO', '51318', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51319_SACODECO', 'Worker', 'MOHAMMAD SHOEIB SHABBIR', 'SACODECO', '51319', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51320_SACODECO', 'Worker', 'MOHAMMAD IRSAD MOHAMMAD AJJAN', 'SACODECO', '51320', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51321_SACODECO', 'Worker', 'MOHSIN ALI MUHAMMAD ASHRAF', 'SACODECO', '51321', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51322_SACODECO', 'Worker', 'UMAIR FIAZ FIAZ IQBAL', 'SACODECO', '51322', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51323_SACODECO', 'Worker', 'MUHAMMAD SHAH KHAN SARWAR SHAH', 'SACODECO', '51323', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51324_SACODECO', 'Worker', 'ASAD KHAN SABIR KHAN', 'SACODECO', '51324', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51325_SACODECO', 'Worker', 'SHAHAB AHMAD FAZAL AHAD', 'SACODECO', '51325', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51326_SACODECO', 'Worker', 'MUHAMMAD SHAMRAIZ BARKAT ALI', 'SACODECO', '51326', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51327_SACODECO', 'Worker', 'SYED WASI HASNAIN SHAH SYED QAMAR ABBAS', 'SACODECO', '51327', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51328_SACODECO', 'Worker', 'KAMAL YOUSAF MUHAMMAD YOUSAF', 'SACODECO', '51328', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51329_SACODECO', 'Worker', 'ZOHAIB SHAH MUHAMMAD NADEEM', 'SACODECO', '51329', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51330_SACODECO', 'Worker', 'UMAIR ALI ALI ASGHAR', 'SACODECO', '51330', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51331_SACODECO', 'Worker', 'WAQAS ASHIQ ASHIQ ALI', 'SACODECO', '51331', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51332_SACODECO', 'Worker', 'SHAHID MUSTAFA BARKAT ALI', 'SACODECO', '51332', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51333_SACODECO', 'Worker', 'TAYYAB MAZHAR MAZHAR IQBAL', 'SACODECO', '51333', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51334_SACODECO', 'Worker', 'SOHAIL AZAM MUHAMMAD AZAM', 'SACODECO', '51334', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51335_SACODECO', 'Worker', 'SAEED ALI QAMAR ZAMAN', 'SACODECO', '51335', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51336_SACODECO', 'Worker', 'WASIM SAJJAD LOOL BAP', 'SACODECO', '51336', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51337_SACODECO', 'Worker', 'MUHAMMAD NADEEM KHALID ABDUL RAUF', 'SACODECO', '51337', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51338_SACODECO', 'Worker', 'NABEEL IKHLAQ MUHAMMAD IKHLAQ KHAN', 'SACODECO', '51338', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51339_SACODECO', 'Worker', 'SAQIB MEHMOOD GHOUS MUHAMMAD', 'SACODECO', '51339', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51342_SACODECO', 'Worker', 'AHMED MUHAMMAD MUNAWAR', 'SACODECO', '51342', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51343_SACODECO', 'Worker', 'KAMRAN HUSSAIN NOOR ZAMAN', 'SACODECO', '51343', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51344_SACODECO', 'Worker', 'MUHAMMAD ISMAIL MUHAMMAD AYUB', 'SACODECO', '51344', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51345_SACODECO', 'Worker', 'MATEE UR REHMAN GHULAM RASOOL', 'SACODECO', '51345', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51346_SACODECO', 'Worker', 'MUHAMMAD WAJID ABDUL SATTAR', 'SACODECO', '51346', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51347_SACODECO', 'Worker', 'WAQAS JAVED MUHAMMAD JAVED', 'SACODECO', '51347', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51348_SACODECO', 'Worker', 'ABDULLAH FAZAL KHALIQ', 'SACODECO', '51348', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51349_SACODECO', 'Worker', 'AQIB LATIF MUHAMMAD LATIF KHAN', 'SACODECO', '51349', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51350_SACODECO', 'Worker', 'HUSNAIN MAJEED ABDUL MAJEED', 'SACODECO', '51350', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51351_SACODECO', 'Worker', 'MUHAMMAD MUNIR BAZ MIR', 'SACODECO', '51351', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51352_SACODECO', 'Worker', 'MUHAMMAD WAQAS MUHAMMAD AMIN', 'SACODECO', '51352', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51353_SACODECO', 'Worker', 'NAQEEB ULLAH DARWESH BADSHAH', 'SACODECO', '51353', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51354_SACODECO', 'Worker', 'SAEED AHMED SHOUKAT IQBAL', 'SACODECO', '51354', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51355_SACODECO', 'Worker', 'SULTAN WALI AZIZ WALI SHAH', 'SACODECO', '51355', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51356_SACODECO', 'Worker', 'AKASH ALI MUHAMMAD MUSHTAQ', 'SACODECO', '51356', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51357_SACODECO', 'Worker', 'FAISAL BASHIR BASHIR AHMAD', 'SACODECO', '51357', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51358_SACODECO', 'Worker', 'BABAR ASLAM MUHAMMAD ASLAM', 'SACODECO', '51358', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51359_SACODECO', 'Worker', 'GULFAM ALI RIASAT', 'SACODECO', '51359', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51360_SACODECO', 'Worker', 'BASIT ALI NAZIR HUSSAIN', 'SACODECO', '51360', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51361_SACODECO', 'Worker', 'ATIF UR REHMAN SHABBIR ALI', 'SACODECO', '51361', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51362_SACODECO', 'Worker', 'FAHAD MUJAHID MUHAMMAD MUJAHID', 'SACODECO', '51362', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51363_SACODECO', 'Worker', 'ASIF HUSSAIN MUNIR AHMAD', 'SACODECO', '51363', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51364_SACODECO', 'Worker', 'ADIL SAID ABDUL SAID', 'SACODECO', '51364', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51365_SACODECO', 'Worker', 'HARIS MEHMOOD MEHMOOD AKHTAR', 'SACODECO', '51365', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51366_SACODECO', 'Worker', 'GUL MUHAMMAD LAL MUHAMMAD', 'SACODECO', '51366', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51367_SACODECO', 'Worker', 'FAIZAN AHMED MUHAMMED ISHFAQ', 'SACODECO', '51367', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51368_SACODECO', 'Worker', 'HAMID NAWAZ MUHAMMAD NAWAZ', 'SACODECO', '51368', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51369_SACODECO', 'Worker', 'AMJAD KHAN AJMAL KHAN', 'SACODECO', '51369', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51370_SACODECO', 'Worker', 'BILAL AHMED NOOR GUL', 'SACODECO', '51370', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51371_SACODECO', 'Worker', 'MUHAMMAD FARMAN MUHAMMAD SALEEM', 'SACODECO', '51371', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51372_SACODECO', 'Worker', 'MEHRAB AHMED MUHAMMAD FAYYAZ', 'SACODECO', '51372', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51373_SACODECO', 'Worker', 'MUHAMMAD ALI RAFIQUE AHMAD', 'SACODECO', '51373', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51374_SACODECO', 'Worker', 'MUHAMMAD USMAN SHAHID MUNIR', 'SACODECO', '51374', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51375_SACODECO', 'Worker', 'HAROON ABDUL MAJEED', 'SACODECO', '51375', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51376_SACODECO', 'Worker', 'MUHAMMAD SHAHBAZ DILSHAD ABID', 'SACODECO', '51376', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51377_SACODECO', 'Worker', 'MUHAMMAD YASEEN GUL TAJ', 'SACODECO', '51377', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51378_SACODECO', 'Worker', 'MUHAMMAD AMJAD KHAN PERVAIZ KHAN', 'SACODECO', '51378', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51379_SACODECO', 'Worker', 'HUZAIFA ARSHAD ARSHAD KHAN', 'SACODECO', '51379', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51380_SACODECO', 'Worker', 'MUHAMMAD HANAN QAMAR ABDUL GHAFFAR', 'SACODECO', '51380', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51381_SACODECO', 'Worker', 'MUHAMMAD ADEEL MUHAMMAD MASKEEN', 'SACODECO', '51381', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_51382_SACODECO', 'Worker', 'MUHAMMAD TAIMOOR MUHAMMAD ARSHAD', 'SACODECO', '51382', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_52094_فاست', 'Worker', 'قيصر محمود غلام رسول', 'فاست', '52094', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_52347_فاست', 'Worker', 'اليس احمد فضل احمد', 'فاست', '52347', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_52377_فاست', 'Worker', 'مظهر حسين نزير محمد', 'فاست', '52377', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_52670_Nesma', 'Worker', 'MD RABBI HOSSAIN', 'Nesma', '52670', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_52691_فاست', 'Worker', 'عبدالقدير خان محمد عزيز خان', 'فاست', '52691', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53103_فاست', 'Worker', 'بهار على افصار خان', 'فاست', '53103', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53146_فاست', 'Worker', 'فيصل رزاق', 'فاست', '53146', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53343_فاست', 'Worker', 'والي محمد شير', 'فاست', '53343', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53435_فاست', 'Worker', 'عبد الرشيد محمد صديق انجو', 'فاست', '53435', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53486_فاست', 'Worker', 'نصير احمد', 'فاست', '53486', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53649_فاست', 'Worker', 'ذو الفقار خان محمد عزام', 'فاست', '53649', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53829_فاست', 'Worker', 'مسلم بسياتي', 'فاست', '53829', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_53964_فاست', 'Worker', 'شاهد مشتاق مشتاق احمد', 'فاست', '53964', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_54151_فاست', 'Worker', 'عصام عبد العزيز عبد العزيز', 'فاست', '54151', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_54477_فاست', 'Worker', 'على حسن محمد', 'فاست', '54477', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_54558_فاست', 'Worker', 'محمد صابر عبدالقيوم', 'فاست', '54558', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_55162_فاست', 'Worker', 'بهار علي محمد اشرف', 'فاست', '55162', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_55297_فاست', 'Worker', 'محمد اصف', 'فاست', '55297', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_55370_فاست', 'Worker', 'اسلم جاويد شير محمد', 'فاست', '55370', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_55473_فاست', 'Worker', 'محمد علي حيدر', 'فاست', '55473', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_56656_فاست', 'Worker', 'محمد عفيف منفق الدين هامبالي', 'فاست', '56656', 'Indonesia', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_57083_فاست', 'Worker', 'محمد قيس مطيع الرحمن', 'فاست', '57083', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_58578_فاست', 'Worker', 'اخلاق احمد والي محمد', 'فاست', '58578', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_58596_فاست', 'Worker', 'اديب فياض فياض احمد', 'فاست', '58596', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_58634_فاست', 'Worker', 'مصور خان موسى خان', 'فاست', '58634', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_58848_فاست', 'Worker', 'مدحت سيد احمد نورالدين', 'فاست', '58848', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59179_فاست', 'Worker', 'اصف نعيم', 'فاست', '59179', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59183_فاست', 'Worker', 'منصور علي شاه مرادعلي شاه', 'فاست', '59183', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59189_فاست', 'Worker', 'جعفر علي فراز خان', 'فاست', '59189', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59191_فاست', 'Worker', 'محمد عدنان نور محمد', 'فاست', '59191', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59236_فاست', 'Worker', 'عاشق محمود فايز علي', 'فاست', '59236', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59262_فاست', 'Worker', 'مبارك   عبد المنان', 'فاست', '59262', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59290_فاست', 'Worker', 'محمد بابو تلي', 'فاست', '59290', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59295_فاست', 'Worker', 'زيشان عمر حياة', 'فاست', '59295', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59300_فاست', 'Worker', 'نصير احمد جميل', 'فاست', '59300', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59303_فاست', 'Worker', 'محمد ارباز خان', 'فاست', '59303', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59337_فاست', 'Worker', 'سلمان خان', 'فاست', '59337', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_59350_فاست', 'Worker', 'شهباز خان', 'فاست', '59350', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_60564_بريمكو', 'Worker', 'محمد فاروق مبارك', 'بريمكو', '60564', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_60891_بريمكو', 'Worker', 'خالدكمال عبد الجواد', 'بريمكو', '60891', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61016_بريمكو', 'Worker', 'شحاته حسن أحمد شحاته', 'بريمكو', '61016', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61025_بريمكو', 'Worker', 'السيد جمعة ابراهيم', 'بريمكو', '61025', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61097_بريمكو', 'Worker', 'جاكير كودجا', 'بريمكو', '61097', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61307_بريمكو', 'Worker', 'محمد ايوب  فخرالدين', 'بريمكو', '61307', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61799_بريمكو', 'Worker', 'باسط خان', 'بريمكو', '61799', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_61814_بريمكو', 'Worker', 'جهانقير خان', 'بريمكو', '61814', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_63091_بريمكو', 'Worker', 'محمد عقيل محمد', 'بريمكو', '63091', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_63321_بريمكو', 'Worker', 'صبحى صبحى محمد الساعى', 'بريمكو', '63321', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, employee_id, nationaliy, id_number, transfer_destination, status, company) VALUES ('w_emp_63503_بريمكو', 'Worker', 'ابراهيم ابراهيم احمد', '63503', 'Egypt', '', NULL, 'Active', 'PREMCO');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_63836_بريمكو', 'Worker', 'توفيق محمد توفيق', 'بريمكو', '63836', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_64117_بريمكو', 'Worker', 'محمد شبير صابر فروش', 'بريمكو', '64117', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_64162_بريمكو', 'Worker', 'محمد فاروق علي خان', 'بريمكو', '64162', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, transfer_destination, status) VALUES ('w_emp_64359_بريمكو', 'Worker', 'نبيل محمد ابو', 'بريمكو', '64359', 'Egypt', '', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_64854_بريمكو', 'Worker', 'طارق مسود محمد مسود', 'بريمكو', '64854', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_65088_بريمكو', 'Worker', 'محمد ساكير', 'بريمكو', '65088', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_65172_بريمكو', 'Worker', 'صابر عبد الباسط محمد هريدي', 'بريمكو', '65172', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_65268_بريمكو', 'Worker', 'مصباح محمد عبد الجليل اسماعيل', 'بريمكو', '65268', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_65393_بريمكو', 'Worker', 'اسرار على شاه', 'بريمكو', '65393', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_65520_بريمكو', 'Worker', 'عبدالرؤوف قاضي', 'بريمكو', '65520', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_66348_بريمكو', 'Worker', 'امتياز حسين محمد اكرم', 'بريمكو', '66348', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_66352_بريمكو', 'Worker', 'طاهر عزيز', 'بريمكو', '66352', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_66681_بريمكو', 'Worker', 'مشتاق علي خان', 'بريمكو', '66681', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_67298_بريمكو', 'Worker', 'جاويد إقبال غلام', 'بريمكو', '67298', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_67741_بريمكو', 'Worker', 'JAFFAR HUSSAIN', 'بريمكو', '67741', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_68316_بريمكو', 'Worker', 'عبد الكبير علاء الدين', 'بريمكو', '68316', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_68323_بريمكو', 'Worker', 'ظهير خان محمد رفيق', 'بريمكو', '68323', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_68444_بريمكو', 'Worker', 'غني رحمن عزيز الرحمن', 'بريمكو', '68444', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_68553_بريمكو', 'Worker', 'مصطفى ابراهيم احمد صالحين', 'بريمكو', '68553', 'Egypt', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_68651_بريمكو', 'Worker', 'مصطفى صالح محسن محمد زياد', 'بريمكو', '68651', 'Yemen', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_69329_بريمكو', 'Worker', 'راجو بيسيتاي عبدال منان', 'بريمكو', '69329', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_7004339_ABCD-جامعه_و_حرس', 'Worker', 'محمد نعيم تاج بهادر', 'ABCD-جامعه و حرس', '7004339', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_7011677_ABCD-جامعه_و_حرس', 'Worker', 'جوبيل علي محمد أيوب', 'ABCD-جامعه و حرس', '7011677', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_7012997_ABCD-جامعه_و_حرس', 'Worker', 'عمران محمد اقبال', 'ABCD-جامعه و حرس', '7012997', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_70167_بريمكو', 'Worker', 'اسماعيل علي', 'بريمكو', '70167', 'Yemen', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_70552_بريمكو', 'Worker', 'عارف على عاشق', 'بريمكو', '70552', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_70840_بريمكو', 'Worker', 'احمد عبدالكريم محمد', 'بريمكو', '70840', 'Egypt', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_emp_71389_بريمكو', 'Worker', 'حاميد سليم', 'بريمكو', '71389', 'Yemen', '', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_71522_بريمكو', 'Worker', 'محمد أصنف محمد', 'بريمكو', '71522', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_71526_بريمكو', 'Worker', 'مصطفي كمال زمين', 'بريمكو', '71526', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9340549_ABCD-جامعه_و_حرس', 'Worker', 'عمران خان بابو خان', 'ABCD-جامعه و حرس', '9340549', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9340713_ABCD-جامعه_و_حرس', 'Worker', 'ياسين   خان', 'ABCD-جامعه و حرس', '9340713', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9340860_ABCD-جامعه_و_حرس', 'Worker', 'جواد أختر', 'ABCD-جامعه و حرس', '9340860', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9341662_ABCD-جامعه_و_حرس', 'Worker', 'محمد ساجد', 'ABCD-جامعه و حرس', '9341662', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9341717_ABCD-جامعه_و_حرس', 'Worker', 'محمد عباس', 'ABCD-جامعه و حرس', '9341717', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9342590_ABCD-جامعه_و_حرس', 'Worker', 'محمد عاصف  محمد', 'ABCD-جامعه و حرس', '9342590', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9343756_ABCD-جامعه_و_حرس', 'Worker', 'أفتاب علم ممتاز علي', 'ABCD-جامعه و حرس', '9343756', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9343999_ABCD-جامعه_و_حرس', 'Worker', 'دانيش ظفر  شكيل', 'ABCD-جامعه و حرس', '9343999', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9344282_ABCD-جامعه_و_حرس', 'Worker', 'محمد جيشان  ايوب', 'ABCD-جامعه و حرس', '9344282', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9344339_ABCD-جامعه_و_حرس', 'Worker', 'محمد رئيس محمد يونس', 'ABCD-جامعه و حرس', '9344339', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9344604_ABCD-جامعه_و_حرس', 'Worker', 'عليم هاشم', 'ABCD-جامعه و حرس', '9344604', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9344630_ABCD-جامعه_و_حرس', 'Worker', 'صدام خان شاكر خان', 'ABCD-جامعه و حرس', '9344630', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9345087_ABCD-جامعه_و_حرس', 'Worker', 'محمد عبيد البسيطي', 'ABCD-جامعه و حرس', '9345087', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9346487_ABCD-جامعه_و_حرس', 'Worker', 'محمد فرهاد علي', 'ABCD-جامعه و حرس', '9346487', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9346525_ABCD-جامعه_و_حرس', 'Worker', 'محمد روبيول شيخ', 'ABCD-جامعه و حرس', '9346525', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9346549_ABCD-جامعه_و_حرس', 'Worker', 'سوبوس ميا', 'ABCD-جامعه و حرس', '9346549', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9346617_ABCD-جامعه_و_حرس', 'Worker', 'محمد حامد شكدار', 'ABCD-جامعه و حرس', '9346617', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9346943_ABCD-جامعه_و_حرس', 'Worker', 'محمد حافظ أكوندو', 'ABCD-جامعه و حرس', '9346943', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9347205_ABCD-جامعه_و_حرس', 'Worker', 'محمد عزير رياض محمد رياض', 'ABCD-جامعه و حرس', '9347205', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9347708_ABCD-جامعه_و_حرس', 'Worker', 'زرياب علي محمد رمضان', 'ABCD-جامعه و حرس', '9347708', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9348311_ABCD-جامعه_و_حرس', 'Worker', 'وحيد خان امير حيد', 'ABCD-جامعه و حرس', '9348311', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9348339_ABCD-جامعه_و_حرس', 'Worker', 'عبدالله شاه مسعود شاه', 'ABCD-جامعه و حرس', '9348339', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9348695_ABCD-جامعه_و_حرس', 'Worker', 'محمد راشد', 'ABCD-جامعه و حرس', '9348695', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9349891_ABCD-جامعه_و_حرس', 'Worker', 'محمد أمير طاهر طاهر', 'ABCD-جامعه و حرس', '9349891', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9350227_ABCD-جامعه_و_حرس', 'Worker', 'ميرزا علي جبران محمد رمضان', 'ABCD-جامعه و حرس', '9350227', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9350525_ABCD-جامعه_و_حرس', 'Worker', 'محمد ياسر محمد طيف علي', 'ABCD-جامعه و حرس', '9350525', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9351058_ABCD-جامعه_و_حرس', 'Worker', 'محبوب رمضان محمد رمضان', 'ABCD-جامعه و حرس', '9351058', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9351433_ABCD-جامعه_و_حرس', 'Worker', 'جافيد خان', 'ABCD-جامعه و حرس', '9351433', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9351535_ABCD-جامعه_و_حرس', 'Worker', 'محمد عظيم محمد خليل', 'ABCD-جامعه و حرس', '9351535', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9352386_ABCD-جامعه_و_حرس', 'Worker', 'محمد  ريبون ميا', 'ABCD-جامعه و حرس', '9352386', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9352713_ABCD-جامعه_و_حرس', 'Worker', 'محمد إبراهيم حسين', 'ABCD-جامعه و حرس', '9352713', 'Bangladesh', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9354163_ABCD-جامعه_و_حرس', 'Worker', 'ساجد علي محمد اسلم', 'ABCD-جامعه و حرس', '9354163', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9355350_ABCD-جامعه_و_حرس', 'Worker', 'مبشر علي بكار علي', 'ABCD-جامعه و حرس', '9355350', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9355854_ABCD-جامعه_و_حرس', 'Worker', 'رحيم خان نظير احمد', 'ABCD-جامعه و حرس', '9355854', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9355868_ABCD-جامعه_و_حرس', 'Worker', 'محمد قمران محمد اصغر', 'ABCD-جامعه و حرس', '9355868', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9356433_ABCD-جامعه_و_حرس', 'Worker', 'محمد أرشد علي', 'ABCD-جامعه و حرس', '9356433', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9356583_ABCD-جامعه_و_حرس', 'Worker', 'أكمل عزيز نهال صغير', 'ABCD-جامعه و حرس', '9356583', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9357080_ABCD-جامعه_و_حرس', 'Worker', 'زوهيب ارشد محمد انور', 'ABCD-جامعه و حرس', '9357080', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9357324_ABCD-جامعه_و_حرس', 'Worker', 'محمد عرفان', 'ABCD-جامعه و حرس', '9357324', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9361045_ABCD-جامعه_و_حرس', 'Worker', 'عرفان علي', 'ABCD-جامعه و حرس', '9361045', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9361800_ABCD-جامعه_و_حرس', 'Worker', 'اسد اللہ خالد محمود', 'ABCD-جامعه و حرس', '9361800', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9363765_ABCD-جامعه_و_حرس', 'Worker', 'عامر وحيد غلام رسول', 'ABCD-جامعه و حرس', '9363765', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9365535_ABCD-جامعه_و_حرس', 'Worker', 'محمد عديل', 'ABCD-جامعه و حرس', '9365535', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9380221_ABCD-جامعه_و_حرس', 'Worker', 'هاشم شاه محمد', 'ABCD-جامعه و حرس', '9380221', 'Indian', '');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_emp_9380988_ABCD-جامعه_و_حرس', 'Worker', 'محمد زاهد محمد إقبال', 'ABCD-جامعه و حرس', '9380988', 'Pakistan', '');
INSERT OR REPLACE INTO workers (id, role, company, nationaliy, id_number, name, employee_id) VALUES ('w_iq_0', 'Worker', 'شركة البدر', 'Bangladesh', '0', 'SIDUL ISLAM', '2592801407');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_1000888782', 'Supervisor', 'Trahib Khnaifis Alqurashi', 'SACODECO', '38218', 'Saudi', '1000888782');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_1071185076', 'Worker', 'محمد رمضان سيد', 'بريمكو', '39213', 'Pakistan', '1071185076');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_1099907055', 'Worker', 'امين الله خان سامي الله', 'فاست', '39388', 'Pakistan', '1099907055');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2020581357', 'Worker', 'محمد حكيم خان', 'بريمكو', '61407', 'Indian', '2020581357');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2036689970', 'Worker', 'Afsar Ali  Shakir', 'SACODECO', '27007', 'Indian', '2036689970');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2040281418', 'Worker', 'Abdulhamed     Mohammedsadik', 'SACODECO', '27916', 'Indian', '2040281418');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2048441915', 'Worker', 'Mohammed Salim Mohammed Habib', 'SACODECO', '14871', 'Indian', '2048441915');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2049417609', 'Worker', 'Mohammeddin     Khan', 'SACODECO', '4623', 'Indian', '2049417609');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2051531453', 'Worker', 'Farooqa     Ahmed', 'SACODECO', '12883', 'Indian', '2051531453');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2055181719', 'Supervisor', 'Kadri Mohamed Salama', 'SACODECO', '27560', 'Egypt', '2055181719');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2058379435', 'Worker', 'Sabir     Ali', 'SACODECO', '27011', 'Indian', '2058379435');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2058888708', 'Worker', 'Moinuddin     Kayam', 'SACODECO', '15287', 'Indian', '2058888708');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2059313862', 'Worker', 'Bhanwar Ali Chan Mohammed', 'SACODECO', '15124', 'Indian', '2059313862');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, transfer_destination, status) VALUES ('w_iq_2059537999', 'Supervisor', 'Mohammed Hassan Ali Alabdali', 'SACODECO', '40097', 'Yemen', '2059537999', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2061360943', 'Worker', 'Mohammed Faruq   Bisauti', 'SACODECO', '15146', 'Indian', '2061360943');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2063798926', 'Worker', 'Khalid Mahmood Ahmed Khan', 'SACODECO', '6616', 'Pakistan', '2063798926');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2063842617', 'Supervisor', 'Mohammed Rafiq  Mohammed Yasin', 'SACODECO', '49852', 'Indian', '2063842617');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2064271063', 'Worker', 'Mohammed Qasem Rasool Miah', 'SACODECO', '27163', 'Indian', '2064271063');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2065780260', 'Worker', 'Chaudary Mohammed   Nanif', 'SACODECO', '7163', 'Pakistan', '2065780260');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2066496643', 'Supervisor', 'Mohammed Farooq Mustaq   Qazi', 'SACODECO', '16218', 'Indian', '2066496643');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2067118519', 'Supervisor', 'Arshadshah     Ahmedshah', 'SACODECO', '14861', 'Pakistan', '2067118519');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2072538529', 'Worker', 'Mohammadjabbar     Mirdad', 'SACODECO', '9285', 'Pakistan', '2072538529');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2072864495', 'Worker', 'Saleem     Akhtar', 'SACODECO', '9746', 'Pakistan', '2072864495');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2072867506', 'Worker', 'Syedaebed   Hussin', 'SACODECO', '9755', 'Pakistan', '2072867506');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2075409736', 'Worker', 'Coskun   Simsek', 'SACODECO', '9735', 'Turkey', '2075409736');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2077138853', 'Worker', 'Aish Mohammad   Khurshedali', 'SACODECO', '10585', 'Indian', '2077138853');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2083666202', 'Worker', 'Munawar Ali   Kazi', 'SACODECO', '27911', 'Indian', '2083666202');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2087727182', 'Worker', 'Khurshid     Khan', 'SACODECO', '12286', 'Pakistan', '2087727182');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2096815911', 'Worker', 'Faqure Alam Iliyas Khan', 'SACODECO', '14207', 'Indian', '2096815911');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2096833468', 'Supervisor', 'Ali     Sher', 'SACODECO', '14124', 'Indian', '2096833468');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2097370510', 'Supervisor', 'Imkan Ahmad   Khan', 'SACODECO', '14072', 'Indian', '2097370510');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2097371922', 'Supervisor', 'Mohammedyusuf     Kazi', 'SACODECO', '28482', 'Indian', '2097371922');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2097372078', 'Supervisor', 'Manir     Alam', 'SACODECO', '14114', 'Indian', '2097372078');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2097377846', 'Supervisor', 'Mohammad Rafik   Khan', 'SACODECO', '14185', 'Indian', '2097377846');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2113500314', 'Worker', 'Shaaban Shalabi Mohd', 'SACODECO', '19306', 'Egypt', '2113500314');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2114816453', 'Worker', 'Shahid     Faqirhaydar', 'SACODECO', '15221', 'Pakistan', '2114816453');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2114822790', 'Supervisor', 'Nadeem Muhammad   Yousaf', 'SACODECO', '15271', 'Pakistan', '2114822790');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2114823053', 'Worker', 'Mohammed Afzaal Ghulam Qadar', 'SACODECO', '6382', 'Pakistan', '2114823053');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115391720', 'Supervisor', 'Zamirhassan     Tufailhussain', 'SACODECO', '15404', 'Pakistan', '2115391720');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115391845', 'Worker', 'Riaz Ghani  Usmanuddin', 'SACODECO', '15401', 'Pakistan', '2115391845');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115732352', 'Worker', 'Wasidali     Abubakar', 'SACODECO', '15472', 'Indian', '2115732352');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115732394', 'Worker', 'Mushirahmad Khan   Nasibuddin', 'SACODECO', '15424', 'Indian', '2115732394');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115740934', 'Worker', 'Gulamahmad     Khan', 'SACODECO', '15460', 'Indian', '2115740934');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2115741155', 'Worker', 'Imran Ahmad   Khan', 'SACODECO', '11051', 'Indian', '2115741155');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, transfer_destination, status) VALUES ('w_iq_2116333028', 'Supervisor', 'Niyaz Ahmad  Khan', 'SACODECO', '11064', 'Indian', '2116333028', NULL, 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2116399490', 'Worker', 'Mukhtar Ahmad Jaleel Ahmad Khan', 'SACODECO', '14358', 'Indian', '2116399490');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2116454501', 'Worker', 'Sabrulhasan     Khan', 'SACODECO', '15449', 'Indian', '2116454501');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2117062345', 'Supervisor', 'افتخار أحمد  بختي خان', 'SACODECO', '15616', 'Pakistan', '2117062345');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2117080875', 'Worker', 'Sajjad Ahmed Ghulam Rasuool', 'SACODECO', '15790', 'Pakistan', '2117080875');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2117300026', 'Worker', 'Khalidhussain     Ashrf', 'SACODECO', '15723', 'Pakistan', '2117300026');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2118030218', 'Worker', 'تجمل حسين محمد افظل', 'SACODECO', '15622', 'Pakistan', '2118030218');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2120315656', 'Worker', 'Fakrulislam     Mujammil Ali', 'SACODECO', '27008', 'Bangladesh', '2120315656');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2121468363', 'Worker', 'Afzalahmedkhan     Abdurrahman', 'SACODECO', '15942', 'Indian', '2121468363');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2125168266', 'Supervisor', 'Salem Abdulhalim Abouassi', 'SACODECO', '43086', 'Egypt', '2125168266');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2126734108', 'Supervisor', 'Mohammed Nafeeq Khan Mohammad Rafiq Khan', 'SACODECO', '16970', 'Pakistan', '2126734108');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number, status) VALUES ('w_iq_2127000111', 'Worker', 'Abdulbarik     Abdulishalul', 'SACODECO', '17216', 'Bangladesh', '2127000111', 'Active');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2128805393', 'Worker', 'Aseedahmad     Khan', 'SACODECO', '17759', 'Indian', '2128805393');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2128805898', 'Supervisor', 'Khan     Mukhtarahmed', 'SACODECO', '17754', 'Indian', '2128805898');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2129577827', 'Worker', 'Moziburahman     Mohammedfarid', 'SACODECO', '26675', 'Bangladesh', '2129577827');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2129602674', 'Worker', 'Alaluddin     Babrumiah', 'SACODECO', '26677', 'Bangladesh', '2129602674');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2131691350', 'Supervisor', 'Ali Kadir', 'SACODECO', '45605', 'Indian', '2131691350');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2131693661', 'Worker', 'Ansari     Razzaque', 'SACODECO', '18406', 'Indian', '2131693661');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2131956167', 'Worker', 'Kunjara     Sharif', 'SACODECO', '28158', 'Indian', '2131956167');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2132076148', 'Worker', 'Mohamad     Amiruddin', 'SACODECO', '18569', 'Indian', '2132076148');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2132656527', 'Worker', 'Momin Khan Gul Zada', 'SACODECO', '18915', 'Pakistan', '2132656527');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2133407078', 'Worker', 'Babu     Salam', 'SACODECO', '28007', 'Indian', '2133407078');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2133407722', 'Supervisor', 'Raisath     Kahnh', 'SACODECO', '27813', 'Indian', '2133407722');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2136306947', 'Worker', 'Tajmohamed     Hirachaudhary', 'SACODECO', '28029', 'Indian', '2136306947');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2138200908', 'Worker', 'Rwh Alamen Mohamemd Akram', 'SACODECO', '26680', 'Pakistan', '2138200908');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2138271966', 'Worker', 'Mohammed Intajar   Ali', 'SACODECO', '27893', 'Indian', '2138271966');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2139925982', 'Worker', 'Liaquat Ali   Malkmanqua', 'SACODECO', '20858', 'Pakistan', '2139925982');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2142877543', 'Worker', 'Shabbir Hussain Muhammad Irshad', 'SACODECO', '15659', 'Pakistan', '2142877543');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2144316425', 'Worker', 'نواجز سرور محمد سروار', 'بريمكو', '60319', 'Pakistan', '2144316425');
INSERT OR REPLACE INTO workers (id, role, name, company, employee_id, nationaliy, id_number) VALUES ('w_iq_2151121387', 'Worker', 'محمد أنيس سيد', 'بريمكو', '61391', 'Indian', '2151121387');
