name = "estatecare-studio"
compatibility_date = "2024-04-03"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

# Replace with your Cloudflare Account ID


[[d1_databases]]
binding = "DB"
database_name = "estatecare-d1"
database_id = "079529e2-33da-4127-ac5f-c1c0b641155c"
migrations_dir = "drizzle/migrations"

# Optional: environment vars for pages / preview envs
[vars]
# STORAGE_PATH can be set here or via your deploy platform secrets
STORAGE_PATH = "/var/estatecare/storage"

[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "estatecare-storage"
