
import React from 'react';
import { Button } from "@/components/ui/button";
import { Printer, ArrowLeft } from "lucide-react";
import { useRouter } from 'next/navigation';

interface PrintLayoutProps {
  title: string;
  description?: string;
  children: React.ReactNode;
  onPrint?: () => void;
}

export function PrintLayout({ title, description, children, onPrint }: PrintLayoutProps) {
  const router = useRouter();
  
  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 p-4 md:p-8 print:p-0 print:bg-white">
      {/* Toolbar */}
      <div className="max-w-[210mm] mx-auto mb-6 flex justify-between items-center print:hidden">
        <Button variant="ghost" onClick={() => router.back()} className="gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back
        </Button>
        <div className="flex gap-2">
          <Button onClick={handlePrint} className="gap-2">
            <Printer className="h-4 w-4" />
            Print Report
          </Button>
        </div>
      </div>

      {/* A4 Paper Simulation */}
      <div className="max-w-[210mm] mx-auto bg-white text-black shadow-lg print:shadow-none print:w-full min-h-[297mm] p-[15mm] print:p-0 rounded-sm">
        
        {/* Report Header */}
        <div className="border-b-2 border-gray-800 pb-6 mb-8">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 uppercase tracking-tight">{title}</h1>
              {description && <p className="text-gray-500 mt-1 text-sm">{description}</p>}
            </div>
            <div className="text-right">
              <div className="text-2xl font-bold text-gray-900">EstateCare</div>
              <div className="text-sm text-gray-500 uppercase tracking-wider">Studio System</div>
            </div>
          </div>
          <div className="mt-6 flex justify-between text-sm text-gray-600">
            <div>
              <span className="font-semibold text-gray-900">Date:</span> {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </div>
            <div>
              <span className="font-semibold text-gray-900">Generated By:</span> System Admin
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="report-content">
          {children}
        </div>

        {/* Report Footer */}
        <div className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-400 print:fixed print:bottom-4 print:left-0 print:right-0">
          <p>EstateCare Studio &copy; {new Date().getFullYear()} - Confidential Internal Document</p>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          @page {
            margin: 15mm;
            size: A4;
          }
          body {
            background: white;
            color: black;
          }
          /* Force light mode colors for printing */
          .report-content table {
            width: 100%;
            border-collapse: collapse;
          }
          .report-content th {
            background-color: #f3f4f6 !important;
            color: #111827 !important;
            border-bottom: 2px solid #000 !important;
            font-weight: bold;
            text-align: left;
            padding: 8px;
          }
          .report-content td {
            border-bottom: 1px solid #e5e7eb !important;
            padding: 8px;
            color: #000 !important;
          }
          .report-content tr:last-child td {
            border-bottom: none;
          }
        }
        
        /* Screen styles for the report content to look good on "paper" */
        .report-content table {
          width: 100%;
        }
        .report-content th {
          text-align: left;
          padding: 0.75rem;
          font-weight: 600;
          color: #111827;
          border-bottom: 2px solid #e5e7eb;
        }
        .report-content td {
          padding: 0.75rem;
          border-bottom: 1px solid #e5e7eb;
          color: #374151;
        }
      `}</style>
    </div>
  );
}
