"use client";

import React, { useState, useMemo, useRef, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAccommodation, Worker, AccommodationHistory } from '@/context/accommodation-context';
import { useLanguage } from '@/context/language-context';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import {
  Search,
  Printer,
  User,
  Building2,
  MapPin,
  Calendar,
  Clock,
  LogIn,
  LogOut,
  ArrowRightLeft,
  Repeat2,
  FileText,
  Hash,
  Globe,
  Briefcase,
  Building,
  IdCard,
  CheckCircle2,
  Home,
  TrendingUp,
  AlertCircle,
  MoreHorizontal,
  Layers,
  DoorOpen
} from 'lucide-react';
import { format } from 'date-fns';
import { ar, enUS } from 'date-fns/locale';

// Translation keys
const translations = {
  en: {
    pageTitle: 'Worker Accommodation Certificate',
    pageDescription: 'View complete worker data and accommodation status',
    searchPlaceholder: 'Search by name, ID number, or employee number...',
    search: 'Search',
    searching: 'Searching...',
    searchResults: 'Search Results',
    selectAnotherWorker: 'Select Another Worker',
    printCertificate: 'Print Certificate',
    workerData: 'Worker Information',
    fullName: 'Full Name',
    idNumber: 'ID Number',
    employeeNumber: 'Employee Number',
    nationality: 'Nationality',
    jobTitle: 'Job Title',
    company: 'Company',
    notRegistered: 'N/A',
    notSpecified: 'N/A',
    worker: 'Worker',
    supervisor: 'Supervisor',
    engineer: 'Engineer',
    active: 'Active',
    transferring: 'Transferring',
    vacation: 'Vacation',
    exit: 'Exit',
    currentStatus: 'Current Status',
    currentlyAccommodated: 'Currently Accommodated',
    notCurrentlyAccommodated: 'Not Accommodated',
    accommodationLocation: 'Location',
    roomNumber: 'Room',
    city: 'City',
    housing: 'Housing',
    building: 'Building',
    floor: 'Floor',
    room: 'Room',
    checkInDate: 'Check-in',
    stayDuration: 'Duration',
    days: 'days',
    day: 'day',
    summary: 'Summary',
    checkIns: 'Check-ins',
    checkOuts: 'Check-outs',
    transfers: 'Swaps',
    totalDays: 'Total Days',
    recentHistory: 'Recent Movement History',
    moreRecords: 'more records',
    checkIn: 'Check In',
checkOut: 'Out',
    checkIn: 'In',
    checkInNotes: 'Check-in Notes',
    checkOutNotes: 'Check-out Notes',
    transfer: 'Swap',
    swap: 'Swap',
    from: 'From',
    to: 'To',
    certificateTitle: 'WORKER ACCOMMODATION CERTIFICATE',
    certificateSubtitle: 'Official Housing Status Document',
    issueDate: 'Issue Date',
    documentNo: 'Document No',
    signature: 'Authorized Signature',
    stamp: 'Official Stamp',
    generatedBy: 'Generated by Accommodation Management System',
    emptyStateTitle: 'Worker Certificate',
    emptyStateDescription: 'Search for a worker to generate their accommodation certificate',
    workerInfo: 'Worker Info',
    accommodationStatus: 'Status',
    history: 'History',
  },
  ar: {
    pageTitle: 'إفادة سكن موظف',
    pageDescription: 'استعراض بيانات الموظف الكاملة وحالته السكنية',
    searchPlaceholder: 'ابحث بالاسم أو رقم الهوية أو الرقم الوظيفي...',
    search: 'بحث',
    searching: 'جاري البحث...',
    searchResults: 'نتائج البحث',
    selectAnotherWorker: 'اختيار موظف آخر',
    printCertificate: 'طباعة الإفادة',
    workerData: 'بيانات الموظف',
    fullName: 'الاسم',
    idNumber: 'رقم الهوية',
    employeeNumber: 'الرقم الوظيفي',
    nationality: 'الجنسية',
    jobTitle: 'المسمى',
    company: 'الشركة',
    notRegistered: 'غ/م',
    notSpecified: 'غ/م',
    worker: 'عامل',
    supervisor: 'مشرف',
    engineer: 'مهندس',
    active: 'نشط',
    transferring: 'قيد النقل',
    vacation: 'إجازة',
    exit: 'خارج',
    currentStatus: 'الحالة الحالية',
    currentlyAccommodated: 'مُسكّن حالياً',
    notCurrentlyAccommodated: 'غير مُسكّن',
    accommodationLocation: 'الموقع',
    roomNumber: 'الغرفة',
    city: 'المدينة',
    housing: 'المسكن',
    building: 'المبنى',
    floor: 'الطابق',
    room: 'الغرفة',
    checkInDate: 'تاريخ التسكين',
    stayDuration: 'المدة',
    days: 'يوم',
    day: 'يوم',
    summary: 'ملخص',
    checkIns: 'تسكين',
    checkOuts: 'إخراج',
    transfers: 'تبديلات',
    totalDays: 'إجمالي الأيام',
    recentHistory: 'سجل الحركات الأخيرة',
    moreRecords: 'سجلات إضافية',
    checkIn: 'تسكين',
    checkOut: 'إخراج',
    checkInNotes: 'ملاحظات التسكين',
    checkOutNotes: 'ملاحظات الإخراج',
    transfer: 'تبديل',
    swap: 'تبديل',
    from: 'من',
    to: 'إلى',
    certificateTitle: 'إفادة سكن موظف',
    certificateSubtitle: 'مستند رسمي لحالة السكن',
    issueDate: 'تاريخ الإصدار',
    documentNo: 'رقم المستند',
    signature: 'توقيع المسؤول',
    stamp: 'الختم الرسمي',
    generatedBy: 'صادر من نظام إدارة السكن',
    emptyStateTitle: 'إفادة سكن موظف',
    emptyStateDescription: 'ابحث عن موظف لإصدار إفادة السكن الخاصة به',
    workerInfo: 'البيانات',
    accommodationStatus: 'الحالة',
    history: 'السجل',
  }
};

export default function WorkerCertificatePage() {
  const { locale } = useLanguage();
  const t = translations[locale] || translations.en;
  const dateLocale = locale === 'ar' ? ar : enUS;
  const isRTL = locale === 'ar';

  const searchParams = useSearchParams();
  const workerIdFromQuery = searchParams.get('workerId');

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedWorker, setSelectedWorker] = useState<Worker | null>(null);
  const [searchResults, setSearchResults] = useState<Worker[]>([]);
  const [loading, setLoading] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [workerHistory, setWorkerHistory] = useState<AccommodationHistory[]>([]);

  const {
    findWorkerAsync,
    fetchWorkerHistory,
    occupants,
    residences,
    companies,
    getWorkerByIdOrEmployeeId
  } = useAccommodation();

  useEffect(() => {
    const fetchByWorkerId = async () => {
      if (workerIdFromQuery && !selectedWorker) {
        setLoading(true);
        try {
          const worker = await getWorkerByIdOrEmployeeId(workerIdFromQuery);
          if (worker) {
            setSelectedWorker(worker);
            setSearchResults([]);
            setSearchQuery('');
            setHistoryLoading(true);
            try {
              const history = await fetchWorkerHistory(worker.id);
              setWorkerHistory(history);
            } finally {
              setHistoryLoading(false);
            }
          }
        } finally {
          setLoading(false);
        }
      }
    };
    fetchByWorkerId();
  }, [workerIdFromQuery, getWorkerByIdOrEmployeeId]);

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;
    setLoading(true);
    try {
      const results = await findWorkerAsync(searchQuery);
      setSearchResults(results);
    } catch (error) {
      console.error('Search error:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectWorker = async (worker: Worker) => {
    setSelectedWorker(worker);
    setSearchResults([]);
    setSearchQuery('');
    setHistoryLoading(true);
    try {
      const history = await fetchWorkerHistory(worker.id);
      setWorkerHistory(history);
    } catch (error) {
      console.error('Error loading history:', error);
    } finally {
      setHistoryLoading(false);
    }
  };

  const currentOccupancy = useMemo(() => {
    if (!selectedWorker) return null;
    return occupants.find(o => o.workerId === selectedWorker.id && !o.until);
  }, [occupants, selectedWorker]);

  const getResidenceName = (residenceId: string) => {
    return residences.find(r => r.id === residenceId)?.name || residenceId;
  };

  const getRoomFullPath = (residenceId: string, roomId: string) => {
    const residence = residences.find(r => r.id === residenceId);
    if (!residence) return { city: '', housing: '', building: '', floor: '', room: roomId, fullPath: roomId };

    const city = residence.city || '';
    const housing = residence.name || '';

    if (residence.buildings) {
      for (const building of residence.buildings) {
        for (const floor of building.floors || []) {
          const room = floor.rooms?.find(r => r.id === roomId);
          if (room) {
            return {
              city,
              housing,
              building: building.name || '',
              floor: floor.name || '',
              room: room.name || roomId,
              fullPath: [building.name, floor.name, room.name].filter(Boolean).join(' > ') || roomId
            };
          }
        }
      }
    }

    if (residence.rooms) {
      const room = residence.rooms.find(r => r.id === roomId);
      if (room?.name) return { city, housing, building: '', floor: '', room: room.name, fullPath: room.name };
    }

    return { city, housing, building: '', floor: '', room: roomId, fullPath: roomId };
  };

  const getCompanyName = (companyName?: string) => {
    if (!companyName) return t.notSpecified;
    const company = companies.find(c =>
      c.name === companyName || c.nameAr === companyName || c.nameEn === companyName
    );
    if (locale === 'ar') {
      return company?.nameAr || company?.name || companyName;
    }
    return company?.nameEn || company?.name || companyName;
  };

  const stats = useMemo(() => {
    const checkIns = workerHistory.filter(h => h.actionType === 'CHECK_IN').length;
    const checkOuts = workerHistory.filter(h => h.actionType === 'CHECK_OUT').length;
    const swaps = workerHistory.filter(h => h.actionType === 'TRANSFER' || h.actionType === 'SWAP').length;

    let totalDays = 0;
    const sortedHistory = [...workerHistory].sort((a, b) =>
      new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime()
    );

    let lastCheckInDate: Date | null = null;

    for (const record of sortedHistory) {
      if (record.actionType === 'CHECK_IN') {
        lastCheckInDate = new Date(record.actionDate);
        lastCheckInDate.setHours(0, 0, 0, 0);
      } else if (record.actionType === 'CHECK_OUT' && lastCheckInDate) {
        const checkOutDate = new Date(record.actionDate);
        checkOutDate.setHours(0, 0, 0, 0);
        const diffTime = checkOutDate.getTime() - lastCheckInDate.getTime();
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        totalDays += Math.max(diffDays + 1, 1);
        lastCheckInDate = null;
      }
    }

    if (currentOccupancy) {
      const sinceDate = new Date(currentOccupancy.since);
      const today = new Date();
      sinceDate.setHours(0, 0, 0, 0);
      today.setHours(0, 0, 0, 0);
      const diffTime = today.getTime() - sinceDate.getTime();
      const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      totalDays += diffDays + 1;
    }

    return { checkIns, checkOuts, swaps, totalDays };
  }, [workerHistory, currentOccupancy]);

  const groupedHistory = useMemo(() => {
    const asc = [...workerHistory].slice().sort((a, b) => new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime());
    const groups: Array<any> = [];
    let i = 0;
    while (i < asc.length) {
      const cur = asc[i];
      if (cur.actionType === 'CHECK_IN') {
        let j = i + 1;
        while (j < asc.length && asc[j].actionType !== 'CHECK_OUT') j++;
        if (j < asc.length) {
          groups.push({ type: 'period', items: asc.slice(i, j + 1) });
          i = j + 1;
        } else {
          groups.push({ type: 'period', items: asc.slice(i) });
          break;
        }
      } else {
        groups.push({ type: 'single', item: cur });
        i += 1;
      }
    }
    return groups;
  }, [workerHistory]);

  function getCheckoutLabel(checkoutType?: string | null) {
    if (!checkoutType) return null;
    const label = checkoutType;
    if (checkoutType === 'Transfer' || checkoutType === 'Swap') {
      return t.transfer;
    }
    if (locale === 'ar') {
      if (checkoutType === 'Exit') return 'خروج';
      else if (checkoutType === 'Vacation') return 'إجازة';
    }
    return label;
  }

  const summarizedHistory = useMemo(() => {
    const summaries: Array<any> = [];
    const fmtResidence = (rName?: string, roomName?: string, rId?: string, rmId?: string) => {
      let finalRName = rName;
      let finalRoomName = roomName;

      if (!finalRName && rId) {
        finalRName = getResidenceName(rId);
      }
      if (!finalRoomName && rId && rmId) {
        finalRoomName = getRoomFullPath(rId, rmId).room;
      }

      return finalRName ? (finalRoomName ? `${finalRName} • ${finalRoomName}` : finalRName) : t.notSpecified;
    };

    for (const g of groupedHistory) {
      if (g.type === 'single') {
        const item = g.item as AccommodationHistory;
        const startNotes = item.actionType === 'CHECK_IN' ? [item.reason ? `(${item.reason})` : null, item.notes ? `"${item.notes}"` : null].filter(Boolean).join(' ') : '—';
        const endNotes = item.actionType === 'CHECK_OUT' ? [getCheckoutLabel((item as any).checkoutType), item.reason ? `(${item.reason})` : null, item.notes ? `"${item.notes}"` : null].filter(Boolean).join(' ') : '—';
        summaries.push({
          id: item.id,
          startDate: new Date(item.actionDate),
          endDate: null,
          actionLabel: getActionLabel(item.actionType),
          residence: fmtResidence(item.residenceName, item.roomName, item.residenceId, item.roomId),
          startNotes,
          endNotes,
          duration: item.actionType === 'CHECK_OUT' ? getFormattedDuration(item) : '—',
          startReason: item.reason,
          startActionType: item.actionType,
        });
      } else if (g.type === 'period') {
        const items = g.items as AccommodationHistory[];
        const start = items[0];
        const end = items[items.length - 1];
        const transfers = items.filter(i => i.actionType === 'TRANSFER' || i.actionType === 'SWAP');
        const hasCheckout = end && end.actionType === 'CHECK_OUT';

        const fmtTransferPath = () => {
          if (transfers.length === 0) return null;
          const last = transfers[transfers.length - 1];
          let destResidence: string | null = last.toResidenceName || (last.toResidenceId ? getResidenceName(last.toResidenceId) : null) || last.residenceName || (last.residenceId ? getResidenceName(last.residenceId) : null) || null;
          let destRoom: string | null = last.toRoomName || (last.toResidenceId && last.toRoomId ? getRoomFullPath(last.toResidenceId, last.toRoomId).room : null) || last.roomName || (last.residenceId && last.roomId ? getRoomFullPath(last.residenceId, last.roomId).room : null) || null;

          if (!destRoom) {
            const transferIndex = items.indexOf(last);
            if (transferIndex >= 0) {
              for (let k = transferIndex + 1; k < items.length; k++) {
                const next = items[k];
                if (next.actionType === 'CHECK_IN' && (next.roomName || next.roomId)) {
                  destRoom = next.roomName || (next.residenceId && next.roomId ? getRoomFullPath(next.residenceId, next.roomId).room : null) || next.roomId || null;
                  destResidence = destResidence || next.residenceName || (next.residenceId ? getResidenceName(next.residenceId) : null) || (next.residenceId || null);
                  break;
                }
              }
            }
          }

          if (!destRoom) {
            const transferTime = new Date(last.actionDate).getTime();
            const futureCheckIn = workerHistory.find(h => new Date(h.actionDate).getTime() > transferTime && h.actionType === 'CHECK_IN' && (h.roomName || h.roomId));
            if (futureCheckIn) {
              destRoom = futureCheckIn.roomName || (futureCheckIn.residenceId && futureCheckIn.roomId ? getRoomFullPath(futureCheckIn.residenceId, futureCheckIn.roomId).room : null) || futureCheckIn.roomId || null;
              destResidence = destResidence || futureCheckIn.residenceName || (futureCheckIn.residenceId ? getResidenceName(futureCheckIn.residenceId) : null) || (futureCheckIn.residenceId || null);
            }
          }

          const startRes = fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId);
          const isSameRes = (destResidence && (destResidence === start.residenceName || destResidence === start.residenceId)) ||
            (last.toResidenceId && last.toResidenceId === start.residenceId);

          if (isSameRes) {
            return destRoom ? `${startRes} → ${destRoom}` : startRes;
          }
          if (!destResidence && !destRoom) return startRes;
          const dest = fmtResidence(destResidence || undefined, destRoom || undefined);
          return `${startRes} → ${dest}`;
        };

        let residenceSummary: string;
        if (hasCheckout) {
          const isSameRes = (end.residenceName && end.residenceName === start.residenceName) ||
            (end.residenceId && end.residenceId === start.residenceId);

          if (isSameRes) {
            const endRoom = end.roomName || (end.residenceId && end.roomId ? getRoomFullPath(end.residenceId, end.roomId).room : end.roomId);
            residenceSummary = transfers.length > 0
              ? `${fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId)} → ${endRoom}`
              : fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId);
          } else {
            residenceSummary = transfers.length > 0
              ? `${fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId)} → ${fmtResidence(end.residenceName, end.roomName, end.residenceId, end.roomId)}`
              : fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId);
          }
        } else {
          if (transfers.length > 0) {
            residenceSummary = fmtTransferPath()!;
          } else {
            residenceSummary = fmtResidence(start.residenceName, start.roomName, start.residenceId, start.roomId);
          }
        }

        const startParts = [] as string[];
        if (start.reason) startParts.push(`(${start.reason})`);
        if (start.notes) startParts.push(`"${start.notes}"`);
        const startNotes = startParts.length ? startParts.join(' ') : '—';

        const endParts = [] as string[];
        if (hasCheckout) {
          const checkoutLabel = getCheckoutLabel((end as any).checkoutType);
          if (checkoutLabel) endParts.push(checkoutLabel);
          if (end.reason) endParts.push(`(${end.reason})`);
          if (end.notes) endParts.push(`"${end.notes}"`);
        }
        if (transfers.length > 0) endParts.push(`(${transfers.length} ${t.transfers})`);
        const endNotes = endParts.length ? endParts.join(' ') : '—';

        let duration = '—';
        if (start) {
          const s = new Date(start.actionDate); s.setHours(0, 0, 0, 0);
          const e = hasCheckout ? (new Date((end as AccommodationHistory).actionDate)) : new Date();
          e.setHours(0, 0, 0, 0);
          const diff = Math.floor((e.getTime() - s.getTime()) / (1000 * 60 * 60 * 24));
          duration = `${Math.max(diff + 1, 1)}d`;
        }

        summaries.push({
          id: start.id + '_' + (hasCheckout ? end.id : 'open'),
          startDate: new Date(start.actionDate),
          endDate: hasCheckout ? new Date(end.actionDate) : null,
          actionLabel: `${t.checkIn} → ${t.checkOut}`,
          residence: residenceSummary,
          startNotes,
          endNotes,
          duration,
          startReason: start.reason,
          startActionType: start.actionType,
          startResidenceId: start.residenceId,
          startRoomId: start.roomId,
          endResidenceId: hasCheckout ? end.residenceId : null,
          endRoomId: hasCheckout ? end.roomId : null,
        });
      }
    }
    return summaries;
  }, [groupedHistory, residences, t]);

  const handlePrint = () => window.print();

  const lastCheckIn = useMemo(() => {
    if (!workerHistory || workerHistory.length === 0) return null;
    const checkIns = [...workerHistory].filter(h => h.actionType === 'CHECK_IN');
    if (checkIns.length === 0) return null;
    checkIns.sort((a, b) => new Date(b.actionDate).getTime() - new Date(a.actionDate).getTime());
    return checkIns[0].actionDate;
  }, [workerHistory]);

  const getRoleLabel = (role?: string) => {
    switch (role) {
      case 'Supervisor': return t.supervisor;
      case 'Engineer': return t.engineer;
      default: return t.worker;
    }
  };

  const getStatusBadge = (status?: string) => {
    switch (status) {
      case 'Active':
        return <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100">{t.active}</Badge>;
      case 'Transferring':
        return <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-100">{t.transferring}</Badge>;
      case 'Vacation':
        return <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100">{t.vacation}</Badge>;
      case 'Exit':
        return <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-100">{t.exit}</Badge>;
      default:
        return <Badge variant="outline">{t.notSpecified}</Badge>;
    }
  };

  const getActionLabel = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return t.checkIn;
      case 'CHECK_OUT': return t.checkOut;
      case 'TRANSFER': return t.transfer;
      case 'SWAP': return t.swap;
      default: return type;
    }
  };

  const getActionColor = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return 'text-green-700 bg-green-50';
      case 'CHECK_OUT': return 'text-red-700 bg-red-50';
      case 'TRANSFER': return 'text-blue-700 bg-blue-50';
      case 'SWAP': return 'text-purple-700 bg-purple-50';
      default: return 'text-gray-700 bg-gray-50';
    }
  };

  const calculateDays = (since: string) => {
    const sinceDate = new Date(since);
    const today = new Date();
    sinceDate.setHours(0, 0, 0, 0);
    today.setHours(0, 0, 0, 0);
    const diffTime = today.getTime() - sinceDate.getTime();
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
    const days = diffDays + 1;
    return `${days} ${days === 1 ? t.day : t.days}`;
  };

  const formatDuration = (totalDays: number): string => {
    if (totalDays <= 0) return '—';
    const years = Math.floor(totalDays / 365);
    const remainingAfterYears = totalDays % 365;
    const months = Math.floor(remainingAfterYears / 30);
    const days = remainingAfterYears % 30;
    const parts: string[] = [];
    if (years > 0) parts.push(locale === 'ar' ? `${years}س` : `${years}y`);
    if (months > 0) parts.push(locale === 'ar' ? `${months}ش` : `${months}m`);
    if (days > 0 || parts.length === 0) parts.push(locale === 'ar' ? `${days}ي` : `${days}d`);
    return parts.join(' ');
  };

  const historyWithDurations = useMemo(() => {
    const sortedHistory = [...workerHistory].sort((a, b) =>
      new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime()
    );
    let lastCheckInDate: Date | null = null;
    const durationsMap = new Map<string, number>();
    for (const record of sortedHistory) {
      if (record.actionType === 'CHECK_IN') {
        lastCheckInDate = new Date(record.actionDate);
        lastCheckInDate.setHours(0, 0, 0, 0);
      } else if (record.actionType === 'CHECK_OUT' && lastCheckInDate) {
        const checkOutDate = new Date(record.actionDate);
        checkOutDate.setHours(0, 0, 0, 0);
        const diffTime = checkOutDate.getTime() - lastCheckInDate.getTime();
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        const duration = Math.max(diffDays + 1, 1);
        durationsMap.set(record.id, duration);
        lastCheckInDate = null;
      }
    }
    return durationsMap;
  }, [workerHistory]);

  const getFormattedDuration = (item: AccommodationHistory): string | null => {
    if (item.actionType !== 'CHECK_OUT') return null;
    const calculatedDuration = historyWithDurations.get(item.id);
    if (calculatedDuration) {
      return formatDuration(calculatedDuration);
    }
    if (item.duration) {
      return formatDuration(item.duration);
    }
    return null;
  };

  const documentNo = useMemo(() => {
    if (!selectedWorker) return '';
    const date = new Date();
    return `ACC-${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}-${selectedWorker.employeeId || selectedWorker.id.slice(-4)}`;
  }, [selectedWorker]);

  return (
    <div className="min-h-screen bg-background">
      <div className="print:hidden p-6 border-b bg-card">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-3 mb-4">
            <FileText className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-2xl font-bold">{t.pageTitle}</h1>
              <p className="text-muted-foreground text-sm">{t.pageDescription}</p>
            </div>
          </div>

          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground`} />
              <Input
                placeholder={t.searchPlaceholder}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                className={isRTL ? 'pr-10' : 'pl-10'}
              />
            </div>
            <Button onClick={handleSearch} disabled={loading}>
              {loading ? t.searching : t.search}
            </Button>
          </div>

          {searchResults.length > 0 && (
            <Card className="mt-4">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">{t.searchResults} ({searchResults.length})</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y max-h-64 overflow-auto">
                  {searchResults.map((worker) => (
                    <button
                      key={worker.id}
                      onClick={() => handleSelectWorker(worker)}
                      className={`w-full p-4 ${isRTL ? 'text-right' : 'text-left'} hover:bg-accent transition-colors flex items-center justify-between`}
                    >
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <User className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <div className="font-medium">{worker.name}</div>
                          <div className="text-sm text-muted-foreground flex items-center gap-2">
                            {worker.employeeId && <span>#{worker.employeeId}</span>}
                            {worker.nationaliy && <span>• {worker.nationaliy}</span>}
                          </div>
                        </div>
                      </div>
                      {getStatusBadge(worker.status)}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {selectedWorker && (
        <>
          <div className="print:hidden p-4 max-w-4xl mx-auto flex justify-between items-center">
            <Button variant="outline" onClick={() => setSelectedWorker(null)}>
              {t.selectAnotherWorker}
            </Button>
            <Button onClick={handlePrint} className="gap-2">
              <Printer className="h-4 w-4" />
              {t.printCertificate}
            </Button>
          </div>

          <div className="max-w-4xl mx-auto p-4 print:p-0 print:max-w-none print:m-0">
            <div className="bg-white text-black print:bg-white rounded-lg border-2 border-gray-300 print:border print:border-gray-400 overflow-hidden flex flex-col print:min-h-[277mm] print:h-[277mm]" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>

              <div className="bg-gradient-to-r from-slate-800 to-slate-700 text-white px-4 py-2.5 print:px-3 print:py-2 print:bg-slate-800 flex-shrink-0" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-9 h-9 bg-white/20 rounded-lg flex items-center justify-center">
                      <Building2 className="h-5 w-5 text-white" />
                    </div>
                    <div>
                      <h1 className="text-base font-bold tracking-wide">{t.certificateTitle}</h1>
                      <p className="text-slate-300 text-xs">{t.certificateSubtitle}</p>
                    </div>
                  </div>
                  <div className="text-right text-xs">
                    <div className="text-slate-300">{t.documentNo}</div>
                    <div className="font-mono font-bold text-sm">{documentNo}</div>
                    <div className="text-slate-300">{t.issueDate}: {format(new Date(), 'dd/MM/yyyy')}</div>
                  </div>
                </div>
              </div>

              <div className="p-3 print:p-2 space-y-2 print:space-y-1.5 flex-grow">

                <div className="grid grid-cols-3 gap-2 print:gap-1.5">

                  <div className="col-span-2 border rounded-lg p-2.5 print:p-2">
                    <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                      <User className="h-3 w-3" />
                      {t.workerData}
                    </h3>
                    <div className="space-y-1 text-xs print:text-[11px]">
                      <div className="flex justify-between border-b border-dashed pb-1">
                        <span className="text-slate-500">{t.fullName}</span>
                        <span className="font-semibold">{selectedWorker.name}</span>
                      </div>
                      <div className="grid grid-cols-2 gap-x-4 gap-y-1">
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.idNumber}</span>
                          <span className="font-mono text-[10px]">{selectedWorker.idNumber || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.employeeNumber}</span>
                          <span className="font-mono text-[10px]">{selectedWorker.employeeId || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.nationality}</span>
                          <span>{selectedWorker.nationaliy || t.notSpecified}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.jobTitle}</span>
                          <span>{getRoleLabel(selectedWorker.role)}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5 col-span-2">
                          <span className="text-slate-500">{t.company}</span>
                          <span>{getCompanyName(selectedWorker.company)}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="border rounded-lg p-2 print:p-1.5 bg-gradient-to-br from-slate-50 to-white">
                    <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                      <Home className="h-3 w-3" />
                      {t.currentStatus}
                    </h3>
                    {currentOccupancy ? (
                      <div className="space-y-1.5">
                        <div className="flex items-center gap-1.5 bg-green-100 text-green-800 font-semibold px-2 py-1 rounded border border-green-200 text-xs">
                          <CheckCircle2 className="h-3.5 w-3.5 flex-shrink-0" />
                          <span>{t.currentlyAccommodated}</span>
                        </div>

                        {(() => {
                          const roomPath = getRoomFullPath(currentOccupancy.residenceId, currentOccupancy.roomId);
                          return (
                            <div className="flex flex-col gap-1 mb-1">
                              {/* Row 1: City & Housing */}
                              <div className="grid grid-cols-2 gap-1">
                                <div className="bg-amber-50 px-2 py-1 rounded border border-amber-200 flex items-center gap-2">
                                  <div className="flex-shrink-0 p-1 bg-amber-100 rounded-md">
                                    <MapPin className="h-3.5 w-3.5 text-amber-600" />
                                  </div>
                                  <div className="min-w-0">
                                    <div className="text-[7px] text-amber-600 font-semibold uppercase">{t.city}</div>
                                    <div className="text-[10px] font-bold text-amber-900 truncate leading-tight">{roomPath.city || '—'}</div>
                                  </div>
                                </div>
                                <div className="bg-sky-50 px-2 py-1 rounded border border-sky-200 flex items-center gap-2">
                                  <div className="flex-shrink-0 p-1 bg-sky-100 rounded-md">
                                    <Home className="h-3.5 w-3.5 text-sky-600" />
                                  </div>
                                  <div className="min-w-0">
                                    <div className="text-[7px] text-sky-600 font-semibold uppercase">{t.housing}</div>
                                    <div className="text-[10px] font-bold text-sky-900 truncate leading-tight">{roomPath.housing}</div>
                                  </div>
                                </div>
                              </div>

                              {/* Row 2: Building, Floor, Room */}
                              <div className="grid grid-cols-3 gap-1">
                                <div className="bg-indigo-50 px-2 py-1 rounded border border-indigo-200 flex items-center gap-2">
                                  <div className="flex-shrink-0 p-1 bg-indigo-100 rounded-md">
                                    <Building2 className="h-3.5 w-3.5 text-indigo-600" />
                                  </div>
                                  <div className="min-w-0">
                                    <div className="text-[7px] text-indigo-600 font-semibold uppercase">{t.building}</div>
                                    <div className="text-[10px] font-bold text-indigo-900 truncate leading-tight">{roomPath.building || '—'}</div>
                                  </div>
                                </div>
                                <div className="bg-violet-50 px-2 py-1 rounded border border-violet-200 flex items-center gap-2">
                                  <div className="flex-shrink-0 p-1 bg-violet-100 rounded-md">
                                    <Layers className="h-3.5 w-3.5 text-violet-600" />
                                  </div>
                                  <div className="min-w-0">
                                    <div className="text-[7px] text-violet-600 font-semibold uppercase">{t.floor}</div>
                                    <div className="text-[10px] font-bold text-violet-900 truncate leading-tight">{roomPath.floor || '—'}</div>
                                  </div>
                                </div>
                                <div className="bg-emerald-50 px-2 py-1 rounded border border-emerald-200 flex items-center gap-2">
                                  <div className="flex-shrink-0 p-1 bg-emerald-100 rounded-md">
                                    <DoorOpen className="h-3.5 w-3.5 text-emerald-600" />
                                  </div>
                                  <div className="min-w-0">
                                    <div className="text-[7px] text-emerald-600 font-semibold uppercase">{t.room}</div>
                                    <div className="text-[10px] font-bold text-emerald-900 truncate leading-tight">{roomPath.room}</div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          );
                        })()}

                        <div className="flex items-center justify-between text-[10px] text-slate-600 pt-1 border-t border-slate-200">
                          <span className="flex items-center gap-0.5">
                            <Calendar className="h-2.5 w-2.5" />
                            {lastCheckIn ? format(new Date(lastCheckIn), 'dd/MM/yyyy') : format(new Date(currentOccupancy.since), 'dd/MM/yyyy')}
                          </span>
                          <span className="flex items-center gap-0.5 bg-slate-100 px-1 py-0.5 rounded-full font-medium">
                            <Clock className="h-2.5 w-2.5" />
                            {calculateDays(lastCheckIn || currentOccupancy.since)}
                          </span>
                        </div>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1.5 bg-orange-100 text-orange-800 font-semibold px-2 py-1.5 rounded border border-orange-200 text-xs">
                        <AlertCircle className="h-3.5 w-3.5 flex-shrink-0" />
                        <span>{t.notCurrentlyAccommodated}</span>
                      </div>
                    )}
                  </div>
                </div>

                <div className="border rounded-lg p-2 print:p-1.5">
                  <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                    <TrendingUp className="h-3 w-3" />
                    {t.summary}
                  </h3>
                  <div className="grid grid-cols-4 gap-2 print:gap-1.5">
                    <div className="p-1.5 bg-green-50 rounded border border-green-100 flex items-center justify-center gap-2">
                      <LogIn className="h-5 w-5 text-green-600 opacity-80" />
                      <div className="text-center">
                        <div className="text-lg font-bold text-green-700 leading-none">{stats.checkIns}</div>
                        <div className="text-[9px] text-green-600">{t.checkIns}</div>
                      </div>
                    </div>
                    <div className="p-1.5 bg-red-50 rounded border border-red-100 flex items-center justify-center gap-2">
                      <LogOut className="h-5 w-5 text-red-600 opacity-80" />
                      <div className="text-center">
                        <div className="text-lg font-bold text-red-700 leading-none">{stats.checkOuts}</div>
                        <div className="text-[9px] text-red-600">{t.checkOuts}</div>
                      </div>
                    </div>
                    <div className="p-1.5 bg-blue-50 rounded border border-blue-100 flex items-center justify-center gap-2">
                      <ArrowRightLeft className="h-4 w-4 text-blue-600 opacity-80" />
                      <div className="text-center">
                        <div className="text-lg font-bold text-blue-700 leading-none">{stats.swaps}</div>
                        <div className="text-[9px] text-blue-600">{t.transfers}</div>
                      </div>
                    </div>
                    <div className="p-1.5 bg-purple-50 rounded border border-purple-100 flex items-center justify-center gap-2">
                      <Calendar className="h-4 w-4 text-purple-600 opacity-80" />
                      <div className="text-center">
                        <div className="text-lg font-bold text-purple-700 leading-none">{stats.totalDays}</div>
                        <div className="text-[9px] text-purple-600">{t.totalDays}</div>
                      </div>
                    </div>
                  </div>
                </div>{/* End of Summary Section Container (Closed here to separate Timeline) */}

                {/* Monthly timeline summary */}
                {/* Removed border-t and reduced spacing as requested */}
                <div className="mt-2 mb-4">

                  {(() => {
                    // Timeline Data Calculation
                    if (summarizedHistory.length === 0) return null;

                    const items: any[] = [];
                    const source = [...summarizedHistory];

                    // 1. DYNAMIC COLOR MAPPING FOR RESIDENCES
                    // User Request: "Distinguish each residence with a color" & "Just residence names without room numbers"
                    // Extract just the residence name part (before '•') relative to the full string for mapping
                    const getResName = (fullStr: string) => fullStr.split(' • ')[0].trim();

                    // We need to map the FULL residence string (from items) to a color, 
                    // but we want the Legend to only show unique residence NAMES.

                    // Create a map of "Residence Name" -> Color Index
                    // This ensures "Redsea • 101" and "Redsea • 102" get the SAME color if we want that,
                    // OR we keep unique colors per room? 
                    // User said: "Excellent, make it just residence names without room numbers" -> Implies grouping by Residence Name.

                    const uniqueResNames = Array.from(new Set(source.map((s: any) => getResName(s.residence))));

                    const colorPalette = [
                      { hex: '#2E7D32', bg: 'bg-[#2E7D32]', border: 'border-[#2E7D32]', text: 'text-[#2E7D32]' }, // Green
                      { hex: '#1565C0', bg: 'bg-[#1565C0]', border: 'border-[#1565C0]', text: 'text-[#1565C0]' }, // Blue
                      { hex: '#C62828', bg: 'bg-[#C62828]', border: 'border-[#C62828]', text: 'text-[#C62828]' }, // Red
                      { hex: '#EF6C00', bg: 'bg-[#EF6C00]', border: 'border-[#EF6C00]', text: 'text-[#EF6C00]' }, // Orange
                      { hex: '#6A1B9A', bg: 'bg-[#6A1B9A]', border: 'border-[#6A1B9A]', text: 'text-[#6A1B9A]' }, // Purple
                      { hex: '#00838F', bg: 'bg-[#00838F]', border: 'border-[#00838F]', text: 'text-[#00838F]' }, // Cyan
                      { hex: '#AD1457', bg: 'bg-[#AD1457]', border: 'border-[#AD1457]', text: 'text-[#AD1457]' }, // Pink
                    ];

                    // Config: [Near-Top, Far-Bottom, Far-Top, Near-Bottom, Mid-Top]
                    const offsetConfig = [
                      { type: 'top', height: '1.8rem' },      // Near Top
                      { type: 'bottom', height: '2.4rem' },   // Far Bottom
                      { type: 'top', height: '3.2rem' },      // Far Top
                      { type: 'bottom', height: '1.4rem' },   // Near Bottom
                      { type: 'top', height: '2.4rem' },      // Mid Top
                      { type: 'bottom', height: '3.4rem' },   // Deep Bottom
                    ];

                    const minDate = new Date(source[0].startDate);
                    minDate.setDate(minDate.getDate() - 30);
                    const maxDate = new Date(source[source.length - 1].endDate || new Date());
                    maxDate.setDate(maxDate.getDate() + 30);
                    const totalMs = maxDate.getTime() - minDate.getTime();
                    const getPos = (d: Date) => Math.max(0, Math.min(100, ((d.getTime() - minDate.getTime()) / totalMs) * 100));

                    // To avoid overlap, we'll keep track of the last pos for top and bottom separately
                    let lastTopPos = -20;
                    let lastBottomPos = -20;
                    let offsetIdx = 0;

                    for (let i = 0; i < source.length; i++) {
                      const curr = source[i] as any;
                      const currStart = new Date(curr.startDate);
                      const currEnd = curr.endDate ? new Date(curr.endDate) : new Date();

                      const resName = getResName(curr.residence);
                      const resIndex = uniqueResNames.indexOf(resName);
                      const style = colorPalette[resIndex % colorPalette.length];

                      const startPos = getPos(currStart);
                      const endPos = getPos(currEnd);
                      const midPos = (startPos + endPos) / 2;

                      // Collision avoidance: if midPos is too close to last label on the same side, switch side
                      const config = offsetConfig[offsetIdx % offsetConfig.length];

                      // If this is top and too close to last top, OR bottom and too close to last bottom
                      // We prefer alternating, but if the space is very tight, we might need more logic
                      // For now, let's just use the index and ensure enough variety
                      if (config.type === 'top' && midPos - lastTopPos < 12) {
                        // Keep top but use a different height if possible? Or just hope the height variety helps
                      }

                      if (config.type === 'top') lastTopPos = midPos;
                      else lastBottomPos = midPos;

                      items.push({
                        id: curr.id,
                        type: 'STAY',
                        startDate: currStart,
                        endDate: currEnd,
                        title: curr.residence,
                        subtitle: curr.startReason || curr.startNotes || (curr.startActionType === 'CHECK_IN' ? 'Occupied' : ''),
                        duration: curr.duration,
                        color: style.hex,
                        bgColor: style.bg,
                        borderColor: style.border,
                        textColor: style.text,
                        offset: config,
                        midPos // store for later use if needed
                      });

                      offsetIdx++;
                    }

                    if (items.length === 0) return null;

                    const getWidth = (s: Date, e: Date) => Math.max(getPos(e) - getPos(s), 0.5);

                    // Axis Ticks (Months) logic optimization for long durations
                    const totalDaysSpan = totalMs / (1000 * 60 * 60 * 24);
                    let tickIntervalMonth = 1;

                    if (totalDaysSpan > 365 * 3) { // > 3 Years
                      tickIntervalMonth = 6;
                    } else if (totalDaysSpan > 365 * 1.5) { // > 1.5 Years
                      tickIntervalMonth = 3;
                    }

                    const months = [];
                    const cursor = new Date(minDate);
                    cursor.setDate(1);
                    // Align cursor to a clean interval if needed, but simple iteration is usually fine

                    while (cursor <= maxDate) {
                      months.push(new Date(cursor));
                      cursor.setMonth(cursor.getMonth() + tickIntervalMonth);
                    }

                    return (
                      <div className="w-full mt-2 mb-4">
                        {/* RESIDENCE LEGEND - Added as requested */}
                        <div className="flex flex-wrap gap-3 mb-6 justify-center px-4">
                          {uniqueResNames.map((res, idx) => {
                            if (!res) return null;
                            const style = colorPalette[idx % colorPalette.length];
                            return (
                              <div key={idx} className="flex items-center gap-1.5 bg-slate-50 px-2 py-1 rounded border border-slate-100">
                                <div className="w-2.5 h-2.5 rounded-full shadow-sm" style={{ backgroundColor: style.hex }}></div>
                                <span className="text-[10px] font-semibold text-slate-600">{res}</span>
                              </div>
                            );
                          })}
                        </div>

                        <div className="relative w-full h-[200px] select-none font-sans bg-white text-[#333]">

                          {/* 1. Main Event Track Line (Center) - Thinner and Lighter */}
                          {/* MOVED UP TO 45% TO GIVE MORE ROOM AT BOTTOM */}
                          <div className="absolute top-[45%] left-0 right-0 h-[1.5px] bg-slate-800 z-0 opacity-80 rounded-full"></div>

                          {/* 2. Bottom Axis Line (For Dates) - Very thin */}
                          <div className="absolute bottom-6 left-0 right-0 h-[0.8px] bg-slate-200 z-0"></div>

                          {/* Month Ticks on Bottom Axis */}
                          {months.map(m => {
                            const left = getPos(m);
                            if (left < 0 || left > 100) return null;
                            return (
                              <div key={m.getTime()} className="absolute bottom-6 flex flex-col items-center" style={{ left: `${left}%`, transform: 'translate(-50%, 0)' }}>
                                {/* Tick Mark */}
                                <div className="w-[1px] h-1.5 bg-slate-300 mb-1"></div>
                                {/* Label */}
                                <div className="absolute top-1 text-[8px] font-medium text-slate-400 whitespace-nowrap">
                                  {format(m, 'MMM yy', { locale: dateLocale })}
                                </div>
                              </div>
                            );
                          })}

                          {/* Timeline Items */}
                          {items.map((item, idx) => {
                            const left = getPos(item.startDate);
                            const width = getWidth(item.startDate, item.endDate);
                            const mid = left + width / 2;

                            const isTop = item.offset.type === 'top';
                            const stemHeight = item.offset.height;

                            return (
                              <React.Fragment key={item.id}>
                                {/* EVENT PERIOD BAR - Lighter (6px height) */}
                                <div
                                  className="absolute top-[45%] h-[6px] z-10"
                                  style={{
                                    left: `${left}%`,
                                    width: `${width}%`,
                                    backgroundColor: item.color,
                                    transform: 'translateY(-50%)',
                                    opacity: 0.85,
                                    borderRadius: '3px',
                                    boxShadow: '0 1px 2px rgba(0,0,0,0.05)'
                                  }}
                                ></div>

                                {/* DURATION TEXT - ABOVE THE COLORED LINE */}
                                <div
                                  className="absolute top-[45%] text-[9px] font-bold z-20 pointer-events-none transform -translate-y-[18px] -translate-x-1/2"
                                  style={{
                                    left: `${mid}%`,
                                    color: item.color
                                  }}
                                >
                                  {item.duration}
                                </div>

                                {/* START DOT - NO WHITE BORDER */}
                                <div
                                  className="absolute top-[45%] w-[10px] h-[10px] rounded-full z-20 shadow-sm"
                                  style={{
                                    left: `${left}%`,
                                    backgroundColor: item.color,
                                    transform: 'translate(-50%, -50%)',
                                  }}
                                ></div>

                                {/* END DOT - NO WHITE BORDER */}
                                <div
                                  className="absolute top-[45%] w-[10px] h-[10px] rounded-full z-20 shadow-sm"
                                  style={{
                                    left: `${left + width}%`,
                                    backgroundColor: item.color,
                                    transform: 'translate(-50%, -50%)',
                                  }}
                                ></div>

                                {/* START DATE LABEL - RAISED ABOVE DURATION */}
                                {/* Shifted up significantly (-24px) so the slanted text starts above the duration level */}
                                <div
                                  className="absolute top-[45%] text-[8px] text-zinc-500 font-medium z-0 pointer-events-none"
                                  style={{
                                    left: `${left}%`,
                                    transformOrigin: 'left bottom',
                                    transform: 'translate(0px, -24px) rotate(-45deg)',
                                    whiteSpace: 'nowrap'
                                  }}
                                >
                                  {format(item.startDate, 'dd MMM', { locale: dateLocale })}
                                </div>

                                {/* END DATE LABEL - SHIFTED RIGHT */}
                                {/* Shifted X by 4px as requested */}
                                <div
                                  className="absolute top-[45%] text-[8px] text-zinc-500 font-medium z-0 pointer-events-none"
                                  style={{
                                    left: `${left + width}%`,
                                    transformOrigin: 'left top',
                                    transform: 'translate(4px, 8px) rotate(45deg)',
                                    whiteSpace: 'nowrap'
                                  }}
                                >
                                  {format(item.endDate, 'dd MMM', { locale: dateLocale })}
                                </div>

                                {/* DASHED CONNECTOR - Thinner dashed line */}
                                <div
                                  className="absolute left-0 border-l-[1px] border-dashed opacity-40 pointer-events-none"
                                  style={{
                                    left: `${mid}%`,
                                    top: isTop ? 'auto' : '45%',
                                    bottom: isTop ? '55%' : 'auto',
                                    height: stemHeight,
                                    width: '0px',
                                    borderColor: item.color
                                  }}
                                ></div>

                                {/* CALLOUT BOX - REPLACED TEXT WITH COLOR */}
                                {/* User Request: "Replace residence name with line colors" */}
                                <div
                                  className={`absolute flex flex-col items-center z-30`}
                                  style={{
                                    left: `${mid}%`,
                                    top: isTop ? 'auto' : '45%',
                                    bottom: isTop ? '55%' : 'auto',
                                    transform: isTop ? `translate(-50%, -${stemHeight})` : `translate(-50%, ${stemHeight})`
                                  }}
                                >
                                  <div
                                    className={`bg-white px-2.5 py-1.5 rounded-lg border shadow-sm text-center min-w-[100px]`}
                                    style={{ borderColor: item.color, borderWidth: '1px' }}
                                  >
                                    {/* Removed Residence Title - Just showing Reason as implied by 'Replace' */}
                                    <div className="text-[9px] text-slate-500 leading-tight font-medium">
                                      {item.subtitle}
                                    </div>
                                  </div>
                                </div>

                              </React.Fragment>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })()}
                </div>

                <div className="border rounded-lg p-2 print:p-1.5">
                  <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1 flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {t.recentHistory}
                  </h3>
                  {historyLoading ? (
                    <div className="text-center text-slate-400 py-2 text-xs">Loading...</div>
                  ) : workerHistory.length === 0 ? (
                    <div className="text-center text-slate-400 py-2 text-xs">No records</div>
                  ) : (
                    <table className="w-full text-[10px]">
                      <thead>
                        <tr className="text-left text-slate-500">
                          <th className="px-2 py-1">{t.checkIn}</th>
                          <th className="px-2 py-1">Date</th>
                          <th className="px-2 py-1">Details</th>
                          <th className="px-2 py-1">{t.checkInNotes}</th>
                          <th className="px-2 py-1">{t.checkOut}</th>
                          <th className="px-2 py-1">Date</th>
                          <th className="px-2 py-1">{t.checkOutNotes}</th>
                          <th className="px-2 py-1">Duration</th>
                        </tr>
                      </thead>
                      <tbody>
                        {[...summarizedHistory].reverse().map((s) => (
                          <tr key={s.id} className="border-b border-dashed last:border-0">
                            <td className="px-2 py-1"><span className={`px-2 py-0.5 rounded font-medium ${getActionColor('CHECK_IN')}`}>{t.checkIn}</span></td>
                            <td className="px-2 py-1 text-slate-500 font-mono">{format(s.startDate, 'dd/MM/yyyy')}</td>
                            <td className="px-2 py-1 text-slate-700 truncate">{s.residence}</td>
                            <td className="px-2 py-1 text-slate-700 truncate">{s.startNotes}</td>
                            <td className="px-2 py-1">{s.endDate ? <span className={`px-2 py-0.5 rounded font-medium ${getActionColor('CHECK_OUT')}`}>{t.checkOut}</span> : <span className="text-slate-400">—</span>}</td>
                            <td className="px-2 py-1 text-slate-500 font-mono">{s.endDate ? format(s.endDate, 'dd/MM/yyyy') : '—'}</td>
                            <td className="px-2 py-1 text-left text-slate-700 truncate">{s.endNotes}</td>
                            <td className="px-2 py-1 text-orange-600 font-medium bg-orange-50 rounded text-right">{s.duration}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>

              <div className="p-3 print:p-2 border-t border-slate-200 flex-shrink-0 mt-auto">
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center">
                    <div className="h-10 print:h-8 border-2 border-dashed border-slate-300 rounded flex items-center justify-center text-slate-400">
                      <span className="text-[9px] uppercase tracking-wider">{t.stamp}</span>
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="h-10 print:h-8 border-b-2 border-slate-400"></div>
                    <span className="text-[9px] text-slate-500 uppercase tracking-wider">{t.signature}</span>
                  </div>
                </div>

                <div className="text-center text-[9px] text-slate-400 pt-2 mt-2 border-t border-dashed">
                  {t.generatedBy} • {format(new Date(), 'dd/MM/yyyy HH:mm')}
                </div>
              </div>
            </div>
          </div>
        </>
      )
      }

      {
        !selectedWorker && searchResults.length === 0 && (
          <div className="flex items-center justify-center min-h-[60vh] print:hidden">
            <div className="text-center max-w-md">
              <FileText className="h-20 w-20 mx-auto mb-6 text-muted-foreground opacity-50" />
              <h2 className="text-2xl font-semibold mb-2">{t.emptyStateTitle}</h2>
              <p className="text-muted-foreground mb-6">{t.emptyStateDescription}</p>
              <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground">
                <div className="flex items-center gap-2">
                  <User className="h-4 w-4" />
                  {t.workerInfo}
                </div>
                <div className="flex items-center gap-2">
                  <Home className="h-4 w-4" />
                  {t.accommodationStatus}
                </div>
                <div className="flex items-center gap-2">
                  <Clock className="h-4 w-4" />
                  {t.history}
                </div>
              </div>
            </div>
          </div>
        )
      }

      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 5mm;
          }
          
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            background: white !important;
            font-size: 10px !important;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          .bg-gradient-to-r {
            background: #1e293b !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          .bg-green-50 { background-color: #f0fdf4 !important; }
          .bg-red-50 { background-color: #fef2f2 !important; }
          .bg-blue-50 { background-color: #eff6ff !important; }
          .bg-purple-50 { background-color: #faf5ff !important; }
          
          .text-green-700 { color: #15803d !important; }
          .text-red-700 { color: #b91c1c !important; }
          .text-blue-700 { color: #1d4ed8 !important; }
          .text-purple-700 { color: #7c3aed !important; }
          
          .border-green-100 { border-color: #dcfce7 !important; }
          .border-red-100 { border-color: #fee2e2 !important; }
          .border-blue-100 { border-color: #dbeafe !important; }
          .border-purple-100 { border-color: #f3e8ff !important; }
        }
      `}</style>
    </div >
  );
}
