"use client";

import React, { useState, useMemo, useRef, useEffect } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAccommodation, Worker, AccommodationHistory } from '@/context/accommodation-context';
import { useLanguage } from '@/context/language-context';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { 
  Search,
  Printer,
  User,
  Building2,
  MapPin,
  Calendar,
  Clock,
  LogIn,
  LogOut,
  ArrowRightLeft,
  Repeat2,
  FileText,
  Hash,
  Globe,
  Briefcase,
  Building,
  IdCard,
  CheckCircle2,
  Home,
  TrendingUp,
  AlertCircle,
  MoreHorizontal,
  Layers,
  DoorOpen
} from 'lucide-react';
import { format } from 'date-fns';
import { ar, enUS } from 'date-fns/locale';

// Translation keys
const translations = {
  en: {
    pageTitle: 'Worker Accommodation Certificate',
    pageDescription: 'View complete worker data and accommodation status',
    searchPlaceholder: 'Search by name, ID number, or employee number...',
    search: 'Search',
    searching: 'Searching...',
    searchResults: 'Search Results',
    selectAnotherWorker: 'Select Another Worker',
    printCertificate: 'Print Certificate',
    workerData: 'Worker Information',
    fullName: 'Full Name',
    idNumber: 'ID Number',
    employeeNumber: 'Employee Number',
    nationality: 'Nationality',
    jobTitle: 'Job Title',
    company: 'Company',
    notRegistered: 'N/A',
    notSpecified: 'N/A',
    worker: 'Worker',
    supervisor: 'Supervisor',
    engineer: 'Engineer',
    active: 'Active',
    transferring: 'Transferring',
    vacation: 'Vacation',
    exit: 'Exit',
    currentStatus: 'Current Status',
    currentlyAccommodated: 'Currently Accommodated',
    notCurrentlyAccommodated: 'Not Accommodated',
    accommodationLocation: 'Location',
    roomNumber: 'Room',
    city: 'City',
    housing: 'Housing',
    building: 'Building',
    floor: 'Floor',
    room: 'Room',
    checkInDate: 'Check-in',
    stayDuration: 'Duration',
    days: 'days',
    day: 'day',
    summary: 'Summary',
    checkIns: 'Check-ins',
    checkOuts: 'Check-outs',
    transfers: 'Swaps',
    totalDays: 'Total Days',
    recentHistory: 'Recent Movement History',
    moreRecords: 'more records',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    checkInNotes: 'Check-in Notes',
    checkOutNotes: 'Check-out Notes',
    transfer: 'Swap',
    swap: 'Swap',
    from: 'From',
    to: 'To',
    certificateTitle: 'WORKER ACCOMMODATION CERTIFICATE',
    certificateSubtitle: 'Official Housing Status Document',
    issueDate: 'Issue Date',
    documentNo: 'Document No',
    signature: 'Authorized Signature',
    stamp: 'Official Stamp',
    generatedBy: 'Generated by Accommodation Management System',
    emptyStateTitle: 'Worker Certificate',
    emptyStateDescription: 'Search for a worker to generate their accommodation certificate',
    workerInfo: 'Worker Info',
    accommodationStatus: 'Status',
    history: 'History',
  },
  ar: {
    pageTitle: 'إفادة سكن موظف',
    pageDescription: 'استعراض بيانات الموظف الكاملة وحالته السكنية',
    searchPlaceholder: 'ابحث بالاسم أو رقم الهوية أو الرقم الوظيفي...',
    search: 'بحث',
    searching: 'جاري البحث...',
    searchResults: 'نتائج البحث',
    selectAnotherWorker: 'اختيار موظف آخر',
    printCertificate: 'طباعة الإفادة',
    workerData: 'بيانات الموظف',
    fullName: 'الاسم',
    idNumber: 'رقم الهوية',
    employeeNumber: 'الرقم الوظيفي',
    nationality: 'الجنسية',
    jobTitle: 'المسمى',
    company: 'الشركة',
    notRegistered: 'غ/م',
    notSpecified: 'غ/م',
    worker: 'عامل',
    supervisor: 'مشرف',
    engineer: 'مهندس',
    active: 'نشط',
    transferring: 'قيد النقل',
    vacation: 'إجازة',
    exit: 'خارج',
    currentStatus: 'الحالة الحالية',
    currentlyAccommodated: 'مُسكّن حالياً',
    notCurrentlyAccommodated: 'غير مُسكّن',
    accommodationLocation: 'الموقع',
    roomNumber: 'الغرفة',
    city: 'المدينة',
    housing: 'المسكن',
    building: 'المبنى',
    floor: 'الطابق',
    room: 'الغرفة',
    checkInDate: 'تاريخ التسكين',
    stayDuration: 'المدة',
    days: 'يوم',
    day: 'يوم',
    summary: 'ملخص',
    checkIns: 'تسكين',
    checkOuts: 'إخراج',
    transfers: 'تبديلات',
    totalDays: 'إجمالي الأيام',
    recentHistory: 'سجل الحركات الأخيرة',
    moreRecords: 'سجلات إضافية',
    checkIn: 'تسكين',
    checkOut: 'إخراج',
    checkInNotes: 'ملاحظات التسكين',
    checkOutNotes: 'ملاحظات الإخراج',
    transfer: 'تبديل',
    swap: 'تبديل',
    from: 'من',
    to: 'إلى',
    certificateTitle: 'إفادة سكن موظف',
    certificateSubtitle: 'مستند رسمي لحالة السكن',
    issueDate: 'تاريخ الإصدار',
    documentNo: 'رقم المستند',
    signature: 'توقيع المسؤول',
    stamp: 'الختم الرسمي',
    generatedBy: 'صادر من نظام إدارة السكن',
    emptyStateTitle: 'إفادة سكن موظف',
    emptyStateDescription: 'ابحث عن موظف لإصدار إفادة السكن الخاصة به',
    workerInfo: 'البيانات',
    accommodationStatus: 'الحالة',
    history: 'السجل',
  }
};

export default function WorkerCertificatePage() {
  const { locale } = useLanguage();
  const t = translations[locale] || translations.en;
  const dateLocale = locale === 'ar' ? ar : enUS;
  const isRTL = locale === 'ar';

  const searchParams = useSearchParams();
  const workerIdFromQuery = searchParams.get('workerId');

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedWorker, setSelectedWorker] = useState<Worker | null>(null);
  const [searchResults, setSearchResults] = useState<Worker[]>([]);
  const [loading, setLoading] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [workerHistory, setWorkerHistory] = useState<AccommodationHistory[]>([]);

  const { 
    findWorkerAsync,
    fetchWorkerHistory,
    occupants,
    residences,
    companies,
    getWorkerByIdOrEmployeeId
  } = useAccommodation();

  // إذا كان workerId موجود في الرابط، ابحث تلقائياً عن الموظف وعرض الشهادة
  useEffect(() => {
    const fetchByWorkerId = async () => {
      if (workerIdFromQuery && !selectedWorker) {
        setLoading(true);
        try {
          const worker = await getWorkerByIdOrEmployeeId(workerIdFromQuery);
          if (worker) {
            setSelectedWorker(worker);
            setSearchResults([]);
            setSearchQuery('');
            setHistoryLoading(true);
            try {
              const history = await fetchWorkerHistory(worker.id);
              setWorkerHistory(history);
            } finally {
              setHistoryLoading(false);
            }
          }
        } finally {
          setLoading(false);
        }
      }
    };
    fetchByWorkerId();
    // فقط عند تغيّر workerIdFromQuery
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workerIdFromQuery, getWorkerByIdOrEmployeeId]);

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;
    setLoading(true);
    try {
      const results = await findWorkerAsync(searchQuery);
      setSearchResults(results);
    } catch (error) {
      console.error('Search error:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectWorker = async (worker: Worker) => {
    setSelectedWorker(worker);
    setSearchResults([]);
    setSearchQuery('');
    setHistoryLoading(true);
    try {
      const history = await fetchWorkerHistory(worker.id);
      setWorkerHistory(history);
    } catch (error) {
      console.error('Error loading history:', error);
    } finally {
      setHistoryLoading(false);
    }
  };

  const currentOccupancy = useMemo(() => {
    if (!selectedWorker) return null;
    return occupants.find(o => o.workerId === selectedWorker.id && !o.until);
  }, [occupants, selectedWorker]);

  const getResidenceName = (residenceId: string) => {
    return residences.find(r => r.id === residenceId)?.name || residenceId;
  };

  const getRoomFullPath = (residenceId: string, roomId: string) => {
    const residence = residences.find(r => r.id === residenceId);
    if (!residence) return { city: '', housing: '', building: '', floor: '', room: roomId, fullPath: roomId };

    const city = residence.city || '';
    const housing = residence.name || '';

    // Try hierarchical structure (buildings -> floors -> rooms)
    if (residence.buildings) {
      for (const building of residence.buildings) {
        for (const floor of building.floors || []) {
          const room = floor.rooms?.find(r => r.id === roomId);
          if (room) {
            return {
              city,
              housing,
              building: building.name || '',
              floor: floor.name || '',
              room: room.name || roomId,
              fullPath: [building.name, floor.name, room.name].filter(Boolean).join(' > ') || roomId
            };
          }
        }
      }
    }

    // Fallback to flat structure
    if (residence.rooms) {
      const room = residence.rooms.find(r => r.id === roomId);
      if (room?.name) return { city, housing, building: '', floor: '', room: room.name, fullPath: room.name };
    }

    return { city, housing, building: '', floor: '', room: roomId, fullPath: roomId };
  };

  const getCompanyName = (companyName?: string) => {
    if (!companyName) return t.notSpecified;
    const company = companies.find(c => 
      c.name === companyName || c.nameAr === companyName || c.nameEn === companyName
    );
    if (locale === 'ar') {
      return company?.nameAr || company?.name || companyName;
    }
    return company?.nameEn || company?.name || companyName;
  };

  const stats = useMemo(() => {
    const checkIns = workerHistory.filter(h => h.actionType === 'CHECK_IN').length;
    const checkOuts = workerHistory.filter(h => h.actionType === 'CHECK_OUT').length;
    const swaps = workerHistory.filter(h => h.actionType === 'TRANSFER' || h.actionType === 'SWAP').length;
    
    let totalDays = 0;
    
    // ترتيب السجلات حسب التاريخ (الأقدم أولاً)
    const sortedHistory = [...workerHistory].sort((a, b) => 
      new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime()
    );
    
    // حساب الأيام بين كل CHECK_IN و CHECK_OUT المقابل له
    let lastCheckInDate: Date | null = null;
    
    for (const record of sortedHistory) {
      if (record.actionType === 'CHECK_IN') {
        lastCheckInDate = new Date(record.actionDate);
        lastCheckInDate.setHours(0, 0, 0, 0);
      } else if (record.actionType === 'CHECK_OUT' && lastCheckInDate) {
        const checkOutDate = new Date(record.actionDate);
        checkOutDate.setHours(0, 0, 0, 0);
        const diffTime = checkOutDate.getTime() - lastCheckInDate.getTime();
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        // +1 لاحتساب يوم الدخول
        totalDays += Math.max(diffDays + 1, 1);
        lastCheckInDate = null;
      }
    }

    // إضافة أيام الإقامة الحالية إذا كان مُسكّناً
    if (currentOccupancy) {
      const sinceDate = new Date(currentOccupancy.since);
      const today = new Date();
      sinceDate.setHours(0, 0, 0, 0);
      today.setHours(0, 0, 0, 0);
      const diffTime = today.getTime() - sinceDate.getTime();
      const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      // +1 لاحتساب يوم الدخول
      totalDays += diffDays + 1;
    }

    return { checkIns, checkOuts, swaps, totalDays };
  }, [workerHistory, currentOccupancy]);

  // Get condensed history for print (first 2 + last 4)
  const condensedHistory = useMemo(() => {
    if (workerHistory.length <= 6) return { items: workerHistory, skipped: 0 };
    const first4 = workerHistory.slice(-4); // oldest 4
    const last2 = workerHistory.slice(0, 2); // newest 2
    return { 
      items: [...last2, ...first4],
      skipped: workerHistory.length - 6 
    };
  }, [workerHistory]);

  // Group check-in / check-out periods for visual grouping
  const groupedHistory = useMemo(() => {
    // Use chronological order (oldest first) to find CHECK_IN -> next CHECK_OUT pairs
    const asc = [...workerHistory].slice().sort((a, b) => new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime());
    const groups: Array<any> = [];
    let i = 0;
    while (i < asc.length) {
      const cur = asc[i];
      if (cur.actionType === 'CHECK_IN') {
        // find the next CHECK_OUT (skip TRANSFER and other events between)
        let j = i + 1;
        while (j < asc.length && asc[j].actionType !== 'CHECK_OUT') j++;
        if (j < asc.length) {
          // group from i..j (inclusive)
          groups.push({ type: 'period', items: asc.slice(i, j + 1) });
          i = j + 1;
        } else {
          // open period (no checkout found) - include remaining items
          groups.push({ type: 'period', items: asc.slice(i) });
          break;
        }
      } else {
        // single record (CHECK_OUT without prior CHECK_IN or TRANSFER outside periods)
        groups.push({ type: 'single', item: cur });
        i += 1;
      }
    }
    return groups;
  }, [workerHistory]);

  // Utility: checkout label translation (defined before summarization to avoid temporal dead zone)
  function getCheckoutLabel(checkoutType?: string | null) {
    if (!checkoutType) return null;
    let label = checkoutType;
    // Normalize room-transfer naming: treat 'Transfer' and 'Swap' as the same concept
    if (checkoutType === 'Transfer' || checkoutType === 'Swap') {
      return t.transfer; // already localized (Swap / تبديل)
    }
    if (locale === 'ar') {
      if (checkoutType === 'Exit') return 'خروج';
      else if (checkoutType === 'Vacation') return 'إجازة';
    }
    return label;
  }

  // Summarize grouped periods into single-row summaries for Recent Movement History
  const summarizedHistory = useMemo(() => {
    const summaries: Array<any> = [];
    const fmtResidence = (rName?: string, roomName?: string) => rName ? (roomName ? `${rName} • ${roomName}` : rName) : t.notSpecified;

    for (const g of groupedHistory) {
      if (g.type === 'single') {
        const item = g.item as AccommodationHistory;
        const startNotes = item.actionType === 'CHECK_IN' ? [item.reason ? `(${item.reason})` : null, item.notes ? `"${item.notes}"` : null].filter(Boolean).join(' ') : '—';
        const endNotes = item.actionType === 'CHECK_OUT' ? [getCheckoutLabel((item as any).checkoutType), item.reason ? `(${item.reason})` : null, item.notes ? `"${item.notes}"` : null].filter(Boolean).join(' ') : '—';
        summaries.push({
          id: item.id,
          startDate: new Date(item.actionDate),
          endDate: null,
          actionLabel: getActionLabel(item.actionType),
          residence: fmtResidence(item.residenceName, item.roomName),
          startNotes,
          endNotes,
          duration: item.actionType === 'CHECK_OUT' ? getFormattedDuration(item) : '—'
        });
      } else if (g.type === 'period') {
        const items = g.items as AccommodationHistory[];
        const start = items[0];
        const end = items[items.length - 1];
        const transfers = items.filter(i => i.actionType === 'TRANSFER' || i.actionType === 'SWAP');
        const hasCheckout = end && end.actionType === 'CHECK_OUT';

        // Build residence summary: include transfers and destination room when available
        const fmtTransferPath = () => {
          if (transfers.length === 0) return null;
          // map to last transfer destination that has a room; if missing, try to infer from following CHECK_IN (period or global)
          const last = transfers[transfers.length - 1];

          // attempt direct fields first
          let destResidence: string | null = last.toResidenceName || last.residenceName || null;
          let destRoom: string | null = last.toRoomName || last.roomName || null;

          // if no destRoom, try to find a CHECK_IN record after this transfer inside the period
          if (!destRoom) {
            const transferIndex = items.indexOf(last);
            if (transferIndex >= 0) {
              for (let k = transferIndex + 1; k < items.length; k++) {
                const next = items[k];
                if (next.actionType === 'CHECK_IN' && next.roomName) {
                  destRoom = next.roomName;
                  destResidence = destResidence || (next.residenceName || null);
                  break;
                }
              }
            }
          }

          // still no destRoom: search the full workerHistory for the next CHECK_IN after the transfer time
          if (!destRoom) {
            const transferTime = new Date(last.actionDate).getTime();
            const futureCheckIn = workerHistory.find(h => new Date(h.actionDate).getTime() > transferTime && h.actionType === 'CHECK_IN' && h.roomName);
            if (futureCheckIn) {
              destRoom = futureCheckIn.roomName || null;
              destResidence = destResidence || (futureCheckIn.residenceName || null);
            }
          }

          // Build final string: if destination residence equals start residence, show only room number on right side
          const startRes = fmtResidence(start.residenceName, start.roomName);
          if (destResidence && destResidence === start.residenceName) {
            // show only room number if available
            return destRoom ? `${startRes} → ${destRoom}` : startRes;
          }

          // otherwise show full dest residence/room; if no dest found, show start only
          if (!destResidence && !destRoom) return startRes;
          const dest = fmtResidence(destResidence || undefined, destRoom || undefined);
          return `${startRes} → ${dest}`;
        };

        let residenceSummary: string;
        if (hasCheckout) {
          residenceSummary = transfers.length > 0 ? `${fmtResidence(start.residenceName, start.roomName)} → ${fmtResidence(end.residenceName, end.roomName)}` : fmtResidence(start.residenceName, start.roomName);
        } else {
          // No checkout: if there is a transfer, show start → last transfer destination; otherwise show start only
          if (transfers.length > 0) {
            residenceSummary = fmtTransferPath()!; // e.g. "Gypsum • 11 → Gypsum • 12"
          } else {
            residenceSummary = fmtResidence(start.residenceName, start.roomName);
          }
        }

        // start notes: from start record
        const startParts = [] as string[];
        if (start.reason) startParts.push(`(${start.reason})`);
        if (start.notes) startParts.push(`"${start.notes}"`);
        const startNotes = startParts.length ? startParts.join(' ') : '—';

        // end notes: checkout label + end record notes + include transfer notes count
        const endParts = [] as string[];
        if (hasCheckout) {
          const checkoutLabel = getCheckoutLabel((end as any).checkoutType);
          if (checkoutLabel) endParts.push(checkoutLabel);
          if (end.reason) endParts.push(`(${end.reason})`);
          if (end.notes) endParts.push(`"${end.notes}"`);
        }
        if (transfers.length > 0) endParts.push(`(${transfers.length} ${t.transfers})`);
        const endNotes = endParts.length ? endParts.join(' ') : '—';

        // compute duration: if checkout exists, use end; otherwise use current date
        let duration = '—';
        if (start) {
          const s = new Date(start.actionDate); s.setHours(0,0,0,0);
          const e = hasCheckout ? (new Date((end as AccommodationHistory).actionDate)) : new Date();
          e.setHours(0,0,0,0);
          const diff = Math.floor((e.getTime() - s.getTime()) / (1000*60*60*24));
          duration = `${Math.max(diff + 1, 1)}d`;
        }

        summaries.push({
          id: start.id + '_' + (hasCheckout ? end.id : 'open'),
          startDate: new Date(start.actionDate),
          endDate: hasCheckout ? new Date(end.actionDate) : null,
          actionLabel: `${t.checkIn} → ${t.checkOut}`,
          residence: residenceSummary,
          startNotes,
          endNotes,
          duration
        });
      }
    }
    return summaries;
  }, [groupedHistory]);

  const handlePrint = () => window.print();

  // Use the latest CHECK_IN date (if available) as the 'last entry' date to show on the certificate
  const lastCheckIn = useMemo(() => {
    if (!workerHistory || workerHistory.length === 0) return null;
    const checkIns = [...workerHistory].filter(h => h.actionType === 'CHECK_IN');
    if (checkIns.length === 0) return null;
    // newest first
    checkIns.sort((a, b) => new Date(b.actionDate).getTime() - new Date(a.actionDate).getTime());
    return checkIns[0].actionDate;
  }, [workerHistory]);

  const getRoleLabel = (role?: string) => {
    switch (role) {
      case 'Supervisor': return t.supervisor;
      case 'Engineer': return t.engineer;
      default: return t.worker;
    }
  };

  const getStatusBadge = (status?: string) => {
    switch (status) {
      case 'Active':
        return <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100">{t.active}</Badge>;
      case 'Transferring':
        return <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-100">{t.transferring}</Badge>;
      case 'Vacation':
        return <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100">{t.vacation}</Badge>;
      case 'Exit':
        return <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-100">{t.exit}</Badge>;
      default:
        return <Badge variant="outline">{t.notSpecified}</Badge>;
    }
  };

  const getActionLabel = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return t.checkIn;
      case 'CHECK_OUT': return t.checkOut;
      case 'TRANSFER': return t.transfer;
      case 'SWAP': return t.swap;
      default: return type;
    }
  };

  const getActionColor = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return 'text-green-700 bg-green-50';
      case 'CHECK_OUT': return 'text-red-700 bg-red-50';
      case 'TRANSFER': return 'text-blue-700 bg-blue-50';
      case 'SWAP': return 'text-purple-700 bg-purple-50';
      default: return 'text-gray-700 bg-gray-50';
    }
  };



  const calculateDays = (since: string) => {
    // احتساب عدد الأيام بما في ذلك يوم الدخول ويوم اليوم الحالي
    const sinceDate = new Date(since);
    const today = new Date();
    // تصفير الوقت للحصول على فرق الأيام فقط
    sinceDate.setHours(0, 0, 0, 0);
    today.setHours(0, 0, 0, 0);
    const diffTime = today.getTime() - sinceDate.getTime();
    const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
    // +1 لاحتساب يوم الدخول نفسه
    const days = diffDays + 1;
    return `${days} ${days === 1 ? t.day : t.days}`;
  };

  // تنسيق المدة بالسنوات والشهور والأيام
  const formatDuration = (totalDays: number): string => {
    if (totalDays <= 0) return '—';
    
    const years = Math.floor(totalDays / 365);
    const remainingAfterYears = totalDays % 365;
    const months = Math.floor(remainingAfterYears / 30);
    const days = remainingAfterYears % 30;
    
    const parts: string[] = [];
    
    if (years > 0) {
      parts.push(locale === 'ar' ? `${years}س` : `${years}y`);
    }
    if (months > 0) {
      parts.push(locale === 'ar' ? `${months}ش` : `${months}m`);
    }
    if (days > 0 || parts.length === 0) {
      parts.push(locale === 'ar' ? `${days}ي` : `${days}d`);
    }
    
    return parts.join(' ');
  };

  // حساب المدة لكل CHECK_OUT من سجلات CHECK_IN المقابلة
  const historyWithDurations = useMemo(() => {
    // ترتيب السجلات حسب التاريخ (الأقدم أولاً)
    const sortedHistory = [...workerHistory].sort((a, b) => 
      new Date(a.actionDate).getTime() - new Date(b.actionDate).getTime()
    );
    
    // Map لتخزين آخر تاريخ دخول
    let lastCheckInDate: Date | null = null;
    
    // Map لتخزين المدة لكل CHECK_OUT
    const durationsMap = new Map<string, number>();
    
    for (const record of sortedHistory) {
      if (record.actionType === 'CHECK_IN') {
        lastCheckInDate = new Date(record.actionDate);
        lastCheckInDate.setHours(0, 0, 0, 0);
      } else if (record.actionType === 'CHECK_OUT' && lastCheckInDate) {
        const checkOutDate = new Date(record.actionDate);
        checkOutDate.setHours(0, 0, 0, 0);
        const diffTime = checkOutDate.getTime() - lastCheckInDate.getTime();
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
        const duration = Math.max(diffDays + 1, 1); // +1 لاحتساب يوم الدخول
        durationsMap.set(record.id, duration);
        lastCheckInDate = null;
      }
    }
    
    return durationsMap;
  }, [workerHistory]);

  // دالة للحصول على المدة المنسقة لسجل معين
  const getFormattedDuration = (item: AccommodationHistory): string | null => {
    if (item.actionType !== 'CHECK_OUT') return null;
    
    // أولاً نحاول الحصول على المدة المحسوبة دينامياً
    const calculatedDuration = historyWithDurations.get(item.id);
    if (calculatedDuration) {
      return formatDuration(calculatedDuration);
    }
    
    // ثانياً نحاول استخدام المدة المخزنة
    if (item.duration) {
      return formatDuration(item.duration);
    }
    
    return null;
  };

  const documentNo = useMemo(() => {
    if (!selectedWorker) return '';
    const date = new Date();
    return `ACC-${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}-${selectedWorker.employeeId || selectedWorker.id.slice(-4)}`;
  }, [selectedWorker]);

  return (
    <div className="min-h-screen bg-background">
      {/* Search Section - Hidden in print */}
      <div className="print:hidden p-6 border-b bg-card">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-3 mb-4">
            <FileText className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-2xl font-bold">{t.pageTitle}</h1>
              <p className="text-muted-foreground text-sm">{t.pageDescription}</p>
            </div>
          </div>

          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground`} />
              <Input
                placeholder={t.searchPlaceholder}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                className={isRTL ? 'pr-10' : 'pl-10'}
              />
            </div>
            <Button onClick={handleSearch} disabled={loading}>
              {loading ? t.searching : t.search}
            </Button>
          </div>

          {searchResults.length > 0 && (
            <Card className="mt-4">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">{t.searchResults} ({searchResults.length})</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y max-h-64 overflow-auto">
                  {searchResults.map((worker) => (
                    <button
                      key={worker.id}
                      onClick={() => handleSelectWorker(worker)}
                      className={`w-full p-4 ${isRTL ? 'text-right' : 'text-left'} hover:bg-accent transition-colors flex items-center justify-between`}
                    >
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <User className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <div className="font-medium">{worker.name}</div>
                          <div className="text-sm text-muted-foreground flex items-center gap-2">
                            {worker.employeeId && <span>#{worker.employeeId}</span>}
                            {worker.nationaliy && <span>• {worker.nationaliy}</span>}
                          </div>
                        </div>
                      </div>
                      {getStatusBadge(worker.status)}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Certificate Content */}
      {selectedWorker && (
        <>
          {/* Action Buttons - Hidden in print */}
          <div className="print:hidden p-4 max-w-4xl mx-auto flex justify-between items-center">
            <Button variant="outline" onClick={() => setSelectedWorker(null)}>
              {t.selectAnotherWorker}
            </Button>
            <Button onClick={handlePrint} className="gap-2">
              <Printer className="h-4 w-4" />
              {t.printCertificate}
            </Button>
          </div>

          {/* Printable Certificate - Single Page Design */}
          <div className="max-w-4xl mx-auto p-4 print:p-0 print:max-w-none print:m-0">
            <div className="bg-white text-black print:bg-white rounded-lg border-2 border-gray-300 print:border print:border-gray-400 overflow-hidden flex flex-col print:min-h-[277mm] print:h-[277mm]" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>
              
              {/* Header */}
              <div className="bg-gradient-to-r from-slate-800 to-slate-700 text-white px-4 py-2.5 print:px-3 print:py-2 print:bg-slate-800 flex-shrink-0" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-9 h-9 bg-white/20 rounded-lg flex items-center justify-center">
                      <Building2 className="h-5 w-5 text-white" />
                    </div>
                    <div>
                      <h1 className="text-base font-bold tracking-wide">{t.certificateTitle}</h1>
                      <p className="text-slate-300 text-xs">{t.certificateSubtitle}</p>
                    </div>
                  </div>
                  <div className="text-right text-xs">
                    <div className="text-slate-300">{t.documentNo}</div>
                    <div className="font-mono font-bold text-sm">{documentNo}</div>
                    <div className="text-slate-300">{t.issueDate}: {format(new Date(), 'dd/MM/yyyy')}</div>
                  </div>
                </div>
              </div>

              {/* Body - Grows to fill available space */}
              <div className="p-3 print:p-2 space-y-2 print:space-y-1.5 flex-grow">
                
                {/* Worker Info + Status Row */}
                <div className="grid grid-cols-3 gap-2 print:gap-1.5">
                  
                  {/* Worker Info */}
                  <div className="col-span-2 border rounded-lg p-2.5 print:p-2">
                    <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                      <User className="h-3 w-3" />
                      {t.workerData}
                    </h3>
                    <div className="space-y-1 text-xs print:text-[11px]">
                      <div className="flex justify-between border-b border-dashed pb-1">
                        <span className="text-slate-500">{t.fullName}</span>
                        <span className="font-semibold">{selectedWorker.name}</span>
                      </div>
                      <div className="grid grid-cols-2 gap-x-4 gap-y-1">
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.idNumber}</span>
                          <span className="font-mono text-[10px]">{selectedWorker.idNumber || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.employeeNumber}</span>
                          <span className="font-mono text-[10px]">{selectedWorker.employeeId || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.nationality}</span>
                          <span>{selectedWorker.nationaliy || t.notSpecified}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5">
                          <span className="text-slate-500">{t.jobTitle}</span>
                          <span>{getRoleLabel(selectedWorker.role)}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-0.5 col-span-2">
                          <span className="text-slate-500">{t.company}</span>
                          <span>{getCompanyName(selectedWorker.company)}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Current Status */}
                  <div className="border rounded-lg p-2 print:p-1.5 bg-gradient-to-br from-slate-50 to-white">
                    <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                      <Home className="h-3 w-3" />
                      {t.currentStatus}
                    </h3>
                    {currentOccupancy ? (
                      <div className="space-y-1.5">
                        {/* Status Badge */}
                        <div className="flex items-center gap-1.5 bg-green-100 text-green-800 font-semibold px-2 py-1 rounded border border-green-200 text-xs">
                          <CheckCircle2 className="h-3.5 w-3.5 flex-shrink-0" />
                          <span>{t.currentlyAccommodated}</span>
                        </div>
                        
                        {/* Location Details */}
                        {(() => {
                          const roomPath = getRoomFullPath(currentOccupancy.residenceId, currentOccupancy.roomId);
                          return (
                            <div className="grid grid-cols-2 gap-1">
                              <div className="bg-amber-50 px-1.5 py-0.5 rounded border border-amber-200 text-center">
                                <div className="text-[7px] text-amber-600 font-semibold uppercase">{t.city}</div>
                                <div className="text-[10px] font-bold text-amber-900 truncate">{roomPath.city || '—'}</div>
                              </div>
                              <div className="bg-sky-50 px-1.5 py-0.5 rounded border border-sky-200 text-center">
                                <div className="text-[7px] text-sky-600 font-semibold uppercase">{t.housing}</div>
                                <div className="text-[10px] font-bold text-sky-900 truncate">{roomPath.housing}</div>
                              </div>
                              <div className="bg-indigo-50 px-1.5 py-0.5 rounded border border-indigo-200 text-center">
                                <div className="text-[7px] text-indigo-600 font-semibold uppercase">{t.building}</div>
                                <div className="text-[10px] font-bold text-indigo-900">{roomPath.building || '—'}</div>
                              </div>
                              <div className="bg-violet-50 px-1.5 py-0.5 rounded border border-violet-200 text-center">
                                <div className="text-[7px] text-violet-600 font-semibold uppercase">{t.floor}</div>
                                <div className="text-[10px] font-bold text-violet-900">{roomPath.floor || '—'}</div>
                              </div>
                              <div className="col-span-2 bg-emerald-50 px-1.5 py-0.5 rounded border border-emerald-200 text-center">
                                <div className="text-[7px] text-emerald-600 font-semibold uppercase">{t.room}</div>
                                <div className="text-[10px] font-bold text-emerald-900">{roomPath.room}</div>
                              </div>
                            </div>
                          );
                        })()}
                        
                        {/* Date & Duration */}
                        <div className="flex items-center justify-between text-[10px] text-slate-600 pt-1 border-t border-slate-200">
                          <span className="flex items-center gap-0.5">
                            <Calendar className="h-2.5 w-2.5" />
                            {lastCheckIn ? format(new Date(lastCheckIn), 'dd/MM/yyyy') : format(new Date(currentOccupancy.since), 'dd/MM/yyyy')}
                          </span>
                          <span className="flex items-center gap-0.5 bg-slate-100 px-1 py-0.5 rounded-full font-medium">
                            <Clock className="h-2.5 w-2.5" />
                            {calculateDays(lastCheckIn || currentOccupancy.since)}
                          </span>
                        </div>
                      </div>
                    ) : (
                      <div className="flex items-center gap-1.5 bg-orange-100 text-orange-800 font-semibold px-2 py-1.5 rounded border border-orange-200 text-xs">
                        <AlertCircle className="h-3.5 w-3.5 flex-shrink-0" />
                        <span>{t.notCurrentlyAccommodated}</span>
                      </div>
                    )}
                  </div>
                </div>

                {/* Statistics Row */}
                <div className="border rounded-lg p-2 print:p-1.5">
                  <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                    <TrendingUp className="h-3 w-3" />
                    {t.summary}
                  </h3>
                  <div className="grid grid-cols-4 gap-2 print:gap-1.5">
                    <div className="text-center p-1.5 bg-green-50 rounded border border-green-100">
                      <div className="text-lg font-bold text-green-700">{stats.checkIns}</div>
                      <div className="text-[9px] text-green-600">{t.checkIns}</div>
                    </div>
                    <div className="text-center p-1.5 bg-red-50 rounded border border-red-100">
                      <div className="text-lg font-bold text-red-700">{stats.checkOuts}</div>
                      <div className="text-[9px] text-red-600">{t.checkOuts}</div>
                    </div>
                    <div className="text-center p-1.5 bg-blue-50 rounded border border-blue-100">
                      <div className="text-lg font-bold text-blue-700">{stats.swaps}</div>
                      <div className="text-[9px] text-blue-600">{t.transfers}</div>
                    </div>
                    <div className="text-center p-1.5 bg-purple-50 rounded border border-purple-100">
                      <div className="text-lg font-bold text-purple-700">{stats.totalDays}</div>
                      <div className="text-[9px] text-purple-600">{t.totalDays}</div>
                    </div>
                  </div>
                </div>

                {/* Movement History - Organized */}
                <div className="border rounded-lg p-2 print:p-1.5">
                  <h3 className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-1 flex items-center gap-1">
                    <Clock className="h-3 w-3" />
                    {t.recentHistory}
                  </h3>
                  {historyLoading ? (
                    <div className="text-center text-slate-400 py-2 text-xs">Loading...</div>
                  ) : workerHistory.length === 0 ? (
                    <div className="text-center text-slate-400 py-2 text-xs">No records</div>
                  ) : (
                    <table className="w-full text-[10px]">
                      <thead>
                        <tr className="text-left text-slate-500">
                          <th className="px-2 py-1">{t.checkIn}</th>
                          <th className="px-2 py-1">Date</th>
                          <th className="px-2 py-1">Details</th>
                          <th className="px-2 py-1">{t.checkInNotes}</th>
                          <th className="px-2 py-1">{t.checkOut}</th>
                          <th className="px-2 py-1">Date</th>
                          <th className="px-2 py-1">{t.checkOutNotes}</th>
                          <th className="px-2 py-1">Duration</th>
                        </tr>
                      </thead>
                      <tbody>
                        {/* Summarized view: one row per period or single event — newest first */}
                        {[...summarizedHistory].reverse().map((s) => (
                          <tr key={s.id} className="border-b border-dashed last:border-0">
                            <td className="px-2 py-1"><span className={`px-2 py-0.5 rounded font-medium ${getActionColor('CHECK_IN')}`}>{t.checkIn}</span></td>
                            <td className="px-2 py-1 text-slate-500 font-mono">{format(s.startDate, 'dd/MM/yyyy')}</td>
                            <td className="px-2 py-1 text-slate-700 truncate">{s.residence}</td>
                            <td className="px-2 py-1 text-slate-700 truncate">{s.startNotes}</td>
                            <td className="px-2 py-1">{s.endDate ? <span className={`px-2 py-0.5 rounded font-medium ${getActionColor('CHECK_OUT')}`}>{t.checkOut}</span> : <span className="text-slate-400">—</span>}</td>
                            <td className="px-2 py-1 text-slate-500 font-mono">{s.endDate ? format(s.endDate, 'dd/MM/yyyy') : '—'}</td>
                            <td className="px-2 py-1 text-left text-slate-700 truncate">{s.endNotes}</td>
                            <td className="px-2 py-1 text-orange-600 font-medium bg-orange-50 rounded text-right">{s.duration}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  )}
                </div>
              </div>

              {/* Footer - Always at bottom */}
              <div className="p-3 print:p-2 border-t border-slate-200 flex-shrink-0 mt-auto">
                {/* Signature Area */}
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center">
                    <div className="h-10 print:h-8 border-2 border-dashed border-slate-300 rounded flex items-center justify-center text-slate-400">
                      <span className="text-[9px] uppercase tracking-wider">{t.stamp}</span>
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="h-10 print:h-8 border-b-2 border-slate-400"></div>
                    <span className="text-[9px] text-slate-500 uppercase tracking-wider">{t.signature}</span>
                  </div>
                </div>

                {/* Generated By Footer */}
                <div className="text-center text-[9px] text-slate-400 pt-2 mt-2 border-t border-dashed">
                  {t.generatedBy} • {format(new Date(), 'dd/MM/yyyy HH:mm')}
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {/* Empty State */}
      {!selectedWorker && searchResults.length === 0 && (
        <div className="flex items-center justify-center min-h-[60vh] print:hidden">
          <div className="text-center max-w-md">
            <FileText className="h-20 w-20 mx-auto mb-6 text-muted-foreground opacity-50" />
            <h2 className="text-2xl font-semibold mb-2">{t.emptyStateTitle}</h2>
            <p className="text-muted-foreground mb-6">{t.emptyStateDescription}</p>
            <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <User className="h-4 w-4" />
                {t.workerInfo}
              </div>
              <div className="flex items-center gap-2">
                <Home className="h-4 w-4" />
                {t.accommodationStatus}
              </div>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4" />
                {t.history}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 5mm;
          }
          
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            background: white !important;
            font-size: 10px !important;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          /* Force colors */
          .bg-gradient-to-r {
            background: #1e293b !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          .bg-green-50 { background-color: #f0fdf4 !important; }
          .bg-red-50 { background-color: #fef2f2 !important; }
          .bg-blue-50 { background-color: #eff6ff !important; }
          .bg-purple-50 { background-color: #faf5ff !important; }
          
          .text-green-700 { color: #15803d !important; }
          .text-red-700 { color: #b91c1c !important; }
          .text-blue-700 { color: #1d4ed8 !important; }
          .text-purple-700 { color: #7c3aed !important; }
          
          .border-green-100 { border-color: #dcfce7 !important; }
          .border-red-100 { border-color: #fee2e2 !important; }
          .border-blue-100 { border-color: #dbeafe !important; }
          .border-purple-100 { border-color: #f3e8ff !important; }
        }
      `}</style>
    </div>
  );
}
