"use client";

import React, { useState, useMemo, useRef } from 'react';
import { useRouter } from 'next/navigation';
import { useAccommodation, Worker, AccommodationHistory } from '@/context/accommodation-context';
import { useLanguage } from '@/context/language-context';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { 
  Search,
  Printer,
  User,
  Building2,
  MapPin,
  Calendar,
  Clock,
  LogIn,
  LogOut,
  ArrowRightLeft,
  Repeat2,
  FileText,
  Hash,
  Globe,
  Briefcase,
  Building,
  IdCard,
  CheckCircle2,
  Home,
  TrendingUp,
  AlertCircle,
  MoreHorizontal,
  Layers,
  DoorOpen
} from 'lucide-react';
import { format } from 'date-fns';
import { ar, enUS } from 'date-fns/locale';

// Translation keys
const translations = {
  en: {
    pageTitle: 'Worker Accommodation Certificate',
    pageDescription: 'View complete worker data and accommodation status',
    searchPlaceholder: 'Search by name, ID number, or employee number...',
    search: 'Search',
    searching: 'Searching...',
    searchResults: 'Search Results',
    selectAnotherWorker: 'Select Another Worker',
    printCertificate: 'Print Certificate',
    workerData: 'Worker Information',
    fullName: 'Full Name',
    idNumber: 'ID Number',
    employeeNumber: 'Employee Number',
    nationality: 'Nationality',
    jobTitle: 'Job Title',
    company: 'Company',
    notRegistered: 'N/A',
    notSpecified: 'N/A',
    worker: 'Worker',
    supervisor: 'Supervisor',
    engineer: 'Engineer',
    active: 'Active',
    transferring: 'Transferring',
    vacation: 'Vacation',
    exit: 'Exit',
    currentStatus: 'Current Status',
    currentlyAccommodated: 'Currently Accommodated',
    notCurrentlyAccommodated: 'Not Accommodated',
    accommodationLocation: 'Location',
    roomNumber: 'Room',
    city: 'City',
    housing: 'Housing',
    building: 'Building',
    floor: 'Floor',
    room: 'Room',
    checkInDate: 'Check-in',
    stayDuration: 'Duration',
    days: 'days',
    day: 'day',
    summary: 'Summary',
    checkIns: 'Check-ins',
    checkOuts: 'Check-outs',
    transfers: 'Transfers',
    totalDays: 'Total Days',
    recentHistory: 'Recent Movement History',
    moreRecords: 'more records',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    transfer: 'Transfer',
    swap: 'Swap',
    from: 'From',
    to: 'To',
    certificateTitle: 'WORKER ACCOMMODATION CERTIFICATE',
    certificateSubtitle: 'Official Housing Status Document',
    issueDate: 'Issue Date',
    documentNo: 'Document No',
    signature: 'Authorized Signature',
    stamp: 'Official Stamp',
    generatedBy: 'Generated by Accommodation Management System',
    emptyStateTitle: 'Worker Certificate',
    emptyStateDescription: 'Search for a worker to generate their accommodation certificate',
    workerInfo: 'Worker Info',
    accommodationStatus: 'Status',
    history: 'History',
  },
  ar: {
    pageTitle: 'إفادة سكن موظف',
    pageDescription: 'استعراض بيانات الموظف الكاملة وحالته السكنية',
    searchPlaceholder: 'ابحث بالاسم أو رقم الهوية أو الرقم الوظيفي...',
    search: 'بحث',
    searching: 'جاري البحث...',
    searchResults: 'نتائج البحث',
    selectAnotherWorker: 'اختيار موظف آخر',
    printCertificate: 'طباعة الإفادة',
    workerData: 'بيانات الموظف',
    fullName: 'الاسم',
    idNumber: 'رقم الهوية',
    employeeNumber: 'الرقم الوظيفي',
    nationality: 'الجنسية',
    jobTitle: 'المسمى',
    company: 'الشركة',
    notRegistered: 'غ/م',
    notSpecified: 'غ/م',
    worker: 'عامل',
    supervisor: 'مشرف',
    engineer: 'مهندس',
    active: 'نشط',
    transferring: 'قيد النقل',
    vacation: 'إجازة',
    exit: 'خارج',
    currentStatus: 'الحالة الحالية',
    currentlyAccommodated: 'مُسكّن حالياً',
    notCurrentlyAccommodated: 'غير مُسكّن',
    accommodationLocation: 'الموقع',
    roomNumber: 'الغرفة',
    city: 'المدينة',
    housing: 'المسكن',
    building: 'المبنى',
    floor: 'الطابق',
    room: 'الغرفة',
    checkInDate: 'تاريخ التسكين',
    stayDuration: 'المدة',
    days: 'يوم',
    day: 'يوم',
    summary: 'ملخص',
    checkIns: 'تسكين',
    checkOuts: 'إخراج',
    transfers: 'نقل',
    totalDays: 'إجمالي الأيام',
    recentHistory: 'سجل الحركات الأخيرة',
    moreRecords: 'سجلات إضافية',
    checkIn: 'تسكين',
    checkOut: 'إخراج',
    transfer: 'نقل',
    swap: 'تبديل',
    from: 'من',
    to: 'إلى',
    certificateTitle: 'إفادة سكن موظف',
    certificateSubtitle: 'مستند رسمي لحالة السكن',
    issueDate: 'تاريخ الإصدار',
    documentNo: 'رقم المستند',
    signature: 'توقيع المسؤول',
    stamp: 'الختم الرسمي',
    generatedBy: 'صادر من نظام إدارة السكن',
    emptyStateTitle: 'إفادة سكن موظف',
    emptyStateDescription: 'ابحث عن موظف لإصدار إفادة السكن الخاصة به',
    workerInfo: 'البيانات',
    accommodationStatus: 'الحالة',
    history: 'السجل',
  }
};

export default function WorkerCertificatePage() {
  const { locale } = useLanguage();
  const t = translations[locale] || translations.en;
  const dateLocale = locale === 'ar' ? ar : enUS;
  const isRTL = locale === 'ar';
  
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedWorker, setSelectedWorker] = useState<Worker | null>(null);
  const [searchResults, setSearchResults] = useState<Worker[]>([]);
  const [loading, setLoading] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [workerHistory, setWorkerHistory] = useState<AccommodationHistory[]>([]);

  const { 
    findWorkerAsync,
    fetchWorkerHistory,
    occupants,
    residences,
    companies
  } = useAccommodation();

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;
    setLoading(true);
    try {
      const results = await findWorkerAsync(searchQuery);
      setSearchResults(results);
    } catch (error) {
      console.error('Search error:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSelectWorker = async (worker: Worker) => {
    setSelectedWorker(worker);
    setSearchResults([]);
    setSearchQuery('');
    setHistoryLoading(true);
    try {
      const history = await fetchWorkerHistory(worker.id);
      setWorkerHistory(history);
    } catch (error) {
      console.error('Error loading history:', error);
    } finally {
      setHistoryLoading(false);
    }
  };

  const currentOccupancy = useMemo(() => {
    if (!selectedWorker) return null;
    return occupants.find(o => o.workerId === selectedWorker.id && !o.until);
  }, [occupants, selectedWorker]);

  const getResidenceName = (residenceId: string) => {
    return residences.find(r => r.id === residenceId)?.name || residenceId;
  };

  const getRoomFullPath = (residenceId: string, roomId: string) => {
    const residence = residences.find(r => r.id === residenceId);
    if (!residence) return { city: '', housing: '', building: '', floor: '', room: roomId, fullPath: roomId };

    const city = residence.city || '';
    const housing = residence.name || '';

    // Try hierarchical structure (buildings -> floors -> rooms)
    if (residence.buildings) {
      for (const building of residence.buildings) {
        for (const floor of building.floors || []) {
          const room = floor.rooms?.find(r => r.id === roomId);
          if (room) {
            return {
              city,
              housing,
              building: building.name || '',
              floor: floor.name || '',
              room: room.name || roomId,
              fullPath: [building.name, floor.name, room.name].filter(Boolean).join(' > ') || roomId
            };
          }
        }
      }
    }

    // Fallback to flat structure
    if (residence.rooms) {
      const room = residence.rooms.find(r => r.id === roomId);
      if (room?.name) return { city, housing, building: '', floor: '', room: room.name, fullPath: room.name };
    }

    return { city, housing, building: '', floor: '', room: roomId, fullPath: roomId };
  };

  const getCompanyName = (companyName?: string) => {
    if (!companyName) return t.notSpecified;
    const company = companies.find(c => 
      c.name === companyName || c.nameAr === companyName || c.nameEn === companyName
    );
    if (locale === 'ar') {
      return company?.nameAr || company?.name || companyName;
    }
    return company?.nameEn || company?.name || companyName;
  };

  const stats = useMemo(() => {
    const checkIns = workerHistory.filter(h => h.actionType === 'CHECK_IN').length;
    const checkOuts = workerHistory.filter(h => h.actionType === 'CHECK_OUT').length;
    const transfers = workerHistory.filter(h => h.actionType === 'TRANSFER').length;
    
    let totalDays = 0;
    workerHistory.filter(h => h.actionType === 'CHECK_OUT' && h.duration).forEach(h => {
      totalDays += h.duration || 0;
    });

    if (currentOccupancy) {
      const days = Math.ceil((new Date().getTime() - new Date(currentOccupancy.since).getTime()) / (1000 * 60 * 60 * 24));
      totalDays += days;
    }

    return { checkIns, checkOuts, transfers, totalDays };
  }, [workerHistory, currentOccupancy]);

  // Get condensed history for print (first 2 + last 4)
  const condensedHistory = useMemo(() => {
    if (workerHistory.length <= 6) return { items: workerHistory, skipped: 0 };
    const first2 = workerHistory.slice(-2); // oldest 2
    const last4 = workerHistory.slice(0, 4); // newest 4
    return { 
      items: [...last4, ...first2],
      skipped: workerHistory.length - 6 
    };
  }, [workerHistory]);

  const handlePrint = () => window.print();

  const getRoleLabel = (role?: string) => {
    switch (role) {
      case 'Supervisor': return t.supervisor;
      case 'Engineer': return t.engineer;
      default: return t.worker;
    }
  };

  const getStatusBadge = (status?: string) => {
    switch (status) {
      case 'Active':
        return <Badge className="bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100">{t.active}</Badge>;
      case 'Transferring':
        return <Badge className="bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-100">{t.transferring}</Badge>;
      case 'Vacation':
        return <Badge className="bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100">{t.vacation}</Badge>;
      case 'Exit':
        return <Badge className="bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-100">{t.exit}</Badge>;
      default:
        return <Badge variant="outline">{t.notSpecified}</Badge>;
    }
  };

  const getActionLabel = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return t.checkIn;
      case 'CHECK_OUT': return t.checkOut;
      case 'TRANSFER': return t.transfer;
      case 'SWAP': return t.swap;
      default: return type;
    }
  };

  const getActionColor = (type: string) => {
    switch (type) {
      case 'CHECK_IN': return 'text-green-700 bg-green-50';
      case 'CHECK_OUT': return 'text-red-700 bg-red-50';
      case 'TRANSFER': return 'text-blue-700 bg-blue-50';
      case 'SWAP': return 'text-purple-700 bg-purple-50';
      default: return 'text-gray-700 bg-gray-50';
    }
  };

  const calculateDays = (since: string) => {
    const days = Math.ceil((new Date().getTime() - new Date(since).getTime()) / (1000 * 60 * 60 * 24));
    return `${days} ${t.days}`;
  };

  const documentNo = useMemo(() => {
    if (!selectedWorker) return '';
    const date = new Date();
    return `ACC-${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}-${selectedWorker.employeeId || selectedWorker.id.slice(-4)}`;
  }, [selectedWorker]);

  return (
    <div className="min-h-screen bg-background">
      {/* Search Section - Hidden in print */}
      <div className="print:hidden p-6 border-b bg-card">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-3 mb-4">
            <FileText className="h-8 w-8 text-primary" />
            <div>
              <h1 className="text-2xl font-bold">{t.pageTitle}</h1>
              <p className="text-muted-foreground text-sm">{t.pageDescription}</p>
            </div>
          </div>

          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className={`absolute ${isRTL ? 'right-3' : 'left-3'} top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground`} />
              <Input
                placeholder={t.searchPlaceholder}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                className={isRTL ? 'pr-10' : 'pl-10'}
              />
            </div>
            <Button onClick={handleSearch} disabled={loading}>
              {loading ? t.searching : t.search}
            </Button>
          </div>

          {searchResults.length > 0 && (
            <Card className="mt-4">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">{t.searchResults} ({searchResults.length})</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y max-h-64 overflow-auto">
                  {searchResults.map((worker) => (
                    <button
                      key={worker.id}
                      onClick={() => handleSelectWorker(worker)}
                      className={`w-full p-4 ${isRTL ? 'text-right' : 'text-left'} hover:bg-accent transition-colors flex items-center justify-between`}
                    >
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                          <User className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <div className="font-medium">{worker.name}</div>
                          <div className="text-sm text-muted-foreground flex items-center gap-2">
                            {worker.employeeId && <span>#{worker.employeeId}</span>}
                            {worker.nationaliy && <span>• {worker.nationaliy}</span>}
                          </div>
                        </div>
                      </div>
                      {getStatusBadge(worker.status)}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Certificate Content */}
      {selectedWorker && (
        <>
          {/* Action Buttons - Hidden in print */}
          <div className="print:hidden p-4 max-w-4xl mx-auto flex justify-between items-center">
            <Button variant="outline" onClick={() => setSelectedWorker(null)}>
              {t.selectAnotherWorker}
            </Button>
            <Button onClick={handlePrint} className="gap-2">
              <Printer className="h-4 w-4" />
              {t.printCertificate}
            </Button>
          </div>

          {/* Printable Certificate - Single Page Design */}
          <div className="max-w-4xl mx-auto p-6 print:p-0 print:max-w-none">
            <div className="bg-white text-black print:bg-white rounded-lg border-2 border-gray-300 print:border-2 print:border-gray-400 overflow-hidden" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>
              
              {/* Header */}
              <div className="bg-gradient-to-r from-slate-800 to-slate-700 text-white px-6 py-4 print:bg-slate-800" style={{ printColorAdjust: 'exact', WebkitPrintColorAdjust: 'exact' }}>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 bg-white/20 rounded-lg flex items-center justify-center">
                      <Building2 className="h-7 w-7 text-white" />
                    </div>
                    <div>
                      <h1 className="text-xl font-bold tracking-wide">{t.certificateTitle}</h1>
                      <p className="text-slate-300 text-sm">{t.certificateSubtitle}</p>
                    </div>
                  </div>
                  <div className="text-right text-sm">
                    <div className="text-slate-300">{t.documentNo}</div>
                    <div className="font-mono font-bold">{documentNo}</div>
                    <div className="text-slate-300 mt-1">{t.issueDate}</div>
                    <div className="font-medium">{format(new Date(), 'dd/MM/yyyy')}</div>
                  </div>
                </div>
              </div>

              {/* Body */}
              <div className="p-5 space-y-4">
                
                {/* Worker Info + Status Row */}
                <div className="grid grid-cols-3 gap-4">
                  
                  {/* Worker Info */}
                  <div className="col-span-2 border rounded-lg p-4">
                    <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                      <User className="h-3.5 w-3.5" />
                      {t.workerData}
                    </h3>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between border-b border-dashed pb-1.5">
                        <span className="text-slate-500">{t.fullName}</span>
                        <span className="font-semibold">{selectedWorker.name}</span>
                      </div>
                      <div className="grid grid-cols-2 gap-x-6 gap-y-2">
                        <div className="flex justify-between border-b border-dashed pb-1">
                          <span className="text-slate-500">{t.idNumber}</span>
                          <span className="font-mono">{selectedWorker.idNumber || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-1">
                          <span className="text-slate-500">{t.employeeNumber}</span>
                          <span className="font-mono">{selectedWorker.employeeId || t.notRegistered}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-1">
                          <span className="text-slate-500">{t.nationality}</span>
                          <span>{selectedWorker.nationaliy || t.notSpecified}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-1">
                          <span className="text-slate-500">{t.jobTitle}</span>
                          <span>{getRoleLabel(selectedWorker.role)}</span>
                        </div>
                        <div className="flex justify-between border-b border-dashed pb-1 col-span-2">
                          <span className="text-slate-500">{t.company}</span>
                          <span>{getCompanyName(selectedWorker.company)}</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Current Status */}
                  <div className="border rounded-lg p-4">
                    <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                      <Home className="h-3.5 w-3.5" />
                      {t.currentStatus}
                    </h3>
                    {currentOccupancy ? (
                      <div className="space-y-2">
                        <div className="flex items-center gap-2 text-green-700 font-semibold">
                          <CheckCircle2 className="h-5 w-5" />
                          {t.currentlyAccommodated}
                        </div>
                        <div className="text-xs space-y-1.5 text-slate-600">
                          <div className="flex items-center gap-1">
                            <MapPin className="h-3 w-3" />
                            {getResidenceName(currentOccupancy.residenceId)}
                          </div>
                          <div className="space-y-1.5">
                            {(() => {
                              const roomPath = getRoomFullPath(currentOccupancy.residenceId, currentOccupancy.roomId);
                              return (
                                <>
                                  {/* Row 1: City & Housing */}
                                  <div className="grid grid-cols-2 gap-1.5">
                                    <div className="flex items-center gap-1.5 bg-amber-50 px-2 py-1 rounded border border-amber-100">
                                      <MapPin className="h-3 w-3 text-amber-600 flex-shrink-0" />
                                      <div className="flex-1 min-w-0">
                                        <div className="text-[9px] text-amber-600 font-medium uppercase leading-tight">{t.city}</div>
                                        <div className="text-[11px] font-semibold text-amber-900 truncate">{roomPath.city || '—'}</div>
                                      </div>
                                    </div>
                                    <div className="flex items-center gap-1.5 bg-sky-50 px-2 py-1 rounded border border-sky-100">
                                      <Home className="h-3 w-3 text-sky-600 flex-shrink-0" />
                                      <div className="flex-1 min-w-0">
                                        <div className="text-[9px] text-sky-600 font-medium uppercase leading-tight">{t.housing}</div>
                                        <div className="text-[11px] font-semibold text-sky-900 truncate">{roomPath.housing}</div>
                                      </div>
                                    </div>
                                  </div>

                                  {/* Row 2: Building - Floor - Room */}
                                  <div className="grid grid-cols-3 gap-1.5">
                                    <div className="flex items-center gap-1.5 bg-blue-50 px-2 py-1 rounded border border-blue-100">
                                      <Building className="h-3 w-3 text-blue-600 flex-shrink-0" />
                                      <div className="flex-1 min-w-0">
                                        <div className="text-[9px] text-blue-600 font-medium uppercase leading-tight">{t.building}</div>
                                        <div className="text-[11px] font-semibold text-blue-900 truncate">{roomPath.building || '—'}</div>
                                      </div>
                                    </div>
                                    <div className="flex items-center gap-1.5 bg-purple-50 px-2 py-1 rounded border border-purple-100">
                                      <Layers className="h-3 w-3 text-purple-600 flex-shrink-0" />
                                      <div className="flex-1 min-w-0">
                                        <div className="text-[9px] text-purple-600 font-medium uppercase leading-tight">{t.floor}</div>
                                        <div className="text-[11px] font-semibold text-purple-900 truncate">{roomPath.floor || '—'}</div>
                                      </div>
                                    </div>
                                    <div className="flex items-center gap-1.5 bg-emerald-50 px-2 py-1 rounded border border-emerald-100">
                                      <DoorOpen className="h-3 w-3 text-emerald-600 flex-shrink-0" />
                                      <div className="flex-1 min-w-0">
                                        <div className="text-[9px] text-emerald-600 font-medium uppercase leading-tight">{t.room}</div>
                                        <div className="text-[11px] font-semibold text-emerald-900 truncate">{roomPath.room}</div>
                                      </div>
                                    </div>
                                  </div>
                                </>
                              );
                            })()}
                          </div>
                          <div className="flex items-center gap-1">
                            <Calendar className="h-3 w-3" />
                            {format(new Date(currentOccupancy.since), 'dd/MM/yyyy')}
                          </div>
                          <div className="flex items-center gap-1">
                            <Clock className="h-3 w-3" />
                            {calculateDays(currentOccupancy.since)}
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div className="flex items-center gap-2 text-orange-700 font-semibold">
                        <AlertCircle className="h-5 w-5" />
                        {t.notCurrentlyAccommodated}
                      </div>
                    )}
                  </div>
                </div>

                {/* Statistics Row */}
                <div className="border rounded-lg p-4">
                  <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                    <TrendingUp className="h-3.5 w-3.5" />
                    {t.summary}
                  </h3>
                  <div className="grid grid-cols-4 gap-4">
                    <div className="text-center p-3 bg-green-50 rounded-lg border border-green-100">
                      <div className="text-2xl font-bold text-green-700">{stats.checkIns}</div>
                      <div className="text-xs text-green-600">{t.checkIns}</div>
                    </div>
                    <div className="text-center p-3 bg-red-50 rounded-lg border border-red-100">
                      <div className="text-2xl font-bold text-red-700">{stats.checkOuts}</div>
                      <div className="text-xs text-red-600">{t.checkOuts}</div>
                    </div>
                    <div className="text-center p-3 bg-blue-50 rounded-lg border border-blue-100">
                      <div className="text-2xl font-bold text-blue-700">{stats.transfers}</div>
                      <div className="text-xs text-blue-600">{t.transfers}</div>
                    </div>
                    <div className="text-center p-3 bg-purple-50 rounded-lg border border-purple-100">
                      <div className="text-2xl font-bold text-purple-700">{stats.totalDays}</div>
                      <div className="text-xs text-purple-600">{t.totalDays}</div>
                    </div>
                  </div>
                </div>

                {/* Movement History - Condensed */}
                <div className="border rounded-lg p-4">
                  <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                    <Clock className="h-3.5 w-3.5" />
                    {t.recentHistory}
                    {condensedHistory.skipped > 0 && (
                      <span className="text-slate-400 font-normal">({condensedHistory.skipped} {t.moreRecords})</span>
                    )}
                  </h3>
                  {historyLoading ? (
                    <div className="text-center text-slate-400 py-4 text-sm">Loading...</div>
                  ) : workerHistory.length === 0 ? (
                    <div className="text-center text-slate-400 py-4 text-sm">No records</div>
                  ) : (
                    <div className="space-y-1">
                      {/* Show newest 4 */}
                      {condensedHistory.items.slice(0, 4).map((item, idx) => (
                        <div key={item.id} className="flex items-center gap-3 text-xs py-1.5 border-b border-dashed last:border-0">
                          <span className={`px-2 py-0.5 rounded font-medium ${getActionColor(item.actionType)}`}>
                            {getActionLabel(item.actionType)}
                          </span>
                          <span className="text-slate-500 font-mono">
                            {format(new Date(item.actionDate), 'dd/MM/yyyy')}
                          </span>
                          <span className="flex-1 truncate text-slate-700">
                            {item.actionType === 'TRANSFER' ? (
                              <>{item.fromResidenceName || t.from} → {item.toResidenceName || t.to}</>
                            ) : (
                              <>{item.residenceName || getResidenceName(item.residenceId)} {item.roomName && `• ${item.roomName}`}</>
                            )}
                          </span>
                          {item.duration && (
                            <span className="text-slate-400">{item.duration}d</span>
                          )}
                        </div>
                      ))}
                      
                      {/* Separator if there are skipped records */}
                      {condensedHistory.skipped > 0 && (
                        <div className="flex items-center gap-2 py-2 text-slate-400">
                          <div className="flex-1 border-t border-dashed"></div>
                          <MoreHorizontal className="h-4 w-4" />
                          <span className="text-xs">{condensedHistory.skipped} {t.moreRecords}</span>
                          <MoreHorizontal className="h-4 w-4" />
                          <div className="flex-1 border-t border-dashed"></div>
                        </div>
                      )}
                      
                      {/* Show oldest 2 if there are more than 6 */}
                      {condensedHistory.skipped > 0 && condensedHistory.items.slice(4).map((item, idx) => (
                        <div key={item.id} className="flex items-center gap-3 text-xs py-1.5 border-b border-dashed last:border-0">
                          <span className={`px-2 py-0.5 rounded font-medium ${getActionColor(item.actionType)}`}>
                            {getActionLabel(item.actionType)}
                          </span>
                          <span className="text-slate-500 font-mono">
                            {format(new Date(item.actionDate), 'dd/MM/yyyy')}
                          </span>
                          <span className="flex-1 truncate text-slate-700">
                            {item.actionType === 'TRANSFER' ? (
                              <>{item.fromResidenceName || t.from} → {item.toResidenceName || t.to}</>
                            ) : (
                              <>{item.residenceName || getResidenceName(item.residenceId)} {item.roomName && `• ${item.roomName}`}</>
                            )}
                          </span>
                          {item.duration && (
                            <span className="text-slate-400">{item.duration}d</span>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Footer - Signature Area */}
                <div className="grid grid-cols-2 gap-8 pt-4">
                  <div className="text-center">
                    <div className="h-16 border-2 border-dashed border-slate-300 rounded-lg flex items-center justify-center text-slate-400 mb-2">
                      <span className="text-xs uppercase tracking-wider">{t.stamp}</span>
                    </div>
                  </div>
                  <div className="text-center">
                    <div className="h-16 border-b-2 border-slate-400 mb-2"></div>
                    <span className="text-xs text-slate-500 uppercase tracking-wider">{t.signature}</span>
                  </div>
                </div>

                {/* Generated By Footer */}
                <div className="text-center text-xs text-slate-400 pt-2 border-t border-dashed">
                  {t.generatedBy} • {format(new Date(), 'dd/MM/yyyy HH:mm')}
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {/* Empty State */}
      {!selectedWorker && searchResults.length === 0 && (
        <div className="flex items-center justify-center min-h-[60vh] print:hidden">
          <div className="text-center max-w-md">
            <FileText className="h-20 w-20 mx-auto mb-6 text-muted-foreground opacity-50" />
            <h2 className="text-2xl font-semibold mb-2">{t.emptyStateTitle}</h2>
            <p className="text-muted-foreground mb-6">{t.emptyStateDescription}</p>
            <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground">
              <div className="flex items-center gap-2">
                <User className="h-4 w-4" />
                {t.workerInfo}
              </div>
              <div className="flex items-center gap-2">
                <Home className="h-4 w-4" />
                {t.accommodationStatus}
              </div>
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4" />
                {t.history}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 10mm;
          }
          
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            background: white !important;
          }
          
          .print\\:hidden {
            display: none !important;
          }
          
          /* Force colors */
          .bg-gradient-to-r {
            background: #1e293b !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          .bg-green-50 { background-color: #f0fdf4 !important; }
          .bg-red-50 { background-color: #fef2f2 !important; }
          .bg-blue-50 { background-color: #eff6ff !important; }
          .bg-purple-50 { background-color: #faf5ff !important; }
          
          .text-green-700 { color: #15803d !important; }
          .text-red-700 { color: #b91c1c !important; }
          .text-blue-700 { color: #1d4ed8 !important; }
          .text-purple-700 { color: #7c3aed !important; }
          
          .border-green-100 { border-color: #dcfce7 !important; }
          .border-red-100 { border-color: #fee2e2 !important; }
          .border-blue-100 { border-color: #dbeafe !important; }
          .border-purple-100 { border-color: #f3e8ff !important; }
        }
      `}</style>
    </div>
  );
}
